### ISSUE TITLE
Unable to highlight all the issues in VS2017 through SonarLint.

### ISSUE THREAD

**Issue by ArshdeepSingh02** [SonarSource/sonarlint-visualstudio#1004]
We have Sonar OnPrem setup in our project. We have installed the Sonar Lint in VS2017. But it is showing only 86 code issues in VS whereas in SonarQube total 412 code smells are there.
We want to see all the issues reported in VS2017.
Please help.

### Related information

* SonarLint for VS Version
* Visual Studio Version (e.g. Professional v15.4.1) - 2017
* SonarQube server version - Latest
* Languages in your solution (C#, VB.Net, Javascript, C, C++) - C#

**Comment by duncanp-sonar** [comment]
@ArshdeepSingh02 have you looked for an answer on the [community forum](https://community.sonarsource.com/)? There are a number of posts that are probably relevant e.g. [this one](https://community.sonarsource.com/t/sonarlint-expected-behaviour-in-visualstudio/2662/2?u=duncanp).

**Comment by duncanp-sonar** [comment]
Closing due lack of activity. If you still have a problem, please create a new thread in the [community forum](https://community.sonarsource.com/c/help/sl).
