### ISSUE TITLE
Fix C# connected mode suppressions mechanism

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonarlint-visualstudio#1005]
### Description
The suppressions mechanism in SLVS has a poor user experience. There are a number of issues:

* when a solution in connected mode is opened, SLVS blocks VS from reporting issues until suppressions have been fetched from the server.

This is to prevent issues that have been suppressed from being reported. However, it's likely that this is causing VS to display a gold bar complaining that SLVS is causing VS to run slowly: see [SLVS #809](https://github.com/SonarSource/sonarlint-visualstudio/issues/809)

* in VS2017 and VS2019 analyzers can be run in a separate process, so the existing mechanism for suppressing issues does not work at all. See [SLVS #574](https://github.com/SonarSource/sonarlint-visualstudio/issues/574)

### Requirements
* no gold bar: VS should not be telling users that SLVS is causing a problem and giving the user an easy way to disable SLVS
* the user should be presented with a consistent set of issues; it should not be the case that issues are reported but then disappear later without the user having changed any code.

#### Nice to have:
* better logging to make it easy to understand when and why issues are being suppressed/not suppressed
* warn the user if suppressions are not applied e.g. because the server cannot be contacted
* simple trigger mechanism for user to force suppressions to be refreshed

#### Implementation options
1. Don't report any issues until the suppressions have been fetched
2. Save the suppressions locally in a file, and separate the logic that updates the file from the logic that reads the file and applies the suppressions.

The key problem is to decide how to handle analyzers being run out of process.

### Implementation notes
We decided to use a custom [DiagnosticSuppressor](https://docs.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.diagnostics.diagnosticsuppressor?view=roslyn-dotnet-4.1.0) that to suppress SonarC#/SonarVB. That means suppressions will work out of process. However, it means bumping the minimum supported version of VS to VS2019.3.
Related tickets:
* #2882 Drop support for VS2017
* #2892 Increase minimum supported VS2019 version to v16.3

### Related information

Replaces [MMF-1597](https://jira.sonarsource.com/browse/MMF-1597)

* Visual Studio Version: VS2019. ?VS2017?
* Languages in your solution: C#, VB.Net

**Comment by IT-CASADO** [comment]
Is there any expectation when this will be fixed?

**Comment by duncanp-sonar** [comment]
@IT-CASADO we are planning an overhaul of the entire Connected Mode experience in the second half of 2021, which includes how suppressions are handled.

**Comment by Bosch-Eli-Black** [comment]
Any update on this? 🙂

**Comment by duncanp-sonar** [comment]
@Bosch-Eli-Black we'll be looking at fixing the suppression part in Q1 2022

**Comment by Bosch-Eli-Black** [comment]
@duncanp-sonar Thanks! 🙂
