### ISSUE TITLE
Improve the performance (was MMF-1419)

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonarlint-visualstudio#1006]
Note: was [MMF-1419](https://jira.sonarsource.com/browse/MMF-1419)

### WHY
Visual Studio actively tracks the performance of third-party extensions and informs the user about extensions that are impacting the performance of the IDE, giving them the option to immediately disable the extension.

We do not want SonarLint to reported as impacting performance as this will discourage usage and adoption.

In addition, the VS Platform team are deprecating existing synchronous APIs used by extensions in favour of asynchronous alternatives that have less performance impact. They have also provided best practice recommendations for extenders. We need to modify SonarLint to remain compatible with future versions of Visual Studio and to follow the best practices.

It is likely that this focus on performance will continue for at least the remainder of the current VS ship cycle, and may require further work on our part as the platform APIs and recommendations evolve.

### WHAT
Some work has already been done to reduce the impact of SonarLint and maintain compatibility e.g.

* https://github.com/SonarSource/sonarlint-visualstudio/issues/647
* https://github.com/SonarSource/sonarlint-visualstudio/issues/679
* https://github.com/SonarSource/sonarlint-visualstudio/issues/681

The goal is to complete the remaining compatibility work and to review the code against the best practices to minimize the impact of SonarLint and so reduce the likelihood of SonarLint being flagged as causing performance issues to the end user.

h2. HOW

* convert the remaining package(s) to be asynchronous (see guidance [here|https://docs.microsoft.com/en-us/visualstudio/extensibility/how-to-use-asyncpackage-to-load-vspackages-in-the-background])
* review the performance of SonarLint to identify any other hotspots (see guidance [here|https://docs.microsoft.com/en-us/visualstudio/extensibility/how-to-diagnose-extension-performance])
* review the code to check that our extensions are not loaded until they are needed (i.e. packages are delay-loaded. Partial guidance is [here|https://docs.microsoft.com/en-us/visualstudio/extensibility/how-to-use-rule-based-ui-context-for-visual-studio-extensions]).
* contact SUPPORT to review any recent performance issues reported by customers

#### Out of scope
* daemon performance and memory consumption. The memory consumption of the daemon has been reported as an issue. However, this refers to the external Java process and so is not in scope for this MMF. -- UPDATE -- Java process is now not launched until it is needed, and is shutdown when a solution is closed -> reduced perf/memory impact

* analyzer performance. So far, we do not think that the SonarLint Roslyn analyzers are causing performance issues; the performance issues relate mainly to non-analyzer code trigger at startup or when a solution is loaded (e.g. relating to telemetry or notifications). Therefore the investigation of analyzer performance is out of scope for this MMF.

**Comment by Bouke** [comment]
Since installing the extension, I've noticed a lot more slowdowns that Visual Studio hasn't reported (yet). I'm tempted to just disable the extension. Loading a solution with 57 projects causes the UI to hang for several seconds. Visual Studio complains about this extension: 

> Visual Studio stopped responding for 6 seconds. Disabling the extension SonarLint for Visual Studio 2019 4.24.0.20196 might help. [Disable this extension] [Manage performance] [Don't report this extension again]

This (original) ticket is two years old yet, any updates?
