### ISSUE TITLE
Cognitive complexity custom threshold not taken into accounts (connected mode)

### ISSUE THREAD

**Issue by Indigo744** [SonarSource/sonarlint-visualstudio#1007]
### Description

In connected mode, when defining a custom threshold for the Cognitive complexity rule (`csharpsquid:S3776`), SonarLint still uses the default one (`15`).

I tried to search in GitHub issues, on StackOverflow and even and on the web, and I couldn't find any mention of this issue. I hope it's not a misconfiguration from my part.

### Repro steps

1. On SonarQube server, set a custom threshold for the Cognitive complexity rule
![image](https://user-images.githubusercontent.com/7137528/63500611-76f95380-c4ca-11e9-9871-58102f760f71.png)

2. In Visual Studio, set up connected mode to the project, synchronize, then compile. The S3776 rule still uses the default value:
![image](https://user-images.githubusercontent.com/7137528/63500688-9c865d00-c4ca-11e9-96a5-d5367dd2ea67.png)

### Expected behavior

In connected mode, the custom threshold should be used.

### Actual behavior

The custom threshold is ignored, and the rule always uses the default one.

### Related information

* SonarLint for VS Version **4.12.0**
* Visual Studio Version: **Enterprise 2019 v16.1.6**
* SonarQube server version: **7.9.0.26994**
* Languages in your solution: **C#, Javascript, TypeScript**

**Comment by duncanp-sonar** [comment]
@Indigo744 I think you are looking for this ticket: https://github.com/SonarSource/sonarlint-visualstudio/issues/176 _Additional files for parameterized SonarQube rules are retrieved from the SonarQube quality profile_

The ticket described a manual workaround until the feature is implemented.

**Comment by Indigo744** [comment]
Ah thank you. I wonder why I couldn't find this. Workaround works.

**Comment by Indigo744** [comment]
Ah, another related question: using the workaround, I synchronize manually the `SonarLint.xml` file, do I still need the connected mode? Since everything is in the XML, I wonder why stay in connected mode?
