### ISSUE TITLE
Unable to add the server URL for SonarLint

### ISSUE THREAD

**Issue by naveed-butt** [SonarSource/sonarlint-visualstudio#1008]
### Description

I have installed SonarLint on VS 2017 and VS 2019 and the issue was produced as follows.

When I click on Analyze -> ManageSonarQubeConnections, it opens the SonarQube TeamExplorer window on the right hand side, but I am unable to press the connect button (disabled) and specify the SonarQube server URL.

The out put window is stuck at...
`Finished initializing the daemon package.`

### Repro steps

Here are the steps

1. Click on Analyze -> Manage SonarQube Connections

2. Nothing happens that would ask me to put the server URL

### Expected behavior

It should open up a dialog where I can enter the SonarQube URL and credentials

### Actual behavior

Nothing happens

### Known workarounds

None, that I know of...

### Related information

* SonarLint for VS 2017 and VS 2019 (both)
* Visual Studio Version (e.g. Professional v15.9.13)
* SonarQube server Version 1.3
* Languages in your solution (C#)

**Comment by duncanp-sonar** [comment]
Hi @naveed-butt.  Do you have a solution open? If not, the `Connect` button will be disabled.

**Comment by naveed-butt** [comment]
Aaah. Yes. That was the issue. I thought, I was supposed to open a SonarQube Project from the server projects and directly connect to the repository.
