### ISSUE TITLE
Sync sonarLint with SonarQube 

### ISSUE THREAD

**Issue by pemola** [SonarSource/sonarlint-visualstudio#1009]
Hello,

I have installed SonarLint in Visual Studio 2015 update 3 and I use it in connected mode but I have noticed when I change a rule in SonarQube I can’t see the change in visual Studio if I don’t click “update” option of Team Explorer Window.
 I thought SonarLint throws a warning in visual studio if rules in sonarQube had changed.
 That way of work is correct? If SonarLint checks changes in sonarQube, How often does it check it? Is it possible to configure other frecuency in this case?

Thank you very much!

**Comment by duncanp-sonar** [comment]
Hi @pemola. Apologies for the delay in replying. In general, we recommend using the [community forum](https://community.sonarsource.com/c/help) for support questions as it is monitored by more people (both inside and outside SonarSource).

The check for modified rulesets is done when the bound solution is opened or the "update" button` is clicked. There isn't currently a periodic background check.

**Comment by pemola** [comment]
Thank you very much for you reply.
