### ISSUE TITLE
Limit Projects Retrievement on first connect

### ISSUE THREAD

**Issue by rfalcades** [SonarSource/sonarlint-visualstudio#1011]
When binding Sonarlint to sonarqube server, it retrives all projects.
In our scneario, we have about 40k projects (don't ask me if it is correct or no)

It frezzes UI and take so long to continue.

Maybe not retrieve all, or from a filter it would be a good idea.

Improve tests scenario using a server with a huge amount for projects to first binding.

### Related ticket(s)
* https://github.com/SonarSource/sonarlint-visualstudio/issues/949: _Fetching the list of projects should not be done on the UI thread_

**Comment by duncanp-sonar** [comment]
@rfalcades the "UI freezing" issue looks similar to #580 which was fixed in [v4.14](https://github.com/SonarSource/sonarlint-visualstudio/releases/tag/v4.14.0.12332).
Could you confirm whether you still see the problem in the newest version of SLVS please?
Thank you.
