### ISSUE TITLE
System.ArgumentException just after git checkout

### ISSUE THREAD

**Issue by loic-joly-sonarsource** [SonarSource/sonarlint-visualstudio#1012]
### Description

I had a yellow bar in Visual studio after doing a git checkout. I'm not sure if this is linked to SonarLint, to VS itself or to another extension. 

Full message: System.ArgumentException: The span does not belong to a source snapshot of the projection snapshot

### Repro steps

Unfortunately, unknown...

### Related information

* SonarLint for VS Version: 4.12.0.0
* Visual Studio Version (e.g. Professional v15.4.1): Entreprise 16.1.4
* SonarQube server version: None
* Languages in your solution (C#, VB.Net, Javascript, C, C++): C#

I attached the activity log.
[ActivityLog.log](https://github.com/SonarSource/sonarlint-visualstudio/files/3617386/ActivityLog.log)

**Comment by duncanp-sonar** [comment]
@loic-joly-sonarsource if the bug occurred with a solution that does not contain C++ or JavaScript then it's almost certainly a VS issue (we don't have any editor extensions for C#/VB.NET).

**Comment by loic-joly-sonarsource** [comment]
Since this was the case, I'm closing the issue.
