### ISSUE TITLE
C++ analyzer not working with msbuild props file

### ISSUE THREAD

**Issue by raduspa** [SonarSource/sonarlint-visualstudio#1014]
### Description

A visual C/C++ project contains msbuild property file(myCPP.props) that is used by AdditionalIncludeDirectories property will throw exception when is analyzed with sonarlint on visual studio 2019.

### Repro steps

Please provide the steps required to reproduce the problem

1. Create a C++ Console App with Visual Studio 2019 solution dir: c:\sample\test.sonarlint(check sample project attached)

2. create an msbuild prop file with name:  myCpp.props(check sample project attached)

3. import msbuild props file (myCpp.props) in .vcxproj project

4. open solution and open a CPP file

### Expected behavior

Analyzing C:\Users\spantioc\source\repos\test.sonarLint\test.sonarLint\test.sonarLint.cpp
DEBUG: Executing file C:\USERS\SPANTIOC\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\16.0_4BF4AA6E\EXTENSIONS\1XIHXFHU.IIT\lib\subprocess.exe
  Args: C:\Users\spantioc\AppData\Local\Temp\tmpA957.tmp 
  Working directory: 
  Timeout (ms):10000
  Process id: 12092
Initializing the telemetry package...
Finished initializing the telemetry package...
Initializing the daemon package...
Finished initializing the daemon package.
Initializing the notifications package...
Not connected: not checking for notifications
Finished initializing the notifications package
DEBUG: Process returned exit code 0
Found 1 issue(s)

### Actual behavior

Unable to collect C/C++ configuration for C:\Users\spantioc\source\repos\test.sonarLint\test.sonarLint\test.sonarLint.cpp: System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.IsPathRooted(String path)
   at SonarLint.VisualStudio.Integration.Vsix.CFamily.MsvcDriver.Absolute(String basePath, String relativeOrAbsolutePath)
   at SonarLint.VisualStudio.Integration.Vsix.CFamily.MsvcDriver.ToRequest(Capture[] captures)
   at SonarLint.VisualStudio.Integration.Vsix.CFamily.CFamilyHelper.FileConfig.ToRequest(String path)
   at SonarLint.VisualStudio.Integration.Vsix.CFamily.CFamilyHelper.TryGetConfig(ILogger logger, ProjectItem projectItem, String absoluteFilePath)

### Known workarounds

Update value of AdditionalIncludeDirectories from props file in one line with no spaces.

### Related information

* SonarLint for VS Version
* Visual Studio Version  Professional 16.1.4
* Languages in your solution C++ 

**Sample project**
[sample.sonarLint.zip](https://github.com/SonarSource/sonarlint-visualstudio/files/3653847/sample.sonarLint.zip)

**Comment by duncanp-sonar** [comment]
Thanks for reporting the issue and particularly for the repro project @raduspa.
We'll fix this bug in the next release.

**Comment by raduspa** [comment]
Thank you!
