### ISSUE TITLE
Visual studio doesn't show all the projects from the server

### ISSUE THREAD

**Issue by Prabhakarakolar** [SonarSource/sonarlint-visualstudio#1022]
### Description

Visual studio doesn't show all the projects from the server. if projects count is more than 1500.

### Repro steps

1. Create more than 1500 projects in sonarqube server.
2. Install Sonarlint on Visual studio 2017/2019 try to connect with credentials (analyze --> Manage SonarQube connections).
3. List doesn't show all the projects , it shows limited set.
4. Try to search project which is not displayed in list.

### Expected behavior
Using Search option it should be possible to find and bind any project.

### Actual behavior

Visual studio is not showing all the projects.

### Known workarounds

No

### Related information

* SonarLint for VS Version - 2019
* Visual Studio Version (e.g. Professional v16.2.5))
* SonarQube server version - 7.9
* Languages in your solution (C#)

**Comment by rita-gorokhod-sonarsource** [comment]
@Prabhakarakolar I was not able to reproduce this issue. Please try upgrading your SonarLint extension and see if it still happens; there have been fixes around connected mode.
If it still happens please reopen the issue.

**Comment by appyit3** [comment]
I'm also getting this same issue. To reproduce, the number of projects in sonarqube have to be large. Then along with other git extensions, sonarqube is shown. But all the projects are not listed.

**Comment by Prabhakarakolar** [comment]
One work around for this issue is you can change your repository name to
display at higher alphabetical order.

In my case I have Added prefix A to Repository name.

There was no change in the key.

Regards,
Prabhakar

**Comment by rita-g-sonarsource** [comment]
@Prabhakarakolar @appyit3 - Can you please check how many projects do you actually have? we have a limit of 10000, can you please confirm if you have more than that? (you can see how many you have in SonarQube/SonarCloud UI, when you go to the projects list).

**Comment by Prabhakarakolar** [comment]
Hello Rita,

We have approx 2000 projects.

Regards

**Comment by higorcoimbra** [comment]
@rita-g-sonarsource can you explain what fields we have to edit from .slconfig file, please? And I couldn't find a "re-bind" function inside Visual Studio (currently using VS 2019). Thanks for the workaround!

**Comment by rita-g-sonarsource** [comment]
Hi @higorcoimbra. Open your .slconfig and you will need to change the following:

- ServerUri (in case it's on a different SonarQube server)
- Organization (in case it's on a different SonarCloud organization. You can get the key on the ["organizations"](https://sonarcloud.io/account/organizations) page).
- ProjectKey: the key of the new project that you want to bind to. You will see it in the URL when you navigate to your SQ/SC server, e.g. `https://sonarcloud.io/summary/new_code?**id=sonarlint-visualstudio**`
- ProjectName: the name of the new project. This is just the display name, that you can see in the UI of your SQ/SC server.

Save the file, re-open the solution in VS and go to the SonarQube page in Team Explorer. You might need to re-input the credentials. Let me know if it works for you.

**Comment by higorcoimbra** [comment]
@rita-g-sonarsource I followed the listed steps but when I try to acess the SonarQube page in Team Explorer, I'm getting the message "Bound project with key 'XXXXXXX' was not found on the connected server. Select a different SonarQube project, or use a different login that has access to the desired project.", although there is no difference on configuration between projects on the top of the list (those I can bind inside VS 2019) and the one I'm trying to bind, they all have the same permissions for me.

Things I've already check:
- I'm using the correct key.
- Project access and permissions are OK (same as every one in the server).

Other considerations:
- The list inside Visual Studio has 499 projects and the server has 856 projects, the project I'm trying to bind is above the 499th project.

Seems like even when I'm trying to bind using the .slconfig, the Extension is searching only on the 499th (first page) of the GET request on my Server URL. Can I do some workaround using query string or something to retrieve all of the projects?

**Comment by rita-g-sonarsource** [comment]
@higorcoimbra can you please execute the following API call against your SQ server?
`[SQ full ur]/api/components/search_projects?asc=true&p=1&ps=500` 
(along with the relevant basic authentication, see [here](https://docs.sonarqube.org/latest/extend/web-api/)).

You should be getting a response in the format of
```
{
"paging": {
"pageIndex": 1,
"pageSize": 500,
"total": <number of projects in your SQ server>
},
"organizations": [...],
"components": [...],
"facets": [...],
}
```

Couple of questions:
1. What is your SQ version?
2. When you run the query above, does the API return back the expected number of projects under "total" field?
3. What happens when you re-run the web api call, this time when `p` parameter (page number) is 2, 3, etc? (e.g. `api/components/search_projects?asc=true&p=2&ps=500`). Do you get back the correct results?
