### ISSUE TITLE
C++ rule enablement: do not allow project-level rules to be enabled

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonarlint-visualstudio#1024]
### Description

Currently some project-level C++ rules are disabled by default in SonarLint (i.e. rules that look at more than a single file). The rule-enablement UI should not list these rules.

List of disabled rules:
~~https://github.com/SonarSource/sonar-cpp/blob/00bf8bfa95c7eadbbf3aed2c092ba81b147b88e8/sonar-cfamily-plugin/src/main/java/com/sonar/cpp/plugin/AbstractRulesDefinition.java#L30~~
* S5536

**Comment by abbas-sabra-sonarsource** [comment]
@duncanp-sonar @rita-gorokhod-sonarsource I'm updating the list of project-level rules:https://github.com/SonarSource/sonar-cpp/pull/839/files#diff-1c8c8ae2888c5848a89ff459b2843418R30

- We currently have only one: S5536
- The first three used to be project-level but they stop after we moved to clang front-end.
- I will create a "new issue" every time we add a new project-level rule to the list. There is no plan to add soon.
- S5536 is not clang-based:
> CLang-based rule S5536 should also be disabled.

**Comment by duncanp-sonar** [comment]
The list of unavailable rules is shown in the SonarLint output window:

![image](https://user-images.githubusercontent.com/10757559/77671206-29245c80-6f7f-11ea-9bf7-3eb037e41521.png)
