### ISSUE TITLE
How to re-connect to a different SonarQube server

### ISSUE THREAD

**Issue by mayureshs** [SonarSource/sonarlint-visualstudio#1089]
After downloading the VS2019 extension I had the configuration set to a test-ing sonar qube server. Now that we have moved to production how do I change the connection and re-enter credentials ? Thanks!

**Comment by duncanp-sonar** [comment]
Closing as a duplicate of [this Community forum question](https://community.sonarsource.com/t/reconnect-sonarlint-to-a-different-sonarqube-server/16660).
