### ISSUE TITLE
Embed SonarCFamily 6.6

### ISSUE THREAD

**Issue by abbas-sabra-sonarsource** [SonarSource/sonarlint-visualstudio#1162]
sonarlint-visualstudio is currently on SonarCFamily 6.3.
[6.4 release notes](https://jira.sonarsource.com/secure/ReleaseNote.jspa?projectId=10090&version=15013)
[6.5 release notes](https://jira.sonarsource.com/secure/ReleaseNote.jspa?projectId=10090&version=15220)
[6.6 release notes](https://jira.sonarsource.com/secure/ReleaseNote.jspa?projectId=10090&version=15281)

Changes that might impact SLVS: 
- 6.5: Project-level rules (currently we have only S5536) should always be disabled for SLVS.
- 6.6: Incremental analysis is transparent to SLVS. Currently, it doesn't make sense to support it, since we don't analyze the entire project.
- 6.6: Automatical creation of the reproducer is transparent to SLVS. At some moment in time, it might make sense to propagate this new feature to SLVS.

**Comment by duncanp-sonar** [comment]
Manually tested on vanilla VS2015.3, vanilla VS2017 and latest VS2019. The latest binaries are installed and one of the new rules correctly raises.

Added a unit test to check that S5536 is disabled by default. We don't have a mechanism for ensure that project-level rules are never enabled (that's the subject of by #1024).

**Comment by duncanp-sonar** [comment]
@abbas-sabra-sonarsource Thanks for the links to the release notes and for calling out potentially impactful changes - very helpful.
