### ISSUE TITLE
Custom Sonar rules error/warnings not detected

### ISSUE THREAD

**Issue by AnanthaSubramanian** [SonarSource/sonarlint-visualstudio#1184]
### Description
I am using SonarQube 7.9.1 LTS. I have created a custom sonar rule. I deployed the plugin in local sonarqube instance, created from VS2017 - 15.7.6 version. I created a project in local sonarqube instance. This project I mapped with both Quality gate and Quality Profile where I enabled my custom sonar rules as well.
After this in my visual studio 15.7.6 version I downloaded Sonarlint extension and used managed connection and gave the local instance url and the project I created before.
When I did a build to my sample project which violated the custom sonar rule, I was expecting a warning/error for the violation of custom rules.  In actual I was only seeing some warnings for other sonar rule violations but not for the custom rules.

Please provide a succinct description of your issue.
Custom Sonar rule violation not detected.
### Repro steps

Please provide the steps required to reproduce the problem
As mentioned in Description.
1. Step A
 Create a custom sonar rule using VS 2017 15.7.6 version.
2. Step B
Deploy plugin in SonarQube 7.9.1 LTS.
3.Step C
Create a project in SonarQube.
4.Step D
Map the project created in Step C with custom Quality Gate and add conditions for any error/warnings greater than zero.
5.StepE
Map the project created in Step C with custom Quality Profile.
6.StepF
Add new custom rules to the Quality Profile you created in Step E.
7.StepG
Create a sample violation project so as the custom rules created above can detect a issue/warnings.
8.StepH
Using Manage SonarQube Connection connect to local sonarqube instance where plugin was deployed in Step B.
 
If possible then please create a git repository with a repro sample or attach a zip to the issue.
I will not be able to provide the plugin as it is proprietary to the company I work. It would be a violation if I attach the plugin here.
 
### Expected behavior

Please provide a description of the behavior you expect.
When I did a build to my sample project which violated the custom sonar rule, I was expecting a warning/error for the violation of custom rules. 
### Actual behavior

Please provide a description of the actual behavior you observe.
 In actual I was only seeing some warnings for other sonar rule violations but not for the custom rules.
### Known workarounds

Please provide a description of any known workarounds.

### Related information

* SonarLint for VS Version
* Visual Studio Version (e.g. Enterprise v15.7.6)
* SonarQube server version - 7.9.1 LTS
* Languages in your solution (C#)

**Comment by duncanp-sonar** [comment]
How did you create your custom rule? Was it as a Roslyn analyzer, and did you then use the [SonarQube Roslyn SDK](https://github.com/sonarsource/sonarqube-roslyn-sdk) to create a custom SonarQube plugin?

If so, then unfortunately that is the expected behaviour. SonarLint is not able to dynamically register your custom Roslyn analyzer with Visual Studio so that it is executed in the IDE.

To get your custom analysis rules to run in the IDE, you would have to either ship them as a VSIX and install it on each developer machine, or add a reference to your analyzer NuGet package to each project (i.e. just what you would normally do to run custom Roslyn analysis rules).

There is some good news: in connected mode, the ruleset generated by SonarLint will contain the settings for your custom rules (have a look at the generated ruleset in the solution-level `.sonarlint` folder to check), so at least you will be able to manage the rule configuration centrally on SonarQube in the Quality Profile.

**Comment by AnanthaSubramanian** [comment]
> .sonarlint

Thanks much for the prompt reply. 
>>How did you create your custom rule? Was it as a Roslyn analyzer, and did you then use the SonarQube Roslyn SDK to create a custom SonarQube plugin?

Yes,  I had used SonarQube Roslyn SDK.

Earlier with  SDK ver 1.0 as well I had generated the plugin and deployed in SonarQube and I remember that time Sonarlint was working for custom rules scanning as well.
I would like to request your team to add this as a feature enhancement as this will add easy way for developers to check the code for sonar issues before they checkin.
Currently Jenkin Plugin based on MSBuild works on CI/CD however, that is in action only when a check-in is committed. It would be good if sonarlint can bring this feature as then before check-in developer can scan and fix and then commit the changes when the changes are appropriate for check-in.

**Comment by AnanthaSubramanian** [comment]
Also, one more suggestion - In Readme if it can be mentioned saying - "The current version supports only SonarQube default rules and does not support custom rules created using SonarQube Roslyn SDK" it will help readers.

**Comment by duncanp-sonar** [comment]
Thanks for the suggestion. I've updated the readme for the [SonarQube Roslyn SDK](https://github.com/SonarSource/sonarqube-roslyn-sdk) project.

SonarLint for VS in Connected Mode used to install the SonarC#/VB analyzer NuGet packages (I can't remember whether it also installed third-party analyzers packaged using the SDK but it might have done).

However, we stopped adding the analyzer NuGet packages based on feedback from users: the analyzer NuGet packages made local builds on dev machines slower, and updating the SonarC#/VB plugins on the server forced updates to every bound project.

**Comment by sodeshpa21** [comment]
> How did you create your custom rule? Was it as a Roslyn analyzer, and did you then use the [SonarQube Roslyn SDK](https://github.com/sonarsource/sonarqube-roslyn-sdk) to create a custom SonarQube plugin?
> 
I have created Custom rule Analyzer project with Roslyn and placed jar in extension
Later used Sonarscanner build commands with project key, but the rules are not getting scanned.. Does SonarScanner not recognize the analyzers?

**Comment by sodeshpa21** [comment]
> > How did you create your custom rule? Was it as a Roslyn analyzer, and did you then use the [SonarQube Roslyn SDK](https://github.com/sonarsource/sonarqube-roslyn-sdk) to create a custom SonarQube plugin?
> 
> I have created Custom rule Analyzer project with Roslyn and placed jar in extension
> Later used Sonarscanner build commands with project key, but the rules are not getting scanned.. Does SonarScanner not recognize the analyzers?

I am doing exactly what is said in below link
https://stackoverflow.com/questions/57455993/what-do-i-missed-to-apply-for-sonarqube-custom-rules-using-fxcop 

To get round all of these limitations, you can use the SonarQube Roslyn SDK to generate a custom SonarQube plugin jar that packages up your custom Roslyn analyzer. You don't need to write any code; just run RoslynSonarQubePluginGenerator.exe against your Roslyn NuGet package and it will create a plugin jar.

Once you install that generated custom SonarQube plugin into your SonarQube instance, you will be able to configure your rules in the Quality Profile, mark issues as FPs etc, and the Scanner for MSBuild will take care of executing your analysis rules as part of the build so you don't need to reference your custom Roslyn analyzer NuGet package from every MSBuild project you want to analyse.

**Comment by duncanp-sonar** [comment]
@sodeshpa21 please don't post unrelated questions to a closed thread.
If you have a support question, please create a thread in the [community forum](https://community.sonarsource.com/c/help/8).
