### ISSUE TITLE
'Connect to SonarQube' screen freezes and VS is frozen

### ISSUE THREAD

**Issue by rita-gorokhod** [SonarSource/sonarlint-visualstudio#1217]
### Description

When connecting a new project to SonarQube, the 'connect' screen freezes (see attachment).
Seems to happen on only one of my monitors, the other one works fine. Might be a DPI issue.

### Repro steps

TBD

### Expected behavior

Screen works correctly.

### Actual behavior

Screen freezes, VS is frozen.

### Known workarounds

Might be a DPI issue, works on another monitor.
EDIT: It freezes only on the non main monitor. When the monitor is main, it doesn't happen.

### Related information

* SonarLint for VS Version - 4.17
* Visual Studio Version - 2019 16.4.4

**Comment by rita-gorokhod-sonarsource** [comment]
![Capture](https://user-images.githubusercontent.com/60586879/73926267-a876a780-48cf-11ea-9097-0cf82efe4b84.PNG)

**Comment by duncanp-sonar** [comment]
Closing as can't repro for now.
