### ISSUE TITLE
Store suppression list locally

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonarlint-visualstudio#1267]
### Description

The list of CFamily suppressions will be stored on the local machine and refreshed periodically.

### TODO
- [ ] decide where the data should be stored. See notes below for more background
- [ ] implement and test

### Notes:
Local storage of suppressions: this would need to be per-solution.

VS does provide an API for per-user per-solution storage (saved in encoded form in hidden `.suo` file).
Questions: how much data will need to store? Will it make the file too big? What's the behaviour if the user deletes the .suo file?

A simpler alternative would be to store a file in the hidden `.vs` directory, although we'd need to check whether this is supported (or whether there is a different API for this).

**Comment by rita-gorokhod-sonarsource** [comment]
@duncanp-sonar as we discussed offline, I'm closing this as "Won't fix". It's not a problem for CPP and the fix for C# might be different (e.g. can be similar to what we do in other IDEs).
