### ISSUE TITLE
Visual Studio 2015, 2017 and 2019  Extension "Cannot analyze header files"

### ISSUE THREAD

**Issue by Juan-Ramirez-Alvarez** [SonarSource/sonarlint-visualstudio#1304]
### Description

Visual Studio versions 2015, 17 and 19 do not analyze header files in C++.
It does not matter if using local user settings files or grabbing rules from SonarQube server
Using extension version 4.20.0.16339

### Repro steps
1. Begin a C++ project in any of the above listed visual studio versions
2. Install the appropriate SonarLint extension to the Visual Studio version being run
3. Create a .h file
4. See Visual Studio SonarLint window give error "Cannot analyze header files. File: <filename>"
5. Verify in .h source window that no linting was done with SonarLint

Is this a known defect or missing feature?

### Expected behavior

Linting should happen in .h files
Although not much logic is typically implemented, some orgs have implemented full logic in header.
This is the limitation I'm currently running into, while trying to verify if my changes to a header are fixing security vulnerabilities shown in SonarQube.

### Actual behavior

No linting happens in C++ headers
See output regarding this in linter output window

### Known workarounds

NA

### Related information

* SonarLint for VS Version 4.20.0.16339
* Visual Studio Version Professional/Enterprise 2015-2019
* SonarQube server version - UNKNOWN/ Not relevant
* Languages in your solution - C++

**Comment by Juan-Ramirez-Alvarez** [comment]
https://github.com/SonarSource/sonarlint-visualstudio/pull/677
Does this mean it is not supported?

**Comment by duncanp-sonar** [comment]
@Juan-Ramirez-Alvarez that's correct, analysing header files in SLVS is not currently supported.
