### ISSUE TITLE
Lint / integration for monaco editor

### ISSUE THREAD

**Issue by GlauberF** [SonarSource/sonarlint-visualstudio#1317]
hello I'm new here and I'm sorry if this is not the right place for this.

I have an online CMS that I use the monaco editor (https://microsoft.github.io/monaco-editor/) to edit the code, I want to include the sonar with it.
how I could do this integration, if you have any example, I thank you.

**Comment by duncanp-sonar** [comment]
Hi @GlauberF,
I've don't know if this is possible, but it sounds interesting!

SonarLint is also available as a [VS Code plugin](https://github.com/sonarsource/sonarlint-vscode) so that might be a better place to start as VS Code is based on Monaco. @henryju might be able to give more info.
