### ISSUE TITLE
Gold bar appears when opening a large C# solution in Connected Mode

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonarlint-visualstudio#1318]
### Description

Reported by @gjactat 

> Open a pretty large C# solution.
Event with no file opened at all. The simple fact of opening the solution makes SonarLint hang for 19 seconds.
I understand that SonarLinat has a lot to process during startup. Could this work be done asynchronously ?

### Repro steps

![image](https://user-images.githubusercontent.com/10757559/78803694-339b1900-79b7-11ea-83a1-f3e4960703a4.png)

### Expected behavior

No gold bar.

### Actual behavior

Gold bar and UI freezes (?)

### Known workarounds

Please provide a description of any known workarounds.

### Related information

* SonarLint for VS Version: ?
* Visual Studio Version (e.g. Professional v15.4.1) ?
* Languages in your solution: C#

TODO: also check initial bind to a large solution e.g. Akka. This has been reported as triggering a gold bar.

**Comment by duncanp-sonar** [comment]
@gjactat thanks for reporting the issues.

FYI the packages are all initialised asynchronously (VS2019 no longer support synchronously initialisation). However, some VS services need to be called in the UI thread, which might account for the delay.

A few questions that would help us investigate:
* how large is a pretty large solution?
* does the delay happen if the solution is opened in standalone mode? (you can switch the solution from Connected Mode to standalone by temporarily deleting the solution level `.sonarlint` folder then restarted VS).

Thanks.

**Comment by gjactat** [comment]
Thank you @duncanp-sonar for taking time to answer (and sorry for having reported this issue in the wrong thread).
The Visual Studio solution consists of : 

- 120 projects (csproj files)
- ~5000 C# files

Loading that solution in connected mode takes +/- 19 seconds. Visual Studio freezes during pretty much of that duration. Golden bar appears.

Loading the solution in disconnected mode doesn't produce any freeze. Golden bar doesn't show up.

Hope this helps !
Guillaume

**Comment by duncanp-sonar** [comment]
Could be the same underlying issues as #809

**Comment by duncanp-sonar** [comment]
Closing a likely duplicate of #2791, fixed in v5.2.
