### ISSUE TITLE
Apply server settings in connected mode

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonarlint-visualstudio#1335]
### Description
SLVS does not apply server-side settings when reporting issues in the IDE, leading to differences between the issues reported in the IDE and on the server. See [Narrowing the Focus](https://docs.sonarqube.org/latest/project-administration/narrowing-the-focus/) for more information.

Related: [MMF-1230](https://jira.sonarsource.com/browse/MMF-1230)

### Workaround
None.

TODO: check which settings are applied in other SL flavours.

#### SonarLint Core
Supported: `sonar.inclusions`, `sonar.exclusions`, `sonar.test.inclusions`, `sonar.test.exclusions`, ` sonar.issue.ignore.multicriteria`, `sonar.enforce.multicriteria`

#### Implementation notes
The filtering logic should be the same for all supported languages. However, based on our recent experience of fixing suppressions for C#/VB.NET, we'll probably need a different mechanism to prevent issues being raised for those languages from the other languages in which we are in control of execution and reporting of issues
i.e. one mechanism for C#/VB.NET, another for CFamily, JS/TS etc

The recent Roslyn suppressions work suggests that it will be difficult to provide a good filtering experience from the VS side; it might be necessary to implement the logic in the analyzers.

**Comment by StingyJack** [comment]
This is really frustrating

**Comment by duncanp-sonar** [comment]
@StingyJack FYI
> is this the same reason why my azure devops pipelines report all kinds of things during compilation that dont show up as issues in the portal?

No - analysis in CI pipelines is completely separate.

**Comment by facusantillo** [comment]
Is there any workaround to apply the same rules and exclusions in sonarlint for visual studio? Since connected mode does not sync the exclusions it's nearly impossible for the dev team to identify which ones make sense from those who doesn't

**Comment by StingyJack** [comment]
@facusantillo - there is always `// NOSONAR`

@duncanp-sonar  does sonar lint at least honor the properties file if its included in the repo?

**Comment by duncanp-sonar** [comment]
@facusantillo:
> Is there any workaround to apply the same rules and exclusions in sonarlint for visual studio?

No. If we know of a workaround we would always aim to describe it in the ticket. I'll amend the description above to make that explicit.

@StingyJack
> does sonar lint at least honor the properties file if its included in the repo?

No. If that worked this ticket wouldn't be necessary.

**Comment by StingyJack** [comment]
@rita-sonarsource is this actually done and available?

**Comment by rita-sonarsource** [comment]
> @rita-sonarsource is this actually done and available?

Hello @StingyJack, this is now available for C/CPP. I've created a follow up ticket for C# #3093.
