### ISSUE TITLE
CFamily: support pre-commit analysis

### ISSUE THREAD

**Issue by abbas-sabra-sonarsource** [SonarSource/sonarlint-visualstudio#1349]
**Is your feature request related to a problem? Please describe.**
Before pushing a new commit would be helpful to display the new issues introduced.

**Describe the solution you'd like**
Support pre-commit analysis.

**Describe alternatives you've considered**
Analyze and check manually the newly introduced code.

**Comment by duncanp-sonar** [comment]
Closing as obsolete. Support for showing issues in new code is on the product backlog for all languages in all flavours of SonarLint (H2 2023?)
