### ISSUE TITLE
By embedding SonarC# 5.9, SonarLint provides 32 new rules (23 activated by default)

### ISSUE THREAD

**Issue by fmallet** [SonarSource/sonarlint-visualstudio#135]
**New Rules on SonarWay profile**
* Rule S3247: Duplicate casts should not be made
* Rule S2386: Mutable fields should not be "public static"
* Rule S3885: Assembly.Load should be used
* Rule S3869: "SafeHandle.DangerousGetHandle" should not be called
* Rule S3884: "CoSetProxyBlanket" and "CoInitializeSecurity" should not be used
* Rule S1215: "GC.Collect" should not be called
* Rule S3889: Neither "Thread.Resume" nor "Thread.Suspend" should be used
* Rule S3887: "readonly" mutable collection and array fields should be private
* Rule S3877: Exceptions should not be thrown from unexpected methods
* Rule S3875: Do not overload "operator ==" on reference types
* Rule S3871: Exception types should be "public"
* Rule S2376: Write-only properties should not be used
* Rule S2342: Enumeration types should comply with a naming convention
* Rule S1206: "Equals(object)" and "GetHashCode()" should be overridden in pairs
* Rule S1110: Redundant parentheses should be removed
* Rule S3897: Classes that override "Equals(<T>)" or "Equals(Object)" should implement "IEquatable<T>"
* Rule S110: Inheritance tree of classes should not be too deep
* Rule S3903: Types should be defined in named namespaces
* Rule S1104: Fields should not have public accessibility
* Rule S2436: Generic types should not have too many parameters
* Rule S1118: Classes with only static members should be sealed
* Rule S3904: Assemblies should have version information
* Rule S3926: Deserialization methods should be provided for "OptionalField" members

**New Rules (disabled by default)**
* Rule S3902: Don't use Assembly.GetExecutingAssembly()
* Rule S2156: "sealed" classes should not have "protected" members
* Rule S3881: "IDisposable" should be implemented correctly
* Rule S3880: Finalizers should not be empty
* Rule S3876: Strings or integral types should be used for indexers
* Rule S3874: "out" and "ref" parameters should not be used
* Rule S3872: Parameter names should not duplicate the names of their methods
* Rule S3898: Value types should implement "IEquatable<T>"
* Rule S2325: Methods and properties that don't access instance data should be static

**Bug-fix/F-P/Kill the Noise**
* Fix S1144: Avoid FP on partial classes
* Fix S2357: Rule should not report on public fields in structs nor on non-public nested classes.
* Fix S2583: Avoid FP on Singleton pattern implementation with lock
* Fix S3316: No unused parameters should be spotted on empty, unsupported or "Main(string[] args)" methods
* Fix S1144 to not raise on serialization constructor for exceptions
* Rule S1854: update to ignore initializations to 1, 0, null, true, false
* Rule S3814: improve the rule to handle <= and >= operators
* Rule S2275: Improve the rule to detect more cases and to be able to raise for more methods using string formatting.
* Rule S3457: Rule should handle unused arguments and missing item index

**Comment by Evangelink** [comment]
PR #144
