### ISSUE TITLE
Embed SonarCFamily 6.9.0.17076 

### ISSUE THREAD

**Issue by abbas-sabra-sonarsource** [SonarSource/sonarlint-visualstudio#1351]
sonarlint-visualstudio is currently on SonarCFamily 6.8.

[Release Notes](https://jira.sonarsource.com/secure/ReleaseNote.jspa?projectId=10090&version=15643).

Things to adapt:
- S5782 should be added to the list of not supported rules in SonarLint. [The full story](https://discuss.sonarsource.com/t/impact-of-security-council-decisions-on-sonarcfamily/4541).

**Comment by abbas-sabra-sonarsource** [comment]
@duncanp-sonar & @rita-g-sonarsource, 

We were doing some investigation sprint on Cfamily side to see if it is possible to improve symbolic execution performance. We stumbled on a performance bug that was introduced in clang 10. Cfamily 6.9 contains the upgrade from clang 9 to Clang 10.  I will close this issue to avoid introducing this bug to SonarLint. I will create another ticket to upgrade directly to 6.10 when it is released.

**Comment by Godin** [comment]
For the reference - https://jira.sonarsource.com/browse/CPP-2511

Jira Query to retrieve known issues - [`project = CPP AND affectedVersion >= 6.9`](https://jira.sonarsource.com/issues/?jql=project%20%3D%20CPP%20AND%20affectedVersion%20%3E%3D%206.9)
