### ISSUE TITLE
Provide a digital signature to the extension

### ISSUE THREAD

**Issue by fmallet** [SonarSource/sonarlint-visualstudio#136]
As the vsix is not signed at the moment, when you install it you have a message saying this extension comes from an unknown publisher.

https://msdn.microsoft.com/en-us/library/dd997171.aspx

**Comment by Evangelink** [comment]
- [ ] Choose the identity to sign with
- [ ] Get a SSL certificate
- [ ] Add the NuGet package to the VSIX project
- [ ] Update CI job to sign the extension
- [ ] Test the newly signed extension
