### ISSUE TITLE
[Javascript/Daemon] Issues should use the severity specified in the Quality Profile

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonarlint-visualstudio#1385]
### Description
See #808 [C#/VB] Issues should use the severity specified in the Quality Profile.

The JavaScript analyzer/daemon has the same issue.

At present the severity is hard-coded to `Warning` [here](https://github.com/SonarSource/sonarlint-visualstudio/blob/558296b44d059b55830e22a0553c8613f038d4a0/src/Integration.Vsix/SonarLintTagger/IssuesSnapshot.cs#L90) the sseverity is incorrect in both standalone mode and connected mode.

NOTE: currently blocked:
* we don't currently support connected mode for JavaScript

Parent issue: #884

**Comment by rita-sonarsource** [comment]
Outdated
