### ISSUE TITLE
Sonar issues does not shown unless you open files on local analysis

### ISSUE THREAD

**Issue by MentallyYours** [SonarSource/sonarlint-visualstudio#1420]
Sonar issues does not completely shown at ErrorList part of VisualStudio after building the sln. But when you open a cs file including a issue, the issue comes as warning to ErrorList part. This directs developers wrongly, and they complain about why SonarLint by default not showing all codesmells after build. Is there any setting to show all issues by default ? 
Sonar ruleset already imported in the sln. 

* SonarLint for VS Version (4.21.0.16909)
* Visual Studio Version (Microsoft Visual Studio Enterprise 2019 Version 16.5.3)
* Languages in solution (C#, Javascript )

**Comment by duncanp-sonar** [comment]
Hi @MentallyYours 

Please ask support questions in the [community forum](https://community.sonarsource.com/). The forum is monitored by more SonarSourcers and community members so your question is likely to be answered more quickly (if the answer isn't already available in the forum). It also helps other forum users who have similar questions.

The short answer is that the SonarC#/VB analyzers are normal Roslyn analyzers, and how and when they are run is handled by Visual Studio.

The longer answer is that it depends on whether you have installed the analyzers using a NuGet package or using a VSIX (like SonarLint), what options you have set in VS, and which version of VS you are using.

The standard behaviour for VSIX analyzers is described in the [VS docs](https://docs.microsoft.com/en-us/visualstudio/code-quality/configure-live-code-analysis-scope-managed-code?view=vs-2019).
VSIX analyzers are not run on build, and by default only open documents are analysed, although this is configurable.
NuGet analyzers are run on build, and in VS2019 can also be configured to run "live" in the IDE.

The Sonar analyzers are also available as NuGet packages: [SonarAnalyzer.CSharp](https://www.nuget.org/packages/SonarAnalyzer.CSharp/) and [SonarAnalyzer.VisualBasic](https://www.nuget.org/packages/SonarAnalyzer.VisualBasic/)
