### ISSUE TITLE
Changes in SonarLint.xml file are not picked up until VS is restarted

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonarlint-visualstudio#1421]
### Description

Rules parameters in `SonarLint.xml` files are being correctly updated when the parameters are updated on the SonarQube server. However, the new settings are not being used by the analyzers lead to incorrect analysis results.

On investigation, this looks like a bug in the sonar-dotnet analyzers. See SONAR-DOTNET [#3361](https://github.com/SonarSource/sonar-dotnet/issues/3361)

After discussion with the PM, this has a significant enough adverse impact on the UX of "improve CM" milestone for us to delay the release.

**Comment by duncanp-sonar** [comment]
The related bug is fixed. Manually verified the fix in VS - the new settings are picked up immediately.
This bug can be closed as soon as the new version of the analyzer is released and SLVS is updated to embed it.

**Comment by Rora** [comment]
@duncanp-sonar thank you for all the work on the connected mode improvements. My team and I have been following this project for some time now and are wondering if you could give us a ballpark figure (days/weeks/months?) on when the 'SLVS' impedement will be resolved and the connected mode improvements will most likely make it to master.

**Comment by duncanp-sonar** [comment]
Hi @Rora. No problem, and thanks for your interest.
The next version of the SonarC# plugin is scheduled for release this Friday/next Monday. We'll release the next version of SLVS as soon as we can after that, so I'll be disappointed if it's any later than next Monday/Tuesday.
