### ISSUE TITLE
Epic: re-imagine the binding workflow

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonarlint-visualstudio#1428]
### Description

The user experience of the binding workflow is not good; it's not easy to discover, it doesn't differentiate between SonarQube and SonarCloud, and it requires too much manual input.
It is also has technical issues: too complicated, and too much custom code.

We want to rework the whole binding experience to be simpler, easier to find and use, and to reduce the amount of user input required. In addition, we want to simplify the storage of the configuration information.

This ticket is a place-holder for the overall epic.

### TODO
* design the new workflow and UI. Do we want the new workflow to be the same/similar to that in other flavours of SonarLint, or do we want to change the binding workflow in the other flavours too?
* which authentication mechanisms should be supported? Should third-party identity providers be supported? See also #180.

### Low-level requirements
* the UI should not be hosted in the Team Explorer
* the UI should be aware of both SonarQube and SonarCloud
* the UI should handle user name + password and token-based authentication separately
* drop our custom progress UI controls in favour of standard VS UI components.

### Other points to consider
* impact on legacy connected mode, if any. Do we have to drop support for legacy mode as part of this change? If so, we need to communicate with users about deprecation and think about migration paths.
* handling of test projects: should we configure test projects to use the QP rules/no Sonar rules/do nothing? (note: check with the DotNet team/Scanner guild - it's possible the behaviour of the S4MSB will be changed to run rules against test projects. See e.g. [this ticket](https://github.com/SonarSource/sonar-dotnet/issues/4062)).
* storing binding configuration: the current method for storing binding configuration is predicable but intrusive (see the [wiki](https://github.com/SonarSource/sonarlint-visualstudio/wiki/Connected-Mode-configuration-for--C%23-and-Visual-Basic-projects) and #2221 for more info). It is possible to have a less intrusive configuration e.g. using `Directory.Build.props` as we do in [this repo](https://github.com/SonarSource/sonarlint-visualstudio/blob/master/Directory.Build.props), but that is dependent on the other factors to work (i.e. solution layout, presence of other `Directory.Build.props` files, contents of the individual solutions). Can we simplify the configuration without sacrificing the predictability e.g. by allowing the user more control over the  storage.?

### Related issues
#914 
#935 
#1247
#1198

**Comment by cacti77** [comment]
I certainly agree the UX is poor - see https://community.sonarsource.com/t/failing-to-connect-to-sonarqube-server-from-visual-studio-2019-invalid-credentials/28071 . Having easily connected to a different, Python, project in PyCharm via its SonarLint plugin, the experience in VisualStudio was far from intuitive.
