### ISSUE TITLE
Update Project-level rulesets documentation

### ISSUE THREAD

**Issue by rita-g-sonarsource** [SonarSource/sonarlint-visualstudio#1431]
Document the logic behind project-level rulesets (when do we amend the existing ruleset? when do we reference the solution ruleset? when do we create a new ruleset?)

**Comment by duncanp-sonar** [comment]
See https://github.com/SonarSource/sonarlint-visualstudio/wiki/Connected-Mode-configuration-for--C%23-and-Visual-Basic-projects
