### ISSUE TITLE
SonarLint for VS with TFS version control not usable

### ISSUE THREAD

**Issue by csoltenborn** [SonarSource/sonarlint-visualstudio#147]
SonarLint 2.11.0 for Visual Studio has severe problems with .ruleset files if TFS is used as the backing version control system (I assume that this is not an issue when using Git). The problems are described in detail in [this StackOverflow question](http://stackoverflow.com/questions/43113882/using-sonarlint-for-visual-studio-with-tfs-sharing-rulesets-accross-development).

**Comment by Evangelink** [comment]
Hi @csoltenborn. Sorry for the delay in the answer of your problem we are now back on track and will follow the questions with more rigor. I am closing this thread, let's continue the discussion on StackOverflow (your original post).

**Comment by csoltenborn** [comment]
Apparently I can not re-open this issue myself, but since there hasn't been any help on the according StackOverflow question, I wish I could :-|
