### ISSUE TITLE
[CFamilySensor] Investigate if there are missing post-processing steps

### ISSUE THREAD

**Issue by rita-gorokhod** [SonarSource/sonarlint-visualstudio#1524]
### Description

Go over the post-processing logic inside the [CFamilySensor.java](https://github.com/SonarSource/sonar-cpp/blob/master/sonar-cfamily-plugin/src/main/java/com/sonar/cpp/plugin/CFamilySensor.java#L603) and investigate if there are any missing bits that are relevant to SLVS.
Previously discovered differences: 
- #1489
- #2149 (missing logic: https://github.com/SonarSource/sonar-cpp/blob/master/sonar-cfamily-plugin/src/main/java/com/sonar/cpp/plugin/CFamilySensor.java#L879)

**Comment by duncanp-sonar** [comment]
@abbas-sabra-sonarsource I think so. The recent changes were all about changing the input messages.
This is about checking what is being returned, which hasn't changed recently.

**Comment by duncanp-sonar** [comment]
Closing as obsolete. We'll deal with any specific issues as they are reported
