### ISSUE TITLE
SonarLint integration package did not load correctly with VS 2015 Update 1

### ISSUE THREAD

**Issue by pichika** [SonarSource/sonarlint-visualstudio#153]
Hi,
I just installed SonarLint for Visual Studio 2015 from the below link
https://marketplace.visualstudio.com/items?itemName=SonarSource.SonarLintforVisualStudio

When I opened Visual studio(2015), it shows the message "sonarlint integration package did not load correctly"
Looked at activityLog.xml and found the below error 

<errorinfo>Could not load file or assembly 'Microsoft.CodeAnalysis.Workspaces, Version=1.3.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.</errorinfo

Is "Microsoft.CodeAnalysis.Workspaces" not part of the package?
Could someone please help me to resolve this issue?

Thanks.

**Comment by brunoshine** [comment]
I've also got this with VS2015 Update1. Any known workaround?
thanks

**Comment by fmallet** [comment]
@pichika, which update of VS2015 are you using ? Thanks

**Comment by pichika** [comment]
Hi,
I am using VS2015 Update1. Do we have any workaround for this issue?

Thanks.
