### ISSUE TITLE
SonarLint for Visual Studio 17 Plugin 4.23.0.19399 Crashing After Several Hours Use

### ISSUE THREAD

**Issue by MicrosoftComments** [SonarSource/sonarlint-visualstudio#1536]
### Description

Happening repeatedly with 4.23.0.19399

### Repro steps

1. Use Visual Studio 2017 for a few hours
2. Wait for it to crash.
3. Have a look in the ActivityLog.xml file and see the error.

I'll see if I can find any pattern to it, but frankly you're in a better place to figure out what is happening than me.

### Expected behavior

I can use Visual Studio for 8 hours without the plugin crashing.

### Actual behavior

Crashes after two hours or so work Visual Studio produces the 'a plugin has crashed' dialog with directions to the following debug information in the activitylog.xml:

  <entry>
    <record>1210</record>
    <time>2020/07/16 15:09:26.467</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.NullReferenceException: Object reference not set to an instance of an object.&#x000D;&#x000A;   at SonarLint.VisualStudio.Integration.Vsix.TextBufferIssueTracker.UpdateIssues(IEnumerable`1 issueMarkers)&#x000D;&#x000A;   at SonarLint.VisualStudio.Integration.Vsix.TextBufferIssueTracker.HandleNewIssues(IEnumerable`1 issueMarkers)&#x000D;&#x000A;   at SonarLint.VisualStudio.Integration.Vsix.AccumulatingIssueConsumer.Accept(String path, IEnumerable`1 issues)&#x000D;&#x000A;   at SonarLint.VisualStudio.Integration.Vsix.TextBufferIssueTracker.RequestAnalysis(IAnalyzerOptions options)&#x000D;&#x000A;   at SonarLint.VisualStudio.Integration.Vsix.TextBufferIssueTracker.AddTagger(IssueTagger tagger)&#x000D;&#x000A;   at SonarLint.VisualStudio.Integration.Vsix.TextBufferIssueTracker.CreateTagger()&#x000D;&#x000A;   at SonarLint.VisualStudio.Integration.Vsix.TaggerProvider.CreateTagger[T](ITextView textView, ITextBuffer buffer)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.GatherTaggers(ITextBuffer textBuffer)&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)</description>
  </entry>

### Known workarounds

Visual Studio is still usable without the plugin, so it can be restarted.

### Related information

* SonarLint for VS Version 4.23.0.19399
* Visual Studio Community 2017 15.9.19. 
* SonarCloud
* C / C++ win32 project
* Windows 10 Pro 64-bit (10.0, Build 18363) (18362.19h1_release.190318-1202)

**Comment by duncanp-sonar** [comment]
Thanks for reporting the issue @MicrosoftComments. In case it helps with finding a pattern, my guess is that it's something to do with the background analysis returning an issue for a file/location that no longer exists because of subsequent edits.
