### ISSUE TITLE
Embed C#/VB.net analyzer 8.10.0.19839

### ISSUE THREAD

**Issue by andrei-epure-sonarsource** [SonarSource/sonarlint-visualstudio#1538]
Release notes: https://github.com/SonarSource/sonar-dotnet/releases/tag/8.10.0.19839

**Comment by andrei-epure-sonarsource** [comment]
Note that https://github.com/SonarSource/sonar-dotnet/issues/3421 didn't get fixed in 8.10, it will in 8.11.

**Comment by rita-g-sonarsource** [comment]
Won't fix, will embed 8.11 instead.

**Comment by duncanp-sonar** [comment]
@rita-g-sonarsource does v8.10 introduce a regression? If not, why wouldn't we embedding v8.10 if we are going to ship before v8.11 is available?

**Comment by rita-g-sonarsource** [comment]
@duncanp-sonar you're right, I added it back to the sprint.

**Comment by andrei-epure-sonarsource** [comment]
it doesn't have a regression, it just should be tested that it doesn't show S5766 issues in the IDE (S5766 was added in 8.9 as a security hotspot, and it shows issues when running as a nuget in 8.9 and 8.10, and this gets fixed in 8.11)
