### ISSUE TITLE
Embeds SonarC# 5.10 and benefits from 10 new rules

### ISSUE THREAD

**Issue by Evangelink** [SonarSource/sonarlint-visualstudio#154]
Link to the release:
[https://github.com/SonarSource/sonar-csharp/milestone/1?closed=1](https://github.com/SonarSource/sonar-csharp/milestone/1?closed=1)

**Comment by fmallet** [comment]
And benefits from the following new rules 

- SonarSource/sonar-csharp#166 : Rule S2365: Properties should not make collection or array copies
- SonarSource/sonar-csharp#214: Rule S1751: Jump statements should not be used unconditionally
- SonarSource/sonar-csharp#165: Rule S2589: Boolean expressions should not be gratuitous
- SonarSource/sonar-csharp#147: Rule S3915: Conditions should not unconditionally evaluate to "false"
- SonarSource/sonar-csharp#208: Rule S3967: Multidimensional arrays should not be used
- SonarSource/sonar-csharp#206: Rule S3963: "static" fields should be initialized inline
- SonarSource/sonar-csharp#210: Rule S3971: "GC.SuppressFinalize" should not be called
- SonarSource/sonar-csharp#168: Rule S3925: "ISerializable" should be implemented correctly
- SonarSource/sonar-csharp#160: Rule S2365 - Properties should not make collection or array copies
- SonarSource/sonar-csharp#161: Rule: Check ArgumentException instantiations for argument names
