### ISSUE TITLE
Allow the user to hide adornments for a flow issue

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonarlint-visualstudio#1623]
### Description

Feedback from the PM on the implementation of secondary locations in other SL flavours: there are scenarios in which the user might not want to see the editor adornments e.g.
* cognitive complexity
* some rules that have multiple steps on a single line/over a few lines.
In this case, the adornments can be annoying, and the user might want to hide them.
They could do this by selecting a different issue, but this isn't obvious and requires navigating away from the editor to the Error List.
The high-level request is for a simple command to allow the user hide the adornments e.g. pressing Escape.

### TODO - decide what the UX should be
There are questions about the experience that need to considered before implementing a solution e.g.
* is this a general problem, or is it a special case for a few specific rules e.g. cognitive complexity? If specific, then perhaps we should be looking at a different solution, such decorating cognitive complexity issues differently.
* how long are the adornments hidden for - just until another issue is selected, or until the user asks to see them again?
* should hiding the adornments have any effect on the flow panel or Error List?

Possible solution:
Add a VS command that clears the currently selected issue that could be activate by a key combination.

However, `Esc` already has a global mapping to switch focus back to the current editor window. We should not override this global mapping. We might be able to chain our command to hide the adornments too, but even if we can it's not clear that this is what a user who currently uses `Esc` would want - they might still want to see the adornments.

Relates to https://jira.sonarsource.com/browse/MMF-2098

**Comment by rita-g-sonarsource** [comment]
Fixed by #1724
