### ISSUE TITLE
Show toolwindow command should be visible and enabled

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonarlint-visualstudio#1700]
### Description

Currently the "show tool window" command (`Views`, `Other windows`, `SonarLint Issue Visualization`) is not visible unless an issue with a secondary location is selected. This makes the command hard to find. It should at least be always visible.

TODO:
* ?should it also be always enabled? Yes.
* add the command to the SonarLint group in the Error List context menu
* change the flow panel overlay message to refer to SonarLint issues with secondary locations, and include a link to the wiki home page

**Comment by rita-g-sonarsource** [comment]
@duncanp-sonar There is a problem with making the command always visible ( = not attached to a context): it means that the user can manually open it and leave it opened when VS shuts down. It will cause a goldbar to appear next time VS is opened, complaining about our window.
