### ISSUE TITLE
Fix Visualization tool window auto show/hide + gold bar

### ISSUE THREAD

**Issue by rita-g-sonarsource** [SonarSource/sonarlint-visualstudio#1714]
Make sure that the auto show/hide works + there is no goldbar

![image](https://user-images.githubusercontent.com/60586879/109790202-74280480-7c11-11eb-8860-c7aaa5c003bd.png)

Clicking on the `Manage performance` button shows the following dialogue:

![image](https://user-images.githubusercontent.com/10757559/109847749-79a04180-7c47-11eb-9eca-a8861a87dd90.png)

#### Occurrence and impact
The tool window will appear/disappear automatically based on the state of the UIContext as long as the user does not do a manual action that "breaks" the tracking. Once the tracking is broken it will stay broken until the user takes a manual action to restore it e.g.
* using the menu command to show the tool window when the UIContext is active, or
* manually closing the tool window when the UIContext is not active.

The only scenario in which the gold bar will appear is if tracking is a broken, and the tool window was open when VS shuts down.
In that case, the tool window will be shown again on startup, potentially leading to the appearance of the gold bar.

However, this appearance of this gold bar is not a serious as the gold bars which suggest that the offending extension should be disable. This gold bar merely effects the specific tool window. The gold bar can also appear for built-in VS tool windows.

#### Interaction between ToolWindowVisibility and "Transient" setting on ToolWindow attribute
The ToolWindow attribute has a "Transient" boolean property. If set to true, the tool window will never be open at startup, even if it was open when VS closed.

However, the "transient" setting appears to be ignored if the ToolWindowVisibility attribute is also present.

**Comment by duncanp-sonar** [comment]
Closing as won't fix. The occurrence should be low, the impact is relatively low (in that the user is not prompted to disable the whole extension), and there is isn't an simple, reliable fix.
