### ISSUE TITLE
UX: "show visualization" doesn't ensure the tool window is visible

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonarlint-visualstudio#1733]
### Description

[UX, Minor]

The issue visualization pane is not always visible after selecting the "show visualization" light-bulb command.

### Repro steps

1. Open a file with secondary locations
2. Move the caret in the editor to an issue with secondary locations
3. Select the "show visualization" lightbulb command -> tool window opens
4. Switch to another docked tool window in the same group e.g. the Solution Explorer
5. Select a "normal" issue in the Error List i.e. one that doesn't have secondary locations -> tool window closes
6. Repeat steps 2 & 3. 

### Expected behavior

The tool window is opened top-most i.e is visible.

### Actual behavior

The tool window is opened but isn't top-most. The highlights/adornments do appear in the editor, though.

![image](https://user-images.githubusercontent.com/10757559/93622700-7be24c80-f9d5-11ea-8d1e-ee4078af2f80.png)

### Known workarounds

None

### Related information

* SonarLint for VS Version: unreleased v4.26 (WIP)

**Comment by rita-g-sonarsource** [comment]
Fixed by #1738
