### ISSUE TITLE
issues mismatch with SonarQube server and sonarlint in connected mode.

### ISSUE THREAD

**Issue by Sandeep321** [SonarSource/sonarlint-visualstudio#1734]
### Description

We are having a sonar Qube server and we have a project configured there. It shows a lot of issues there- in the 100's.
I got the sonlarlint extension installed for VS2019 and then I connected my project in VS2019 to the SonarQube server.  I can see that it has pulled the ruleset files etc for my local system from the server. So, I am running in the connected mode now. Please let me know if this behavior is correct and any other details which could help.

### Expected behavior

My understanding was that it will show all issues in my local also with sonar lint so that I can fix them before pushing my code to the server.

### Actual behavior

Surprisingly, I am seeing only a few issues in my VS2019 solution- around 26. but server shows around 500

### Related information

* SonarLint for VS Version - VS Extension
* Visual Studio Version (2019 - v16.7.3)
* SonarQube server version
* Languages in your solution (C#)

**Comment by rita-g-sonarsource** [comment]
Hi @Sandeep321, thank you for reporting this issue to us.
We have an open [issue](https://github.com/SonarSource/sonarlint-visualstudio/issues/1336) that lists reasons why some issues might appear on the server but not in the IDE. If your use case does not match any of the reasons listed above, please provide further information:
* Which rules are you not seeing in the IDE
* What is your SonarLint version
