### ISSUE TITLE
Additional files for parameterized SonarQube rules are retrieved from the SonarQube quality profile

### ISSUE THREAD

**Issue by fmallet** [SonarSource/sonarlint-visualstudio#176]
Some analyzer (SonarQube analyzer for C#) requires additional files to be passed to the compiler to configure some rules (parametrized rules).
this is done in the continuous integration (See Scanner for MSBuild), but not yet for the connected experience.

Related [MMF-510](https://jira.sonarsource.com/browse/MMF-510)

Here are the parametered rules:

C# and VB.NET

- S2342 EnumNameShouldFollowRegexBase
- S1067 ExpressionComplexityBase
- S104 FileLinesBase
- S1541 FunctionComplexityBase (cyclomatic complexity)
- S134 FunctionNestingDepthBase
- S103 LineLengthBase

C#

- S110 AvoidExcessiveInheritance
- S1451 CheckFileLicense
- S3776 CognitiveComplexity
- S1541 FunctionComplexity
- S2436 TooManyGenericParameters
- S1479 TooManyLabelsInSwitch
- S107 TooManyParameters

VB.NET

- S101 ClassName
- S2343 EnumerationValueName
- S2347 EventHandlerName
- S2348 EventName
- S1542 FunctionName
- S114 InterfaceName
- S117 LocalVariableName
- S2304 NamespaceName
- S1654 ParameterName
- S2366 PropertyName
- S2373 TypeParameterName
- S2375 UseWithStatement 
- S2362 PrivateConstantFieldName
- S2364 PrivateFieldName
- S2363 PrivateSharedReadonlyFieldName
- S2367 PublicConstantFieldName
- S2369 PublicFieldName
- S2370 PublicSharedReadonlyFieldName

All of them are disabled by default, except S1479, which have been tuned lately to not report on enums and therefore we don't expect false positives with the default max value (30).

Comes from [SVS-5](https://jira.sonarsource.com/browse/SVS-5)

**Comment by FarisFAhmed** [comment]
Hi,

you said:
_this is done in the continuous integration (See Scanner for MSBuild), but not yet for the connected experience._

does this mean that default rule parameters like _maximumLineLength_ in rule S103 can be changed when scanning using sonar-scanner-msbuild-2.3.2.573?
If this is possible in msbuild can you tell me how?

Regards,
Faris Ahmed

**Comment by duncanp-sonar** [comment]
@FarisFAhmed you would change the rule parameter on the SonarQube server. Log in, browse to the Quality Profile, find the appropriate rule, and edit the parameters associated with it.

The Scanner for MSBuild downloads the parameters from the server during the _begin_ step and passes them to the analysers automatically.

**Comment by duncanp-sonar** [comment]
**Manual workaround**
This manual workaround enables the analysers to use a static copy of the rule parameters:

1. Run the _Scanner for MSBuild_ _begin_ step locally for the solution.
2. Copy the _SonarLint.xml_ file from _.sonarqube\conf\cs_ to a location within the solution.
3. Edit each C# project file in the solution to include the following snippet (changing the path to the file as appropriate):

```
  <ItemGroup>
    <AdditionalFiles Include="Properties\SonarLint.xml" />
  </ItemGroup>
```

The _SonarLint.xml_ file contains the rule parameters from the server. Adding it to the  _AdditionalFiles_ ItemGroup means it will be passed to the analyzers.

**Comment by Evangelink** [comment]
For example, we use it to specify a different file header for all our C# project. Here is the csproj of one of our [project](https://github.com/SonarSource/sonar-csharp/blob/master/sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/SonarAnalyzer.CSharp.csproj#L120).

**Comment by Roraa** [comment]
Is there any plan to fix this in the near future? Sonarlint isn't really finished without this feature IMO.

**Comment by Indigo744** [comment]
Hello,

Is there an ETA for enabling this in connected mode?
The workaround works, but it can be tedious when updating new rules.

Thanks a lot for your hard work.
