### ISSUE TITLE
Modify SonarQubeClient to include flow information

### ISSUE THREAD

**Issue by rita-g-sonarsource** [SonarSource/sonarlint-visualstudio#1761]
### Description

GetIssuesRequest returns SonarQubeIssue item which does not contain flow information needed to display vulnerabilities. We need to modify SonarQubeIssue to include flow information. 

(Commit from prototype: https://github.com/SonarSource/sonarqube-webclient-dotnet/commit/7fb9a245b8cf4cebfd354774d5ea1b0e56052f31)

**Comment by duncanp-sonar** [comment]
https://github.com/SonarSource/sonarqube-webclient-dotnet/pull/60
