### ISSUE TITLE
Output FileConfig to allow easier troubleshooting 

### ISSUE THREAD

**Issue by rita-g-sonarsource** [SonarSource/sonarlint-visualstudio#1769]
#### Description

When users experience C/C++ analysis failures, it is difficult to understand what is the problem.
A current way is to ask them for a reproducer file, however sometimes that is not enough, e.g. if the problem is on SonarLint's side in the way that we collect the configuration (for example: #1630, #1537).
Providing a way to output the collected configuration (FileConfig) would help to troubleshoot these problems.

TODO: 
- [x] check the FileConfig class can be serialized easily
- [x] change the "CreateReproducer" command to also serialize the FileConfig in the same location as the reproducer file.
- [x] update the wiki documentation: https://github.com/SonarSource/sonarlint-visualstudio/wiki/Troubleshooting-problems-with-C-or-Cpp-analysis

**Comment by abbas-sabra-sonarsource** [comment]
@rita-g-sonarsource, I wonder if we should add a TODO to deserialize the FileConfig and generate a request from it. This way, we will be able to easily debug the request generation. WDYT?

**Comment by duncanp-sonar** [comment]
@abbas-sabra-sonarsource Sounds good. Rather than adding a TODO, create a ticket and label it with the `Infrastructure` tag.
