### ISSUE TITLE
SonarQube ruleset should win over local ruleset

### ISSUE THREAD

**Issue by fmallet** [SonarSource/sonarlint-visualstudio#177]
After initially binding a project to SonarQube or after having re-synched it, at least all rules enabled in SonarQube should be executed.
However at the moment, if the project's own ruleset sets S1186 for example to None to disable it, then even after a resynch, the rule S1186 will remain disabled. This enables developers to use a more permissive quality profile than the one configured on the server without having to ask for a dedicated quality profile, which isn't good.
From an implementation point of view, the location of the `<Include Path="..\sonarqube\sonaranalyzer-csharp-vbnetcsharp.ruleset" Action="Default" />` element in the ruleset doesn't seem to have any impact: Roslyn seems to use the last specified value and discard the inherited one.

Comes from [SVS-23](https://jira.sonarsource.com/browse/SVS-23)

**Comment by Evangelink** [comment]
No longer relevant.
