### ISSUE TITLE
Logging when navigating unsupported file types is too verbose

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonarlint-visualstudio#1770]
### Description

It is common for C++ projects to contain file types that cannot be analyzed. Navigating these produces a lot of output messages in the Output Pane that clutter the pane and make it difficult to see more important/relevant output.

#### Current behaviour
1) When an unsupported file is opened, two "unsupported file type" messages are logged: one from the PCH analysis request, and one for the "normal" analysis request.
2) When a previously opened file is activated again, another PCH request is created which logs another "unsupported file type" message.

It is the second behaviour that is generating the noise.

Ignoring the crash of the unsupported file as it will be fixed in another ticket, we see the same message for the same unsupported file:
![image](https://user-images.githubusercontent.com/49131500/95365722-ce2ad500-08d2-11eb-8099-0056130e131e.png)

#### Proposed behaviour
Don't log "unsupported" messages when creating PCH analysis requests, so there would be only only one "unsupported type" message logged in case (1) and none for case (2).

Related PR: #1766

Related ticket: #788 _Enable different logging levels_

**Comment by abbas-sabra-sonarsource** [comment]
Ignoring the crash for the unsupported file as it will be fixed in another, we can see the same message for the same unsupported file:

![image](https://user-images.githubusercontent.com/49131500/95365236-2a412980-08d2-11eb-82a2-459bb27d85ce.png)
