### ISSUE TITLE
Warn the user to remove old SonarLint NuGet packages

### ISSUE THREAD

**Issue by fmallet** [SonarSource/sonarlint-visualstudio#178]
The VSIX checks whether the analyzers (SonarAnalyzer) included with the VSIX are also installed as NuGet packages and, if so, disables the VSIX analyzers.
However, it does not check whether the user has older versions of the SonarLint NuGet package installed (different package name). If they do, then they will get duplicate errors being reported, one by the VSIX and one from the SonarLint NuGet package.
Consider warning the user to manually uninstall the old SonarLint NuGet packages to avoid the duplicates.

Comes from [SVS-32](https://jira.sonarsource.com/browse/SVS-32)

**Comment by Evangelink** [comment]
No longer relevant.
