### ISSUE TITLE
Support binding to a Secure SonarQube Server

### ISSUE THREAD

**Issue by fmallet** [SonarSource/sonarlint-visualstudio#180]
As the SonarQube AAD OAuth 2 provider will be available, we need to let the user provide credentials through the OAuth 2 handshake (which might include 2 factors authentication).
Today, if the user tries to connect to a server on which HTTPS was enabled with a self signed certificate, and on which the AAD OAuth provider was installed, providing whatever credentials (including the corporate credentials), s/he'll get the following error:
https://servername:9090/ SonarQube request failed: 
An error occurred while sending the request. The underlying connection was closed: 
Could not establish trust relationship for the SSL/TLS secure channel. 
Connecting to SonarQube server: Failed
This improvement requires more spec on the flow, but the current dialog is probably not sufficient to let the user use authenticate with OAuth 2. It seems that most applications delegate to a sign-in UI which leverages some browser.

Comes from [SVS-42](https://jira.sonarsource.com/browse/SVS-42)

**Comment by usmonster** [comment]
Was this implemented?

**Comment by duncanp-sonar** [comment]
@usmonster no. This ticket is three years old, and quite a bit has changed on the server-side.
This ticket has been superceded by #1428. We'll consider the types of authentication to support as part of the overall re-evaluation of the binding experience.

**Comment by usmonster** [comment]
Thanks for the response, @duncanp-sonar. I'll follow the other issue, then!
