### ISSUE TITLE
Context menu layout/style does not respond to high contrast mode or other style changes

### ISSUE THREAD

**Issue by fmallet** [SonarSource/sonarlint-visualstudio#182]
The context menu on the server/project tree does not respond to VS theme/style changes nor does it support High Contrast mode in Windows.

Repo steps:
1. In Windows, enable high contrast mode
2. In VS, go to Tools > Options > Enironment > Fonts and Colors, and change the environment font to Comic Sans size 15
3. Open a bound solution
4. Right click on a project/server in the Team Explorer > SonarQube page

Comes from [SVS-52](https://jira.sonarsource.com/browse/SVS-52)

**Comment by fmallet** [comment]
![actual_highcontrast](https://cloud.githubusercontent.com/assets/548729/26192656/e75ee2fa-3bb2-11e7-89da-ab9e7f37d73a.png)
![actual_vsstyles](https://cloud.githubusercontent.com/assets/548729/26192655/e75d9b98-3bb2-11e7-92d5-bb2b2fdc943a.png)
![expected_highcontrast](https://cloud.githubusercontent.com/assets/548729/26192657/e75eec82-3bb2-11e7-8b11-614b3130bba8.png)
![expected_vsstyles](https://cloud.githubusercontent.com/assets/548729/26192658/e7652cbe-3bb2-11e7-9ba2-9cdd96595d33.png)

**Comment by ugras-ergun-sonarsource** [comment]
We don't support non standard themes for now.
