### ISSUE TITLE
Improve the handling of compiler unsupported options

### ISSUE THREAD

**Issue by abbas-sabra-sonarsource** [SonarSource/sonarlint-visualstudio#1841]
### Description
Currently, when an unsupported compiler option is provided we see a stacktrace in the output:
![image](https://user-images.githubusercontent.com/49131500/97334064-8b7a6e00-187c-11eb-8c14-d62ff8e5e56b.png)
This is usually interpreted by the users as SonarLint is failing and is not working as expected. While in reality, this is not the case. We intentionally don't support these options (like "/std:c++latest" and "/ZW").

### Proposed solution:
Log the message when an option is not supported without the stacktrace.

**Comment by duncanp-sonar** [comment]
@abbas-sabra-sonarsource I have a quick question about one of the arguments for which we currently throw an `InvalidOperationException`: [unexpanded response file](https://github.com/SonarSource/sonarlint-visualstudio/blob/6b9a8a7623906def168229d9089bf6e17a9c00a4/src/Integration.Vsix/CFamily/PortedFromJava/MsvcDriver.cs#L254).

Is this a valid argument that we don't support, and for which we should return a friendlier message?

**Comment by abbas-sabra-sonarsource** [comment]
@duncanp-sonar I never got a report about it. The only way to hit this path is to have an unexpanded response file in the additional option. It is not a feature like /std:latest that everybody uses. So maybe it is worth keeping it with the unfriendly message to get a report in case a user faces it.  By the way support for std:latest should be coming soon in the next release.
