### ISSUE TITLE
UX - due to VS handling of rule set delete the user will end up in and invalid state

### ISSUE THREAD

**Issue by fmallet** [SonarSource/sonarlint-visualstudio#185]
1. Bind solution to SQ project
2. Once bound, delete the project rule set
3. Bind again
Expected: the rule set will be re-created. 
Actually: two rule sets will be created (one will be including the other in some cases).

More info:
When deleting the rule set VS will also clear the rule set value for the active configuration, but will leave the non active configuration value as it was (so using the no-longer available project rule set).
When we rebind since there are two different rule set per configuration we will create two rule sets and the one that had no existing file will now be referencing the newly created rule sets instead of not referencing anything.

Technically speaking, there's no bug but the UX is quite confusing and we should be able to fix it by applying a bit of heuristics (i.e. if the file doesn't exist and the name was as the project file name we treat is as empty). 

Comes from [SVS-65](https://jira.sonarsource.com/browse/SVS-65)

**Comment by Evangelink** [comment]
No longer relevant with the new connected mode.
