### ISSUE TITLE
Refactor IAnalysisIssueVisualizationConverter and separate conversion from span calculations

### ISSUE THREAD

**Issue by rita-gorokhod** [SonarSource/sonarlint-visualstudio#1857]
#### Description

IAnalysisIssueVisualization was used up until now only for live analysis issues, where the analyzed document was already open. This allowed us to calculate the relevant span when creating IAnalysisIssueVisualization.

However, hotspots are fetched from the server and the analyzed document doesn't have to be open. Therefore, there is no text buffer, and we cannot calculate the spans.

The current implementation of IAnalysisIssueVisualizationConverter does two things:
1. Creating an issue viz object 
2. Assigning spans to all locations in a given text buffer

The second part is not relevant for hotspots. In order to support hotspots, conditions were added to the code to disable this functionality. 
The class should instead be refactored and the span calculations logic should be taken out.

**Comment by duncanp-sonar** [comment]
Closing as obsolete; there is now no special-case handling for hotspots in the converter.
