### ISSUE TITLE
Add a command to unbind a project

### ISSUE THREAD

**Issue by fmallet** [SonarSource/sonarlint-visualstudio#188]
There's no simple way to unbind a bound project.
The obvious command users will try is Disconnect but this doesn't affect the binding.
An "unbind" command would remove the items added to the solution-level SonarQube folder and remove the inclusion of the server ruleset from the project-level ruleset.
Optionally, it could also remove the project-level if it has no other rules and has a name that suggests it was created by the extension when binding.
![disconnectcmdmisleading](https://cloud.githubusercontent.com/assets/548729/26193443/a0a0fde6-3bb5-11e7-8d77-69c8e7a674a0.png)

Comes from [SVS-79](https://jira.sonarsource.com/browse/SVS-79) and [SVS-80](https://jira.sonarsource.com/browse/SVS-80)

**Comment by Evangelink** [comment]
This will be available when using the new connected mode.
