### ISSUE TITLE
Customize secondary locations panel for hotspots

### ISSUE THREAD

**Issue by rita-gorokhod** [SonarSource/sonarlint-visualstudio#1902]
#### Description

Support customizing secondary locations panel for hotspots information.

TODO:
- [ ] Instead of Issue Severity icon, display hotspot priority (high/medium/low)

**Comment by duncanp-sonar** [comment]
Closing as obsolete. The "hotspot" concept will become obsolete with the move to the Clean Code Taxonomy so this isn't worth changing.
