### ISSUE TITLE
Change ThreadHelper.SetCurrentThreadAsUIThread to return a disposable scope

### ISSUE THREAD

**Issue by rita-gorokhod** [SonarSource/sonarlint-visualstudio#1906]
#### Description

`ThreadHelper.SetCurrentThreadAsUIThread` is changing static members and is not changing them back when the test ends.
This creates a pollution of tests when the entire test suite runs.

TODO:
- [ ] Return a disposable scope, similar to AssertIgnoreScope, that will revert the changes once the test ends.

Notes: could extend `HackedVSThreadingScope` to handle this too.

**Comment by duncanp-sonar** [comment]
Closing as obsolete. The tests should be changed to use the `IThreadHandling` interface instead.
