### ISSUE TITLE
Navigating to/from the SonarQube view takes a long time

### ISSUE THREAD

**Issue by fmallet** [SonarSource/sonarlint-visualstudio#193]
When connecting to a server with a lot of projects (sonarqube.com for example) the SonarQube team explorer view loads all available projects. It then takes quite a long time when navigating from/to this view, for the view to load.
It looks like the virtualization is broken.

The latency is mainly cause when Navigating from the SonarQube view to other views.
I have found that the style we are using break the virtualization (even when forcing the `ItemsPanel` properties to use a `VirtualizedStackPanel`). 
Besides there are a lot of warnings about resources not being found that disappear if get rid of the `TreeViewItemStyle` (it is a style provided by TeamFoundation) but the drawback is that we then lose the VisualStudio look & feel (including the support for VS themes) of the tree view items.

```
System.Windows.ResourceDictionary Warning: 9 : Resource not found; ResourceKey='TreeViewItemBorderStyle'
System.Windows.ResourceDictionary Warning: 9 : Resource not found; ResourceKey='TreeViewItemBorderStyle'
System.Windows.ResourceDictionary Warning: 9 : Resource not found; ResourceKey='TreeViewItemDockPanelStyle'
System.Windows.ResourceDictionary Warning: 9 : Resource not found; ResourceKey='TreeViewItemDockPanelStyle'
System.Windows.ResourceDictionary Warning: 9 : Resource not found; ResourceKey='TreeViewItemContentPresenterStyle'
System.Windows.ResourceDictionary Warning: 9 : Resource not found; ResourceKey='TreeViewItemContentPresenterStyle'
System.Windows.ResourceDictionary Warning: 9 : Resource not found; ResourceKey='TreeViewItemItemsPresenterStyle'
System.Windows.ResourceDictionary Warning: 9 : Resource not found; ResourceKey='TreeViewItemItemsPresenterStyle'
```

Comes from [SVS-121](https://jira.sonarsource.com/browse/SVS-121)

**Comment by duncanp-sonar** [comment]
Fixed by #580
