### ISSUE TITLE
Display hotspot help information

### ISSUE THREAD

**Issue by rita-gorokhod** [SonarSource/sonarlint-visualstudio#1938]
#### Description

Provide the hotspot information, as seen in SQ UI (am I at risk, what is the risk, etc)

TODO:
- [ ] Decide UX layout (new window? new pane in the existing window?)
- [x] Where do we get the documentation from? UPDATE: the hotpsot search API returns the help fields in HTML format.
- [ ] How do we parse it? 

#### SonarQube APIs
The general rule API returns has a single help description for each rule. The help text is actually returned in two formats - HTML and Markdown, in the fields `htmlDesc` and `mdDesc` respectively. 

The hotspot API returns three separate "help"-related fields in HTML formatL `riskDescription`, `vulnerabilityDescription`, `fixRecommendations`. The server contains logic to split the single general HTML rule field into the separate hotspot rule descriptions.

NOTE: the server-side field-splitting logic is not straightforward; it searches for particular sections within the HTML description and rearranges them to build up the three hotspot fields/tabs. See for example rule [2068](https://rules.sonarsource.com/vbnet/type/Security%20Hotspot/RSPEC-2068). The text in the first tab of the SQ UI uses the text from the start of the `htmlDesc` field plus the `Exceptions` text that appears at the end of the field:

![image](https://user-images.githubusercontent.com/10757559/101344472-74686c00-387d-11eb-9887-9c459b8239c5.png)

We shouldn't try to replicate this logic in the client, => we need to use the fields in the hotspots API => we need to handle the data in HTML format.

#### Rendering HTML in the IDE
Options:
(1) Display in a browser control
Pros: simple
Cons: no control of theming; no control of navigation -> user can browse anywhere; heavyweight - embedded browser control does far more than we need.

(2) Translate to XAML
Cons: there isn't an out-of-the-box/production-quality/third-party way to do this
Pros: complete control of rendering

#### htmlDesc field data
Results of investigating the `htmlDesc` data programmatically for all of the rules (all languages and all rule types, not just hotspots) in SonarCloud:
* all of the data is HTML fragments i.e. no single root
* all of the data is valid XML i.e. matching opening and closing tags
* the complete set of HTML tags used in the rules as of December 2020 is as follows:
Heading tags: h1, h2, h3
List tags: ol, ul, li
Text formatting: pre, code, blockquote, strong, em, del
Paragraph formatting: p, br
And anchor: a. This is the only tag that has attributes, and the only attributes used are `href=[target]` and `rel=nofollow`.

**Comment by duncanp-sonar** [comment]
Obsolete. Hotspot help is available in the IDE from [v7.1](https://github.com/SonarSource/sonarlint-visualstudio/releases/tag/v7.1.0.75242).
