### ISSUE TITLE
Bringing IDE to front fails with Win32 error code 1400

### ISSUE THREAD

**Issue by rita-g-sonarsource** [SonarSource/sonarlint-visualstudio#1943]
#### Description

Opening a hotspot using "open in IDE" feature does not bring the IDE to front, and an error is written to the output:
```
GetWindowPlacement call failed. Last error code: 1400
SetForegroundWindow call failed. Last error code: 1400
```

Notes:
- VS 2019
- Solution was already open
- The window was not minimized (but in the background)
- Might be related to remote desktop session
- Error code 1400 = ERROR_INVALID_WINDOW_HANDLE
- The call succeeded in the following try

**Comment by duncanp-sonar** [comment]
Some additional logged output (running in the experimental hive with Ctrl+F5):
```
Bringing IDE to front...
DEBUG: Stored handle: 25954740, Process name: devenv, Current process handle: 1705984, Process id: 1964
DEBUG: GetWindowPlacement call failed. Last error code: 1400
DEBUG: SetForegroundWindow call failed. Last error code: 1400
```

The process handles are different.

**Comment by duncanp-sonar** [comment]
PR #1954 will have fixed one cause, but there may be others. I'll close this for now. We can re-open it if necessary.
