### ISSUE TITLE
[Open in IDE] Browser menu text looks odd if no solution open

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonarlint-visualstudio#1968]
#### Description

Menu label for an  IDE instance that doesn't have an open solution looks odd:

![image](https://user-images.githubusercontent.com/10757559/101165538-bbaced80-362e-11eb-90ce-43a85c67ce22.png)

and

![image](https://user-images.githubusercontent.com/10757559/101165369-75f02500-362e-11eb-821b-012b41854175.png)

cf how SLI handles it:

Project open:
![image](https://user-images.githubusercontent.com/10757559/101166383-198e0500-3630-11eb-95a1-f5003d916092.png)

No project open:
![image](https://user-images.githubusercontent.com/10757559/101166352-0da24300-3630-11eb-934c-501ec34eeb4d.png)

**Comment by jblievremont** [comment]
FYI, I opened https://github.com/SonarSource/sonar-enterprise/pull/3468 to only append the description when it is not empty in the SonarQube UI.
