### ISSUE TITLE
Taint list is not cleared when solution binding changes

### ISSUE THREAD

**Issue by rita-g-sonarsource** [SonarSource/sonarlint-visualstudio#2037]
#### Description

When the solution is closed/changed to standalone, the taint list is not cleared.

TODO:
- [ ] Clear the list when the binding changes.

**Comment by duncanp-sonar** [comment]
The store is cleared, but the taint list isn't. The screen shot below shows the effect of opening and closing a bound solution three times. with an open file that has one issue:

![image](https://user-images.githubusercontent.com/10757559/102910710-e2628500-4472-11eb-9140-23baa7bf047b.png)

The two obsolete entries are shown as non-navigable while the latest entry is navigable.
