### ISSUE TITLE
VS2017连接SonarQube时，报错：The languages supported by plugins on this SonarQube server (C#) do not match any of the solution projects' languages.

### ISSUE THREAD

**Issue by jcchai-0521** [SonarSource/sonarlint-visualstudio#2077]
### Description
VS2017连接SonarQube时，报错：The languages supported by plugins on this SonarQube server (C#) do not match any of the solution projects' languages.

### Repro steps
1. 安装SonarLint.VSIX-4.29.0.25125-2017.vsix插件

2. 连接SonarQube时报错

 3.当前是使用VS2017开发C++代码 

### Expected behavior
能够正常连接SonarQube，且展示配置的质量

### Actual behavior
报错：The languages supported by plugins on this SonarQube server (C#) do not match any of the solution projects' languages.。没有展示SonarQube质量，

### Known workarounds

NA

### Related information

* SonarLint for VS Version：SonarLint.VSIX-4.29.0.25125-2017.vsix
* Visual Studio Version ( v15.9.24)
* SonarQube server version 6.7.1
* Languages in your solution (C++)

**Comment by duncanp-sonar** [comment]
> The languages supported by plugins on this SonarQube server (C#) do not match any of the solution projects' languages

This error message suggests your SonarQube server doesn't have the CFamily plugin installed, which is available in Developer edition and above. Which edition are you using? Has the CFamily plugin been manually removed?
 
The C++ analysis will work in VS in standalone mode even if the CFamily plugin is not installed on the server.

**Comment by jcchai-0521** [comment]
没有使用CFamily plugin，而是使用了SonarOpenCommunity/sonar-cxx开发的插件，通过sonar-scanner扫描是OK的，但是插件就有问题。VS空的解决方案也是一样的报错。

**Comment by duncanp-sonar** [comment]
SonarLint for Visual Studio is not expected to work with the community sonar-cxx plugin, so this behaviour is by design.

If you are having problems scanning using the [sonar-cxx](https://github.com/SonarOpenCommunity/sonar-cxx) plugin then you should contact them for support.

**Comment by jcchai-0521** [comment]
谢谢。
