### ISSUE TITLE
"Show issue viz" item is visible in the Error List context menu for issues without secondary locations

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonarlint-visualstudio#2108]
### Description

The "Show SonarLint Issue Visualization" menu item can be shown in the Error List context menu for issues that do not have secondary locations (and for issues that are not Sonar issues).

Background: the visibility of the Error List content menu item is controlled determined by a UIContext which is set by the `IAnalysisIssueSelectionService`. Previously only CFamily live issues could have secondary locations. Now, the selection service also handles taint issues and hotspots.

The [status checking code](https://github.com/SonarSource/sonarlint-visualstudio/blob/b2fe179c0c95d3685398136a801b8a2a96244687/src/IssueViz/Commands/IssueVisualizationToolWindowCommand.cs#L91) for the Error List context menu command needs to be updated.

### Repro steps

1. Open a bound project that has taint issues
2. Select a taint issue with secondary locations in the taint list
3. Switch to the Error List
4. Right-click on an issue that does not have secondary locations

### Expected behavior

The "Show SonarLint Issue Visualization" menu item is not shown.

### Actual behavior

The context menu item is shown:

![image](https://user-images.githubusercontent.com/10757559/104936525-8ec95580-59a4-11eb-9bb8-6947ad32fd65.png)

### Known workarounds

None

### Related information

* SonarLint for VS Version: Next (unreleased)

**Comment by rita-g-sonarsource** [comment]
Fixed by #2096 and #2125 - right clicking on a row in the error list will select that row, which will trigger the selection service and update the UI context -- so the button will not appear when there are no secondary locations.
