### ISSUE TITLE
Not Reading sonarcloud Ruleset

### ISSUE THREAD

**Issue by sachin-agarwal-by** [SonarSource/sonarlint-visualstudio#2169]
### Not Reading sonarcloud Ruleset

I have sonarcloud where we have all the quality profile defined and I want to load the quality profile from the sonarclloud but its always taking default rule set from https://rules.sonarsource.com/.

### Repro steps

o	First we have  installed SonarLint extension by clicking Extension-> Manage Extension  searching sonar in search box and click on download.

o	Once Extension downloaded , we have restarted the visual studio.
Now right click on solution and click on manage SonarQube connection.

o	A new entry called “SonarQube” will be shown in the Team Explorer window:

o	Click on connect to open the dialog where you can enter your server and your user token:
SonarQube Server : server name
User Name: Employee id
Password: SonarQube login Password 
And click on Connect.

 
o	It will show all the project available in SonarQube repo.
Select project name and right click and click on bind.

### Expected behavior

it should load rule set from server.

### Actual behavior

its loading all the rules from https://rules.sonarsource.com/.

### Related information

* SonarLint for VS Version
* Visual Studio Version (e.g. Professional v15.4.1)
* SonarQube server version
* Languages in your solution (C#, VB.Net, Javascript, C, C++)

**Comment by rita-g-sonarsource** [comment]
@sachin-agarwal-by can you clarify what do you mean by "its loading all the rules from https://rules.sonarsource.com/." ? loading where?
Once you bind the project, a new folder named `.sonarlint` will be added under the solution's root directory. It will contain inside a `ruleset` file that represents the configuration that you have on the server. You can read more about it in our [documentation](https://github.com/SonarSource/sonarlint-visualstudio/wiki/Connected-Mode-configuration-for--C%23-and-Visual-Basic-projects).
Is this not the behavior that you observe? If so, please clarify.

**Comment by sachin-agarwal-by** [comment]
@rita-g-sonarsource as u can see below screenshot when we are getting any sonarQube issue in my project then its referring rule from the  https://rules.sonarsource.com/." location, So I am not sure whether its reading my sonarcloud ruleset or its taking default rule set.

![image](https://user-images.githubusercontent.com/69183793/107667556-af3fb380-6cb5-11eb-9b24-7ca85a13563f.png)

and another questions if I would like to share the same settings to all my team mates then do I need to just checkin the .sonarlint folder is it okay ? or we have to checkin sonarlint.xml which has generated for each project.

**Comment by rita-g-sonarsource** [comment]
@sachin-agarwal-by the link that you see is a documentation link -- rules.sonarsource.com is a our documentation website where you can see the explanation of all SonarSource rules. So it's ok that it's pointing there, it's not supposed to link to your server.

The rules that are enabled in your IDE (such as the S2178 in your screenshot) are determined by the quality profile that is configured on your SonarQube/SonarCloud server. You can read more about it [here](https://docs.sonarqube.org/latest/instance-administration/quality-profiles/).
If you want to be sure that the rules in your IDE match what you have in the server, simply right-click on the on the binding and update it:
![image](https://user-images.githubusercontent.com/60586879/107669412-fd42c000-6c91-11eb-846d-4683733d2710.png)
If you want, you can compare the `.ruleset` file under the `.sonarlint` folder with your server configuration, but you shouldn't need to do so, updating the binding will make sure that your project is synced.

If you want to share the project with your team mates you can commit the `.sonarlint` folder and all of its contents. Note: depending on your solution's configuration, it's possible that additional ruleset files were added. You can read [here](https://github.com/SonarSource/sonarlint-visualstudio/wiki/Connected-Mode-configuration-for--C%23-and-Visual-Basic-projects) about the other files that we might add.

**Comment by sachin-agarwal-by** [comment]
thanks a lot @rita-g-sonarsource  for your quick response and the provided information was really helpful.
So as a conclusion I got that we have to checkin .sonarlint folder, projectfile changes which is referring to sonarlint.xml and rulesets as highlighted below.

<PropertyGroup>
  <CodeAnalysisRuleSet>path-to-generated-ruleset.ruleset</CodeAnalysisRuleSet>
</PropertyGroup>

<ItemGroup>
  <AdditionalFiles Include="..\.sonarlint\{language}\SonarLint.xml" />
</ItemGroup>

**Comment by rita-g-sonarsource** [comment]
@sachin-agarwal-by is that the actual values that you have in your csproj? or just an example? this is the example that we have in our documentation, it's not something you need to copy paste as-is to your project. In fact, you shouldn't need to manually change your csproj -- you can just click on "update" in the binding window and we will change your project files as needed.
And afterwards you can review the changes and commit them. Does that make sense?

**Comment by sachin-agarwal-by** [comment]
yes this was just for example but in my case it was creating entries after binding solution but changes were made in above those files which I have highlighted in above thread.

**Comment by rita-g-sonarsource** [comment]
@sachin-agarwal-by great, you should be set now and the rules that you configured in the server should be applied now 🙂 
Feel free to use our [community forum](https://community.sonarsource.com/) if you have any questions/issues.

**Comment by sachin-agarwal-by** [comment]
can I move this project level changes to Directory.Build.props so that we have to make changes in only one file .
I tried to add below code in Directory.Build.props but in output window I can see all project all unbound..


<Project>
    <PropertyGroup>
        <CodeAnalysisRuleSet>..\solutions\.sonarlint\test.ruleset</CodeAnalysisRuleSet>
    </PropertyGroup>
	
	<ItemGroup>
      <AdditionalFiles Include="..\solutions\.sonarlint\test\CSharp\SonarLint.xml" Link="SonarLint.xml" />
    </ItemGroup>
	
	
</Project>

**Comment by duncanp-sonar** [comment]
@sachin-agarwal-by as Rita said, please use the forum for support questions.

You can use `Directory.Build.props` or any other standard MSBuild mechanism - that's what we do with the code in [this repo](https://github.com/SonarSource/sonarlint-visualstudio/blob/master/Directory.Build.props).
For a project to be considered as bound, it needs to reference the `SonarLint.xml` file and the generated ruleset.
