### ISSUE TITLE
Simplify telemetry collection

### ISSUE THREAD

**Issue by rita-gorokhod** [SonarSource/sonarlint-visualstudio#2178]
#### Description

The current design of telemetry collection requires "manual" bootstrapping whenever a new field is added:
* The field is declared in the payload (TelemetryPayload.cs)
* The field is declared in the storage (TelemetryData.cs)
* If the field is a daily counter, it is reset when a day elapses
* The field's manipulation (toggle / increment / add value) is exposed via a new method

This results in multiple code changes whenever a new field is added, it's time consuming and is prone to error (e.g. there are no checks in place that verify that a daily counter is indeed being reset). 

TODO:
The new design should have an easy way to add a new field:
- [ ] Adding a new field should result in minimal changes
- [ ] Daily counters should automatically be reset when needed
- [ ] Manipulation methods (i.e. flag toggle, counter incrementation) should not be copy-pasted

**Comment by duncanp-sonar** [comment]
Closing as obsolete. Telemetry will probably require a complete re-write once the Data team have decided what information they want.
