### ISSUE TITLE
Display a user friendly message when Taint Vulnerabilities are not available in the given SQ version

### ISSUE THREAD

**Issue by rita-g-sonarsource** [SonarSource/sonarlint-visualstudio#2179]
#### Description

When a solution is connected to SQ versions released prior to 8.6, fetching taint vulnerabilities fails with a message:
```
ERROR: Could not find compatible implementation of 'IGetTaintVulnerabilitiesRequest' for SonarQube 7.9.4.35981.
    [Taint] Failed to synchronize taint vulnerabilities with the connected server: System.InvalidOperationException: Could not find compatible implementation of 'IGetTaintVulnerabilitiesRequest' for SonarQube 7.9.4.35981.
       at SonarQube.Client.Requests.RequestFactory.Create[TRequest](ServerInfo serverInfo)
       at SonarQube.Client.SonarQubeService.<InvokeRequestAsync>d__19`2.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at SonarQube.Client.SonarQubeService.<GetTaintVulnerabilitiesAsync>d__37.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
``` 

The message is expected however it is not clear to the user that this is a "normal" behavior.
TODO:
- [x] Remove the stack trace and display a user-friendly message that the SQ version is not supported
- [x] Link to documentation

Example:
![image](https://user-images.githubusercontent.com/10757559/109328476-61987e80-7851-11eb-84ef-18d586cfa7e0.png)

**Comment by roofg** [comment]
Also confirmed for Version:
ERROR: Could not find compatible implementation of 'IGetTaintVulnerabilitiesRequest' for SonarQube 7.9.1.27448.
Very unexpected error when using a SonarQube LTS version. 
Cheers

**Comment by rita-g-sonarsource** [comment]
@roofg just to clarify: it will appear for any SQ version that is older than 8.6, but it doesn't have any impact on SonarLint or your project. It just means that this feature is not supported in the SQ version that you're using.
