### ISSUE TITLE
Bug initializing taint vulnerabilities

### ISSUE THREAD

**Issue by creamteam-de** [SonarSource/sonarlint-visualstudio#2211]
![TaintVulnerabilities_SonarLint](https://user-images.githubusercontent.com/41690091/109679975-5492cc80-7b7c-11eb-853c-c97d57001063.PNG)
### Description

I had just installed the plugin SonarLint to analyze my .net project and for binding it to my Sonar Server. 
When I tried to connect to my server, it seems that the connection is successful, but the initialization of the taint vulnerabilities fail.

### Repro steps

1. Download SonarLint for VS Version: 4.32.0.27625 in "Manage Extensions".

2. Connect SonarLint to my SonarQube server.

### Expected behavior

Connect with no problems.

### Actual behavior

Error [1] is raised:

[Taint] Initializing taint issues synchronization package...
ERROR: Could not find compatible implementation of 'IGetTaintVulnerabilitiesRequest' for SonarQube 7.9.3.33349.
[Taint] Failed to synchronize taint vulnerabilities with the connected server: System.InvalidOperationException: Could not find compatible implementation of 'IGetTaintVulnerabilitiesRequest' for SonarQube 7.9.3.33349.

### Known workarounds

If I download a stable version of SonarLint as SonarLint.VSIX-4.24.0.20196-2019, everything works perfectly.

### Related information
SonarLint for VS Version: 4.32.0.27625
Visual Studio Version: Microsoft Visual Studio Community 2019 Version 16.8.4
SonarQube server version: 7.9 (July 2019) LT
Languages in your solution: C#

**Comment by rita-g-sonarsource** [comment]
Hi @creamteam-de, it's a duplicate of #2179.
FYI just to clarify: Taint Vulnerabilities is a new feature which requires SQ version 8.6 or higher. For any older SQ version, this message will be shown but it doesn't have any impact on SonarLint or your project. It just means that this feature is not supported in the SQ version that you're using. In the upcoming release it will be better worded..
