### ISSUE TITLE
Analysis failure message is displayed for source control diff files

### ISSUE THREAD

**Issue by rita-gorokhod** [SonarSource/sonarlint-visualstudio#2243]
Steps to reproduce:
1. Open a cpp project that is committed to source control
2. Modify a c/cpp/.h file
3. Open the diff view in VS for the modified file

Expected ==> file is not analyzed, no errors in the output log
Actual ==> error in the output log:
`Unable to retrieve the configuration for file 'C:\Users\Rita\AppData\Local\Temp\TFSTemp\vctmp4216_797377.b6.c3934761.h'. Check the file is part of a project in the current solution.`

**Note**: using a different text role might solve the issue: https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.text.editor.predefinedtextviewroles.analyzable?view=visualstudiosdk-2019

**Comment by georgii-borovinskikh-sonarsource** [comment]
Can't fully repro on both 22 & 19. When 'Compare with Unmodified', only the actual project file gets analyzed. When comparing files between 2 commits, the right one is attempted to be analyzed, but rejected as not having a project root. All of the messages are Debug-only, no user facing errors
