### ISSUE TITLE
Existing issues on JS should not disappear when file is saved with parsing errors

### ISSUE THREAD

**Issue by henryju** [SonarSource/sonarlint-visualstudio#225]
We should try to preserve existing issue locations "at best".

Depend on https://jira.sonarsource.com/browse/SLCORE-141

**Comment by duncanp-sonar** [comment]
TODO: investigate behaviour in CFamily. Does this ticket make sense for C++ now that the analysis is handled separately (i.e. not be daemon)?

**Comment by abbas-sabra-sonarsource** [comment]
investigation result: This ticket no longer makes sense for C++; I couldn't reproduce.
