### ISSUE TITLE
Change EmbeddedVsix to use public released version of SonarJS

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonarlint-visualstudio#2270]
### Description

`EmbeddedVsix.csproj` is currently referring to a pre-release version of the SonarJS plugin that contains a rule metadata file.
The project should be changed to use the official download site once the new version of the SonarJS plugin is released.

**Comment by rita-sonarsource** [comment]
Updated to version 7.4.2.15501, release notes: https://github.com/SonarSource/SonarJS/releases/tag/7.4.2.15501
