### ISSUE TITLE
Show issues in opened files when installing the additional languages

### ISSUE THREAD

**Issue by christophelevis** [SonarSource/sonarlint-visualstudio#229]
When installing the support of additional languages, the files that were previously opened are analyzed, issues are reported in Error list but not highlighted in the code. The files needs to be reopened.
In the case of VS2015, this limitation applies only to the file that is currently displayed, but issues are properly highlighted when switching to the other tabs.
In the case of VS2017, all the files that were previously loaded need to be reopened.

**Comment by duncanp-sonar** [comment]
The concept of "additional languages" (i.e. languages that require an additional download to work) was dropped several years ago when the SonarLint daemon was removed.
