### ISSUE TITLE
SonarLint on offline network

### ISSUE THREAD

**Issue by Eldadc** [SonarSource/sonarlint-visualstudio#2389]
Hi,

Do you support offline network without internet connection.
Is there a way to bring documantion to the IDE ?
My question refer to visual studio and VScode.

Thanks

**Comment by rita-sonarsource** [comment]
Hello @Eldadc,
Please open a feature request in the [community forum](https://community.sonarsource.com/tags/c/suggestions/12/sonarlint) along with more information:
* What kind of support would you expect in offline mode? (connected mode?)
* What kind of documentation do you refer to? (our wiki? rules description?) 

It would help also if you provide more details about your use case. Thank you.

**Comment by Eldadc** [comment]
Yes. The case is offline network where I want to  get rule documetion from
visual studio.

Thanks
