### ISSUE TITLE
Prevent SLVS from making changes to csproj-files

### ISSUE THREAD

**Issue by fredrikcarlbom** [SonarSource/sonarlint-visualstudio#2413]
**Is your feature request related to a problem? Please describe.**
We are trying to configure our solution to have our developers use SLVS and not commiting the ruleset files to source control according to https://github.com/SonarSource/sonarlint-visualstudio/wiki/Choosing-which-C%23-or-VB.NET-rules-to-run-in-Standalone-mode but SonarLint keep make changes to our projects.
Right now we have added the references to the ruleset files within condition that the file exists but sonarlint does not recognize that reference and add its own reference regardless.

**Describe the solution you'd like**
Have a setting that makes sonarlint only download ruleset files and not make any changes to projects.

**Describe alternatives you've considered**
Commiting the ruleset file.

**Additional context**
-

**Comment by duncanp-sonar** [comment]
cc @marco-comi-sonarsource 

@fredrikcarlbom just to clarify what you want to achieve:
* you want all developers working on the solution to use Connected Mode so the rules used are synchronized with the SonarQube server
* checking in the contents of the `.sonarlint` folder is ok, but you don't want there to be any additional project-level files, or any changes to individual project files.

Is that correct?

If so, then you can manually configure your projects to achieve this. As long as the projects reference both the generated `SonarLint.xml` file and ruleset in the `.sonarlint` folder, SonarLint won't attempt to re-add them. See [this wiki page](https://github.com/SonarSource/sonarlint-visualstudio/wiki/Connected-Mode-configuration-for--C%23-and-Visual-Basic-projects) for more information. FYI the SonarLint for VS solution does not have project-level changes - we put the necessary references a `Directory.Build.props` file [here](https://github.com/SonarSource/sonarlint-visualstudio/blob/fb35786d081871d97fcc1cb9e4391cf01328bac5/Directory.Build.props#L3) so we don't have to make changes to each solution.


More generally, our roadmap for this year includes simplifying and improving the whole binding experience, including reducing the number of changes made individual project files. [This comment](https://github.com/SonarSource/sonarlint-visualstudio/issues/1970#issuecomment-740889517) describes the historical rationale for binding to work the way it does at the moment.

**Comment by fredrikcarlbom** [comment]
@duncanp-sonar Thank you for your answer, the wiki-page solved my issue. I had been looking at [Choosing which C# or VB.NET rules to run in Standalone mode](https://github.com/SonarSource/sonarlint-visualstudio/wiki/Choosing-which-C%23-or-VB.NET-rules-to-run-in-Standalone-mode) and didn't get those instructions to work and had not found the wiki-page that you referred.
