### ISSUE TITLE
Replace "linter is undefined" string check with ErrorCode

### ISSUE THREAD

**Issue by rita-sonarsource** [SonarSource/sonarlint-visualstudio#2432]
#### Description

Following #2428, we rely on the parsing error string that eslint-bridge returns as an indication that init-linter needs to be called.
Change the indication to check the parsing error code instead of string once the changes are made on JS's side: https://github.com/SonarSource/SonarJS/issues/2627

**Comment by duncanp-sonar** [comment]
Duplicate ticket created and fixed: #3239
