### ISSUE TITLE
Spelling error in additional languages download dialog

### ISSUE THREAD

**Issue by jamesmcroft** [SonarSource/sonarlint-visualstudio#244]
### Description

Not a huge issue, there is just a spelling mistake in the additional languages download dialog that reads 'Downloading latest version of SonarLint **additionnal** languages'. The error appears to be in the [SonarLintDaemonInstaller.xaml](https://github.com/SonarSource/sonarlint-visualstudio/blob/eef13495f418cd63555100d689d8d3478759d90e/src/Integration.Vsix/SonarLintDaemon/SonarLintDaemonInstaller.xaml) file.

Question around this, should these strings referenced in XAML be resourced?

### Repro steps

Please provide the steps required to reproduce the problem

1. Install SonarLint for the first time to VS 2017
2. Load VS 2017
3. Notice the download for other languages dialog appears with a spelling mistake on the word 'additionnal'.

### Related information

* SonarLint for VS Version - 3.4.0.1732
* Visual Studio Version - 15.2 (26430.15)

**Comment by Evangelink** [comment]
Fixed in #250
