### ISSUE TITLE
Re-visit finding closest tsconfig.json

### ISSUE THREAD

**Issue by rita-gorokhod** [SonarSource/sonarlint-visualstudio#2446]
#### Description

At the moment, we pick the first `tsconfig.json` that contains the analyzed file. This logic might be incorrect if there are multiple tsconfigs in the project that reference the file.

Update: the newer versions of the JS/TS analyzer have changed how `tsconfig.json` files are located/used. Check if this ticket is still necessary.

TODO:
- [ ] Revisit the algorithm for finding the correct tsconfig -- should we check the closest tsconfig first?

**Comment by duncanp-sonar** [comment]
Obsolete. The JS/TS analyzer is/has changed how it handles .tsconfig files.
