### ISSUE TITLE
Visual Studio crash when activating SonarLint JS/C++ support

### ISSUE THREAD

**Issue by valhristov** [SonarSource/sonarlint-visualstudio#245]
### Description

Visual Studio crash when quickly activate, deactivate and then activate again SonarLint JavaScript/C++ support.

### Repro steps

Open Visual Studio, in Settings dialog, choose Sonar Lint section. Click Deactivate, wait 1 sec, click Activate, wait 1sec, click Deactivate.

### Expected behavior

Visual Studio does not crash.

### Related information

* SonarLint for VS 3.4
* Visual Studio 2017 15.2

**Comment by Evangelink** [comment]
Duplicates #231
