### ISSUE TITLE
Support //NOSONAR

### ISSUE THREAD

**Issue by rita-gorokhod** [SonarSource/sonarlint-visualstudio#2462]
#### Description

[NOSONAR](https://docs.sonarqube.org/latest/faq/) provides a way for the user to suppress issues in the IDE before they're raised on SQ/SC. It is not currently supported in SLVS and it's a functionality gap, as it is supported in other SL flavors. See [community request](https://community.sonarsource.com/t/suppress-issue-in-c-source-file/43154/14). 

TODO:
- [ ] Support //NOSONAR for C/C++/JS/TS languages.

**Comment by Mike4Online** [comment]
Please open a new issue to track a related request: to be able to suppress individual Sonar warnings in a C family source file.  Something like // NOSONAR(cpp:S106).  Some considerations include whether the suppression lasts only for the immediate statement which follows, or whether it remains in effect for the remainder of that source file.  If the latter case, a corresponding comment form that could re-enable the warning would be helpful.

**Comment by abbas-sabra-sonarsource** [comment]
@rita-sonarsource usually nosonar is supported on the analyzer side. In CFamily we don't believe it is the right approach fo issue suppression so we don't support it(even for CLion and VS Code). After the last discussion with @marco-comi-sonarsource there is a plan to support proper issue suppression at some point. So i would suggest remocing c&c++ from this ticket.
