### ISSUE TITLE
Category of JavaScript/C/C++ issues is always Code Smell

### ISSUE THREAD

**Issue by christophelevis** [SonarSource/sonarlint-visualstudio#249]
In the Error List, in the category column, bugs reported by the SonarLint daemon on JS/C/C++ code are always described as code smells.

**Comment by Evangelink** [comment]
The code on SonarLint for Visual Studio is fine, there is a problem on the daemon side (ticket in [JIRA](https://github.com/SonarSource/sonarlint-visualstudio/issues/249)).
