### ISSUE TITLE
Add support for Visual Studio 2022

### ISSUE THREAD

**Issue by pontusdacke** [SonarSource/sonarlint-visualstudio#2511]
**Description**

It would be great if we had support for SonarLint in the previews of Visual Studio 2022. 
Is it possible before the actual release?

**Comment by catalin-ifacts** [comment]
I am also interested in this one. I don't want to install VS2019 just to check this extension :P

**Comment by Rabosa616** [comment]
Any news?

**Comment by bit7** [comment]
Do it to it.

**Comment by duncanp-sonar** [comment]
FYI v5.0 preview has been published to the VS Marketplace [here](https://marketplace.visualstudio.com/items?itemName=SonarSource.SonarLintforVisualStudio2022). It's installable in any of the VS2022 Release Candidates.

**Comment by catalin-ifacts** [comment]
Hi :) I have just installed it, but it doesn't seem to do anything. 
I have multiple extensions, maybe they interfere with each other?
I couldn't find any video showing how to use Solar Lint in Visual Studio :)

**Comment by rejinkumar** [comment]
I installed sonarlint for VS2022 and it seems to be not working.

**Comment by marco-comi-sonarsource** [comment]
Hello @catalin-ifacts and @rejinkumar, thanks for your reportings.

> Hi :) I have just installed it, but it doesn't seem to do anything.
Once SonarLint is installed, you don't have anything else to do (you can see [our docs](https://github.com/SonarSource/sonarlint-visualstudio/wiki#how-it-works) for more details).
Have you tried to open a C# source file and introduce a "simple" issue like adding an unused variable? In this case SonarLint should report the issue in the code editor as soon as you introduce it and also show it in the IDE "Errors" list.
We're working to make SonarLint user experience better, so if you found SonarLint is not intuitive to get started with, we'd be really thankful if you can share a little more about your expectations, and specifically what would you think SonarLint should do just after installation ;-)

> I installed sonarlint for VS2022 and it seems to be not working.
May I suggest to also try adding a simple issue and check whether SonarLint reports it? If it is not reported, I suggest to take a look at SonarLint logs (in Visual Studio output tab, select "SonarLint" in "Show output from:"). You can open a thread in our community forum to get help: https://community.sonarsource.com/c/help/sl/11

**Comment by duncanp-sonar** [comment]
@marco-comi-sonarsource the work associated with this ticket is done - we won't associate any other PRs with it.
If there is a problem with the released package then we'll treat it as a separate bug i.e. a separate ticket.
