### ISSUE TITLE
[Release pipeline] Automate creating a PR to notify Marketing of the new version

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonarlint-visualstudio#2515]
### Description

Part of the SLVS release process is to manually create a PR for the SonarLint website to notify Marketing that a new version of SLVS has been released (although we don't always remember).

We should automate creating the PR.

Ideally, we would also automate the "notify Marketing" step, either by automating the sending of an email, or agree with Marketing that adding someone as a reviewer to the PR is an acceptable alternative.

**Comment by rita-sonarsource** [comment]
No longer needed
