### ISSUE TITLE
VS2019 needs to be shutdown hardly after clicking on SonarLint links in tool windows or tool tips

### ISSUE THREAD

**Issue by MartinL0815** [SonarSource/sonarlint-visualstudio#2578]
### Description

After installing the extension in VS2019 I opened the SonarLint Windows and clicked onto the "link" inside one of the windows.
In the same moment VS2019 became unusable and clicking into the UI of VS2019 let popup the gold old modal dialog about switching to the program manager (ProgMan) or to wait longer. Only cancelling was disabled:

> ![program manager](https://user-images.githubusercontent.com/525700/130124585-48b88163-a362-4910-81a1-06224314085a.png)

After ending the process I restarted VS2019 and opened a source file.
Okay, I expected to find some issues, hovered the mouse pointer over the issue and was able to click onto the rule.
After clicking onto the rule the same happend … VS2019 became unusable:

> ![click on rule in tool tip](https://user-images.githubusercontent.com/525700/130124970-2a372ca9-a44c-4211-b567-300f71947a4d.png)

#### Reproducing using a SonarLint tool window:

1. Open the SonarLint windows containing only a "link"
2. Click onto the link to open it

#### Reproducing using an issue tool tip

1. Hover the mouse pointer over an issue
2. Move the mouse to be onto the "tool tip"
3. Click onto the rule identifier, which seems to be clickable, since the mouse pointer changes to the "hand"

### Expected behavior

I expected to see a web browser to be opened and a SonarLint or a rule definition web page to be loaded.

### Actual behavior

Visual Studio 2019 blocks any user interactions. Clicking into the VS2019 UI causes the dialog …

> ![ProgMan Dialog](https://user-images.githubusercontent.com/525700/130125534-775c84f7-4051-4005-9a76-2365e81ab4e7.png)

… opens. The first two buttons are enabled, but clicking onto those buttons doesn't seem to have an impact. The last, right button "Cancel Operation" is disabled.

### Known workarounds

Workaround? No way.

### Related information

* SonarLint for VS 4.37.0.34839
* Visual Studio Professional 2019, Version 16.9.3
* Languages in your solution : C++ and C

**Comment by duncanp-sonar** [comment]
Thanks for the error report @MartinL0815.

I can't repro this locally; all of the SL links work correctly for me.

Does the issue repro for you with any non-SL links? e.g.

![image](https://user-images.githubusercontent.com/10757559/130214151-f158d674-626e-4160-956d-490ade5a2dd4.png)

**Comment by MartinL0815** [comment]
Hi @duncanp-sonar,

Thanks for your quick response!

Until I had the allowance to update to the latest VS2019 version 16.11.1 I had problems with every link in every "tool tip"/popup and tool window.

But … to be honest … the update procedure asked me to end all devenv processes, while I had no VS2019 visually open and I killed two devenv processes to enable the setup to continue, so what ever went wrong, I think SonarLint was not the reason!

So I close the issue from my own.

All the best!

**Comment by duncanp-sonar** [comment]
No problem - thanks for the update @MartinL0815.
