### ISSUE TITLE
The rule cpp:SingleDeclarationPerStatement is not hit IMHO

### ISSUE THREAD

**Issue by MartinL0815** [SonarSource/sonarlint-visualstudio#2580]
Hi,

Here the screenshot of the situation, with the warning about the harmed rule cpp::SingleDeclarationInStatement:

> ![SingleDelcarationInStatement?](https://user-images.githubusercontent.com/525700/130239599-dee44e6a-66c4-4f93-8699-088d6b7eec02.png)

Since the related line only declares one class attribute, I wouldn't have had expected a warning!

Thanks in advance!

**Comment by magminor** [comment]
Hi,
I have the same problem with
	map<ViChannelTupel, string, TupleCompare> channelToDescriptor;
There is only one declaration but ther is a SingleDeclarationInStatement warning

what can be done to suppress this ?

thanks.
