### ISSUE TITLE
rule "cpp:S1854: Value stored to '…' is never read" failes

### ISSUE THREAD

**Issue by MartinL0815** [SonarSource/sonarlint-visualstudio#2583]
Hi,

I observed that the rule cpp:S1854 fails certainly.

Here an example:

> ![Value stored in '…' IS used](https://user-images.githubusercontent.com/525700/130453263-b0c936f9-14fb-4486-9f4b-6313cb9afae3.png)

So, the three local variables are not only set, but used in a method call inside the MFC "VERIFY" macro.

**Comment by duncanp-sonar** [comment]
@MartinL0815  Could you report issues with rules to the [community forum](https://community.sonarsource.com/c/bug/5) please? There is a section for reporting faults and a specific sub-section for reporting false positives. 

FYI the CFamily rules are developed by a separate team and they don't monitor the SonarLint repos for issues. However, all development teams at SonarSource monitor the community forum.

Thanks.

**Comment by duncanp-sonar** [comment]
@abbas-sabra-sonarsource FYI reported FP on cpp:S1584
