### ISSUE TITLE
Implement workpace / project hashing function for VS2017

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonarlint-visualstudio#2632]
### Description

VS2017 and VS2019 both support the macros `${workspaceHash}` and `{projectHash}`. However, the hash algorithms are different.

TODO
- [ ] implement the VS2017 hash algorithm
- [ ] modify the macro evaluator to select the correct algorithm based on the VS version.

**Comment by bigfluffycookie** [comment]
VS2017 is no longer supported.
