### ISSUE TITLE
Don't sign PR builds

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonarlint-visualstudio#2652]
### Description

PRs by definition contain unreviewed/unverified code. We don't want assemblies or the VSIXes produced by PR builds to be signed, as then they are indistinguishable from "real"/"official" release builds.

**Comment by rita-sonarsource** [comment]
Added 2 new build variables: 
SignVsixIfMasterBranch = default true, will sign a vsix built on master branch. Used to override signing on master.
ForceSignVsix = default false, will force signing a vsix on any branch. Used to override signing on PRs.
