### ISSUE TITLE
Project is marked as exclude from analysis but still reports S125 for commented out code

### ISSUE THREAD

**Issue by StingyJack** [SonarSource/sonarlint-visualstudio#2659]
I marked a project as exclude from sonar lint. Its just a little scratch/test project that I dont need to see warnings or any squigglies for that matter. Here you can see the project is marked to be excluded but the Program.cs still is getting S125 reported. 
![image](https://user-images.githubusercontent.com/15381181/134407564-e6116c12-e25f-4785-9c96-cfca9b299f6c.png)

Repro should be to have sonarlint installed and enabled, create a console app, and comment out the `Console.WriteLine("hello world")`.  SonarLint should warn about it being a commented statement. Then right click on the project and choose the sonar lint -> Exclude from Analysis option or add the project property to the proj file. Save then rebuild the project. 

I would expect to not see any sonar related warnings or errors at that point, but they remain

VS 2019  16.11.1
SonarLint 4.38.0.36876

**Comment by duncanp-sonar** [comment]
@StingyJack thanks for reporting the issue. FYI it's covered by #1337.

**Comment by StingyJack** [comment]
@duncanp-sonar - dat issue number 

I could swear that this worked before for sonarlint and VS

**Comment by duncanp-sonar** [comment]
@StingyJack the property will exclude the project from being bound in Connected Mode. However, that just means that it won't have a specific ruleset applied to it, so the default set of SonarC#/VB.NET rules will run.

**Comment by StingyJack** [comment]
@duncanp-sonar  - there are a few things going on here.  I checked in another solution and added `Console.Writeline($"should be a sonar error");` to one of the unit tests and commented it out and sonar is not reporting an S125 for it.  This was before binding the solution to SonarCloud.  After binding it, it still does not report an S125 for it, but this is because binding the solution to Sonar did not bind the unit test projects - this is a new behavior and one that is a defect in its own right and needs to be addressed. All projects should be bound when the solution is bound. Test projects need to have clean code too. 

In the case I reported above, I had explicitly chosen to exclude a project from analysis using the context menu for the project item in the solution explorer. Yet sonarlint was still reporting sonar errors in that project. Thats a different defect that also needs to be addressed.

**Comment by duncanp-sonar** [comment]
@StingyJack 

> this is because binding the solution to Sonar did not bind the unit test projects - this is a new behavior and one that is a defect in its own right and needs to be addressed

Yes, that's a separate bug - see #632.

More generally, there are a lot of individual things wrong with Connected Mode, summarised in #1336. Overhauling Connected Mode is on the roadmap for Q4 this year, although I suspect it will slip into Q1 next year.

**Comment by StingyJack** [comment]
@duncanp-sonar  Does issue 1336 pertain to other things that build projects, like AzDo pipelines running a VS Build task?    Having those only ever use sonarway QP means inaccurate warnings/errors on every build.

**Comment by duncanp-sonar** [comment]
@StingyJack no. Issues in this repo relate to SLVS only.

In general, it's best to create a thread in the appropriate section of the [community forum](https://community.sonarsource.com/) for a support query, bug report or feature request. It will be seen by more SonarSourcers, as well as being more visible to other users. The appropriate team will create implementation tickets as necessary (some teams use GitHub Issues, most currently use Jira).

FWIW we use the SonarCloud AzDo build task in the SLVS build pipeline, and it looks like it's correctly using the custom C# Quality Profile assigned to the project in the SonarCloud UI.
