### ISSUE TITLE
[Cloud Secrets] Add documentation

### ISSUE THREAD

**Issue by rita-sonarsource** [SonarSource/sonarlint-visualstudio#2673]
### Description

- [x] How to enable/disable rules
- [x] Behavior in standalone/connected mode
- [x] Suppressions

**Comment by duncanp-sonar** [comment]
Edited:
* https://github.com/SonarSource/sonarlint-visualstudio/wiki
* https://github.com/SonarSource/sonarlint-visualstudio/wiki/Secrets-detection-rules
* https://github.com/SonarSource/sonarlint-visualstudio/wiki/Choosing-which-C,-Cpp,-JavaScript,-TypeScript-or-Secrets-detection-rules-to-run-in-Standalone-mode
