### ISSUE TITLE
Support not running secrets analysis on .gitignore-d files

### ISSUE THREAD

**Issue by rita-gorokhod** [SonarSource/sonarlint-visualstudio#2678]
### Description

In other SLVS flavors, the rules are run on text files, unless they are explicitly excluded by being in the .gitignore file i.e. if a project is not under source control then issues will be reported.

This behaviour is nice-to-have; if we can do it easily, great, otherwise it is ok only to run secrets rules for for files we know are under source control.

**Comment by duncanp-sonar** [comment]
Notes:

#### EnvDTE.SourceControl::IsItemUnderSCC(filePath)
Pros:
* public VS interface, VS2015+
* should work for multiple source control systems

Cons:
* limited: doesn't differentiate between (1) ignored files and (2) new files that have been created but not staged or committed:

```
XXX File: D:\proto\SLVS\SCCDetection\SampleApp\.gitignore
	underSCC: True, 	checkedOut: False

XXX File: D:\proto\SLVS\SCCDetection\SampleApp\SampleApp.csproj
	underSCC: True, 	checkedOut: False

XXX File: D:\proto\SLVS\SCCDetection\SampleApp\Program.cs
	underSCC: True, 	checkedOut: False

XXX File: D:\proto\SLVS\SCCDetection\SampleApp\IgnoredFile.txt
	underSCC: False, 	checkedOut: False

XXX File: D:\proto\SLVS\SCCDetection\SampleApp\ExistingFile_Committed.txt
	underSCC: True, 	checkedOut: False

XXX File: D:\proto\SLVS\SCCDetection\SampleApp\ExistingFile_ModifiedLocally.txt
	underSCC: True, 	checkedOut: True

XXX File: D:\proto\SLVS\SCCDetection\SampleApp\NewFile_AddedButNotCommitted.txt
	underSCC: False, 	checkedOut: False

XXX File: D:\proto\SLVS\SCCDetection\SampleApp\NewFile_StagedButNotCommitted.txt
	underSCC: True, 	checkedOut: True

XXX File: D:\proto\SLVS\SCCDetection\SampleApp\MISSING_FILE.txt
	underSCC: True, 	checkedOut: False

```


#### LibGit2Sharp
NuGet: https://www.nuget.org/packages/LibGit2Sharp/0.27.0-preview-0119

Cons:
* Git-only
* public NuGet package is v0.26.2
* adds approx 6MB to the VSIX (less if we exclude the Mac/Unix libraries, but that would be more complicated)

Pros: 
* correctly detects whether files are ignored or not
* widely used (4.5 million downloads)
* VS ships with a privately-built version
* ?used in the GitHub extension for VS?

```
var startPath = ...
var repoPath = Repository.Discover(startPath);

using (var repo = new Repository(repoPath))
{
    // NOTE: needs a relative file path with Unix directory separators
    var isIgnored = repo.Ignore.IsPathIgnored(file);
    Debug.WriteLine($"YYY IsIgnored: {isIgnored}, file: {file}");
}
```
