### ISSUE TITLE
Investigate how to suppress an issue

### ISSUE THREAD

**Issue by Evangelink** [SonarSource/sonarlint-visualstudio#268]
In order to be able to don't show issues marked as FP or won't fix on SonarQube we will need a way to suppress the issue or prevent the issue to be raised.

The main options we are considering are:
1/ Static Dependency Injection (SonarLint will dynamically injects a behavior onto the analyzer to allow or not to raise an issue)

2/ Through some post-processing API (Roslyn? Error List?...)

Sub-task of #267

**Comment by duncanp-sonar** [comment]
Notes:

**Option 1**:
Tested, and works for our analysers.
Pros: simple, low-risk
Cons:
- only works with our analysers, which will all need to be modified to report diagnostics through a new method on the base context.
- issues won't immediately be removed from error list if the list of suppressed issues changes. This is ok for the first version of the feature.

**Option 2:**
- @Evangelink found this feature request for Roslyn, which suggests there is not currently a supported way to filter the issues: [#20242](https://github.com/dotnet/roslyn/issues/20242)

- Error list: Roslyn provides an _ITableDataSource_ implementation to connect the error list to the live solution crawler [here](http://source.roslyn.io/#Microsoft.VisualStudio.LanguageServices/Implementation/TableDataSource/AbstractTableDataSource.cs,abe5d488a562c504,references). However, the implementing types are all _internal_ and it doesn't look as if we can wrap it. MSDN docs on the table manager interfaces are [here](https://msdn.microsoft.com/en-us/library/microsoft.visualstudio.shell.tablemanager.aspx)

- Error list filtering: e.g. by adding a new MEF filter
_[Export(typeof(IErrorListFilterHandler))] // from Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\ErrorList\Microsoft.VisualStudio.ErrorListPkg.dll_

This adds a new filter to the main error list filter combo. It might be useful in other circumstances, but it's not suitable here. The filter can be turned on and off by the user, and although the errors are removed from the error list the squigglies still appear in the editor.
