### ISSUE TITLE
Implements an issue matching mechanism

### ISSUE THREAD

**Issue by Evangelink** [SonarSource/sonarlint-visualstudio#269]
We need to implement an issue matching mechanism that will allow us to be able to match an issue reported by the analyzer and the one suppressed on SonarQube side.

Sub-task of #267

**Comment by duncanp-sonar** [comment]
Matching implementation in IntelliJ is [here](https://github.com/SonarSource/sonarlint-intellij/blob/master/src/main/java/org/sonarlint/intellij/issue/tracking/Tracker.java).
