### ISSUE TITLE
Investigate performance issues during normal execution

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonarlint-visualstudio#2770]
### Description

Users have reported slowness during execution that appears to be caused by SonarLint.

See:
* https://community.sonarsource.com/t/sonarlint-freezes-visual-studio-2022-after-solution-is-loaded/53123
* https://marketplace.visualstudio.com/items?itemName=SonarSource.SonarLintforVisualStudio2022&ssr=false#review-details

Related ticket: #2769

TODO:
- [ ] repro the issue
- [ ] inventory the non-startup operations performed by SLVS and check which thread they are being executed on
- [ ] check whether operations on UI threads can be moved to non-UI threads.

**Comment by Bosch-Eli-Black** [comment]
We've recently been evaluating having everyone on our team install the SonarLint VS extension, and we're running into the same issue: Installing the extension seems to slow down Visual Studio and/or cause it to freeze for a few seconds.

When you investigate this ticket, can you also investigate if the SonarLint extension is slowing down _unloading_ projects (and closing solutions), too? I seem to remember that it felt like that was affected as well 🙂

Also, I'd like to extend an offer to send you logs, if it'd be helpful. Not sure if there's a way to profile where are slowdowns are happening, but if there is, let me know 🙂

**Comment by duncanp-sonar** [comment]
Hi @Bosch-Eli-Black. Thanks for the offer of help. The logging we have currently isn't really geared towards diagnosing perf issues, unfortunately; it's mainly aimed at helping understand functional defects. However, we recently started adding [ETW](https://docs.microsoft.com/en-us/windows/win32/etw/about-event-tracing) tracing to a few modules specifically to help diagnose performance issues, and we'll continue to add more. At that point it would be very useful to have logs from your machines (although there are some issues we'd have to work through as ETW logs get very big very quickly!).

In the short term it would be useful if you could give use some more information about your environment and scenarios:
* which version(s) of VS are you using?
* which language(s)?
* if you are analysing C#/VB.NET, do you have VS configured (a) to analyse the entire solution and (b) is the analysis running in or out of process? The settings are in `Tools`, `Options`, `Text Editor`, `C#`, `Advanced`:

![image](https://user-images.githubusercontent.com/10757559/163235613-a1e8ab95-137d-429e-9ba4-8ff40d26a804.png)

* are you using Connected Mode?
* are you using any other third-party extensions?
* are you seeing gold bars (i.e. VS saying "it looks like SonarLint is causing a slow down", or is it a general impression of slowness?
* are there any specific operations that are noticeably affected? (I see you mentioned unloading/shutting down above).

If you are seeing gold bars, it would be useful to know if they can be triggered repeatedly (a gold bar is often due to some specific issue with a feature e.g. Connected Mode doing something on the UI thread that should be done in the background, so we would open a separate issue for each one we could reproduce).

Thanks!

**Comment by Bosch-Eli-Black** [comment]
Hi @duncanp-sonar,

Cool, thanks! 🙂

- Our solution has 73 projects: 72 C# projects and 1 JavaScript project.
- We're using VS2022, both the latest stable version and the latest preview version
- We have a _lot_ of stuff in `node_modules`.
- We also have `.jsx`, `.xml`, `.css`, `.json`, `.csproj`, `.xsd` filetypes in the projects, as well as an `.editorconfig` for the entire solution.
- We have "Run background code analysis" set to "Entire solution" and we have "Run code analysis in separate process" enabled.
- We're not using Connected Mode
- Other third-party extensions: NPM Task Runner and CodeMaid VS2022. (We mostly use CodeMaid to format files on save)
- We're not seeing gold bars – just everything feels slower.
- Unloading projects seemed to be affected. I seem to remember that the editor would also sometimes hang while typing. I'll have to reenable the SonarLint extension and see if I can get a more complete list 🙂

FYI, I'm getting ready to go on vacation. Will return around May 9th, God willing 🙂
