### ISSUE TITLE
Include local time in telemetry data

### ISSUE THREAD

**Issue by christophelevis** [SonarSource/sonarlint-visualstudio#288]
Telemetry data should include local date and time. 
The parameter is: `system_time`.
The value should be expressed in local time, using the ISO 8601 format, with milliseconds and with the time zone offset.

For example:
```
"system_time": "2017-09-26T16:53:02.592+02:00"
```

**Comment by valhristov** [comment]
@christophelevis is the time format [ISO8601](https://en.wikipedia.org/wiki/ISO_8601#UTC)?
