### ISSUE TITLE
Embed SonarC# 8.36

### ISSUE THREAD

**Issue by costin-zaharia-sonarsource** [SonarSource/sonarlint-visualstudio#2881]
Release notes: https://github.com/SonarSource/sonar-dotnet/releases/tag/8.36.0.43782

**Comment by pavel-mikula-sonarsource** [comment]
8.36 Has packaging issue with VB.NET, we didn't ship SonarAnalyzer.CFG.dll dependency.

**Comment by pavel-mikula-sonarsource** [comment]
Related issue: https://github.com/SonarSource/sonar-dotnet/issues/5436

**Comment by pavel-mikula-sonarsource** [comment]
Edit: C# is fine and can be updated. I've updated the title.

**Comment by pavel-mikula-sonarsource** [comment]
Superseded by #2904
