### ISSUE TITLE
Embed SonarC# 8.36.1 and SonarVB 8.36.1

### ISSUE THREAD

**Issue by pavel-mikula-sonarsource** [SonarSource/sonarlint-visualstudio#2904]
Release notes:
https://github.com/SonarSource/sonar-dotnet/releases/tag/8.36.1.44192
This version changes the packaging of the VB.NET analyzer - `SonarAnalyzer.CFG.dll` dependency was added.

8.36:
Release notes: https://github.com/SonarSource/sonar-dotnet/releases/tag/8.36.0.43782
Summary: Improved performance and rule S2222 tracks more APIs - not in SonarWay yet.

**Comment by duncanp-sonar** [comment]
Superceded by https://github.com/SonarSource/sonarlint-visualstudio/issues/2961
