### ISSUE TITLE
Bug: Suppressions are being fetched on the UI thread

### ISSUE THREAD

**Issue by rita-sonarsource** [SonarSource/sonarlint-visualstudio#2932]
### Description

When `SonarLintIntegrationPackage` loads, it calls `ISuppressedIssuesFileSynchronizer.UpdateFileStorage`. The call is being made on the UI thread and `UpdateFileStorage` is a blocking call.

TODO:
- [x] Make `UpdateFileStorage` a non-blocking call

**Comment by duncanp-sonar** [comment]
The code coverage is low because I can't work out how to test an exception handler - see the comment inline.
