### ISSUE TITLE
S1172 in private methods

### ISSUE THREAD

**Issue by amoroso81** [SonarSource/sonarlint-visualstudio#2984]
Sonarlint for Visual Studio keeps noticing this situation for C#: parameters defined for private methods are marked as unused even if they are used.

![image](https://user-images.githubusercontent.com/18445300/164005547-a409999f-1c9c-4c02-bb24-9f295a6700d9.png)

Can you verify the problem? This is quite annoying. Thanks in advance.

**Comment by duncanp-sonar** [comment]
> Please use the community forum instead of creating issues in this repo.
The community forum already has answers to many common questions/problems and is actively monitored by many SonarSourcers.
> (click on the "Preview" tab above to make the links below clickable)
> * for support or to report a bug visit https://community.sonarsource.com/c/help/sl/11
> * to report a false positive visit https://community.sonarsource.com/c/bug/fp/7
> * to suggest new features visit https://community.sonarsource.com/c/suggestions/features/14
> Thank you.

You might also want to check the [issues](https://github.com/SonarSource/sonar-dotnet/issues?q=is%3Aissue+is%3Aopen+S1172) in the SonarC# repository to see if the issue has already been reported.
