### ISSUE TITLE
Authentication should be mandatory to use the connected mode

### ISSUE THREAD

**Issue by christophelevis** [SonarSource/sonarlint-visualstudio#310]
It's currently possible to use the connected mode without being authenticated if the SonarQube server is configured to allow anonymous access.
But the connected mode is supporting more and more features, and allowing both anonymous and authenticated access can lead to some error-prone and unexpected behaviors.

It should now be mandatory for a user to provide credentials (user/password or token) when creating or editing a connection to a SonarQube server. A server connection that would have been previously specified without any credentials will continue to work.

**Comment by duncanp-sonar** [comment]
cf recent discussion in the other SonarLint IDEs about allowing anonymous access
[SLVSCODE-112](https://jira.sonarsource.com/browse/SLVSCODE-112)

The current consensus is that there are scenarios in which anonymous access is useful e.g. enterprises using SQ where not every developer has an SQ account.
