### ISSUE TITLE
[Binding] Unbound project check does not detect if js/ts settings are missing

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonarlint-visualstudio#3127]
### Description

The "is the binding up to date check" should detect missing settings files warn the user that an update is required.
However, it doesn't warn about missing js/ts rules files.

### Repro steps
1. Bind a solution containing JS or TS files
2. Close the solution
3. Delete the js/ts/both settings files from the `.sonarlint` folder
4. Reopen the solution

### Expected behaviour
The Error List should show a gold bar warning that a binding update is required.

### Actual behaviour
No gold bar.

### Notes
The js/ts analysis still works i.e. no errors. There are messages in the Output Window saying that the settings file could not be found and that default settings are being used.

Updating the binding does re-add the missing files.

**Comment by ugras-ergun-sonarsource** [comment]
A similar issue has been found for CMake projects (#3253). Fixing this issue will need a substantial effort since nobody really has raised issues about Cmake shows that this will be a low-impact task with high effort. For these reasons we have decided not to fix the issue for now.

**Comment by duncanp-sonar** [comment]
Closing as redundant. Following the change to "unintrusive" Connected Mode settings storage in v7.0, all supported QPs will be fetched.
