### ISSUE TITLE
Send keep-alive to the eslint-bridge process

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonarlint-visualstudio#3185]
### Description

Send a keep-alive every five seconds to the eslint-bridge process to prevent it from terminating.
We start separate eslint-bridge instances for JavaScript and TypeScript, so this need to be done for both.

Depends on [SonarJS-#3131](https://github.com/SonarSource/SonarJS/issues/3131). The implementation details are in the ticket.

Note: this ticket is dependent on the current JS/TS sprint finishing and releasing v9.7 i.e. [this milestone](https://github.com/SonarSource/SonarJS/milestone/59).

**Comment by victor-diez-sonarsource** [comment]
Hello @duncanp-sonar,

we will reuse the existing endpoint `/status`, instead of creating a new one just for the heartbeat, given that any request to any endpoint will reset the timeout.
