### ISSUE TITLE
VS2019: Cannot connect SonarLint to SonarQube in 6.7.0.52071

### ISSUE THREAD

**Issue by pde-cds** [SonarSource/sonarlint-visualstudio#3219]
With the latest version 6.7.0.52071 i cannot connect to SonarQube (8.9.9 LTS)
Output of SonarLint only shows "SonarQube request failed: Illegal characters in path."

Version 6.6.0.49766 of SonarLint works fine.

How can i resolve this issue with the latest version?

**Comment by FeydCron** [comment]
I have the same problem. First I thought it has something to do with my recently updated VS2019 to 16.11.18 but since I cannot say when the SonarLint extension update happened it could also be related to the new version of the SonarLint extension. The SonarQube I want to connect to is also Version 8.9.9 (build 56886)

**Comment by FeydCron** [comment]
> I have the same problem. First I thought it has something to do with my recently updated VS2019 to 16.11.18 but since I cannot say when the SonarLint extension update happened it could also be related to the new version of the SonarLint extension. The SonarQube I want to connect to is also Version 8.9.9 (build 56886)
> 
> Is there any way to roll back to the previous version of the SonarLint extension? It would also help to figure out whether the connect failure is related to the latest version.

Yes, it definitely is an issue with version 6.7.0.52071 of the SonarLint extension. My workaround was now:

1. Uninstall the SonarLint extension from VS2019
2. Download version 6.6 of the SonarLint extension (as vsix file) from the related GitHub site: https://github.com/SonarSource/sonarlint-visualstudio/releases/tag/v6.6.0.49766
3. Install version 6.6 of the vsix file
4. Turn off automatic update of the extension in VS2019

**Comment by pde-cds** [comment]
I narrowed the issue down to SonarLint.VisualStudio.IssueVisualization.Editor.LanguageDetection.SonarLanguageRecognizer.GetNormalizedExtension(string fileName)
![image](https://user-images.githubusercontent.com/61505382/187655320-f6776e90-9f88-48b4-9db7-7134285c34c5.png)

Stacktrace
> SonarLint.VisualStudio.Infrastructure.VS.dll!SonarLint.VisualStudio.IssueVisualization.Editor.LanguageDetection.SonarLanguageRecognizer.GetNormalizedExtention(string fileName) Line 147
	at D:\git\sonarlint-visualstudio\src\Infrastructure.VS\LanguageDetection\SonarLanguageRecognizer.cs(147)
SonarLint.VisualStudio.Infrastructure.VS.dll!SonarLint.VisualStudio.IssueVisualization.Editor.LanguageDetection.SonarLanguageRecognizer.GetAnalysisLanguageFromExtension(string fileName) Line 125
	at D:\git\sonarlint-visualstudio\src\Infrastructure.VS\LanguageDetection\SonarLanguageRecognizer.cs(125)
SonarLint.VisualStudio.Integration.dll!SonarLint.VisualStudio.Integration.Binding.JsTsProjectTypeIndicator.IsFileJsTs(string fileName) Line 83
	at D:\git\sonarlint-visualstudio\src\Integration\Binding\JsTsProjectTypeIndicator.cs(83)
SonarLint.VisualStudio.Integration.dll!SonarLint.VisualStudio.Integration.Binding.JsTsProjectTypeIndicator.HasJsTsFileInProject(EnvDTE.ProjectItems projectItems) Line 92
	at D:\git\sonarlint-visualstudio\src\Integration\Binding\JsTsProjectTypeIndicator.cs(92)
SonarLint.VisualStudio.Integration.dll!SonarLint.VisualStudio.Integration.Binding.JsTsProjectTypeIndicator.IsJsTs(EnvDTE.Project dteProject) Line 68
	at D:\git\sonarlint-visualstudio\src\Integration\Binding\JsTsProjectTypeIndicator.cs(68)
SonarLint.VisualStudio.Integration.dll!SonarLint.VisualStudio.Integration.ProjectToLanguageMapper.GetLanguagesInProject(EnvDTE.Project dteProject) Line 107
	at D:\git\sonarlint-visualstudio\src\Integration\ProjectToLanguageMapper.cs(107)
SonarLint.VisualStudio.Integration.dll!SonarLint.VisualStudio.Integration.ProjectToLanguageMapper.GetAllBindingLanguagesForProject(EnvDTE.Project dteProject) Line 83
	at D:\git\sonarlint-visualstudio\src\Integration\ProjectToLanguageMapper.cs(83)
SonarLint.VisualStudio.Integration.dll!SonarLint.VisualStudio.Integration.ProjectToLanguageMapper.HasSupportedLanguage(EnvDTE.Project project) Line 123
	at D:\git\sonarlint-visualstudio\src\Integration\ProjectToLanguageMapper.cs(123)
SonarLint.VisualStudio.Integration.dll!SonarLint.VisualStudio.Integration.ProjectSystemHelper.GetSolutionProjects() Line 92
	at D:\git\sonarlint-visualstudio\src\Integration\LocalServices\ProjectSystemHelper.cs(92)


The Project has a reference to a shared project which is called "APActivator".
Because i got no further infos on ProjectItems.Name than those of [MSDN](https://docs.microsoft.com/en-us/dotnet/api/envdte.projectitem.name?view=visualstudiosdk-2019) i can't propose a fix to this issue. But this might be enough infos to get a dev of this repo envolved.

**Comment by duncanp-sonar** [comment]
@pde-cds thanks for the report and for the investigation.

We're in the process of releasing v6.8, so it won't be fixed in that release. However, I've added this ticket to the next hardening release.
