### ISSUE TITLE
EslintBridge lifecycle refactoring

### ISSUE THREAD

**Issue by rita-gorokhod** [SonarSource/sonarlint-visualstudio#3266]
### Description

There are multiple threading and scheduling bugs with the current architecture of EslintBridgeClient, EslintBridgeProcess, and the related classes.
- #3264
- #3265 
- #3143 

We should refactor it from top to bottom so that once a solution is closed, everything related to this instance (process, queued analysis, keep-alive) is killed.

**Comment by zhouJiecode** [comment]
may i ask when to do this ?
