### ISSUE TITLE
Update embedded JavaScript analyzer to 9.9.0.19492

### ISSUE THREAD

**Issue by ilia-kebets-sonarsource** [SonarSource/sonarlint-visualstudio#3291]
SonarJS hardening before SonarQube 9.7

Release notes: https://github.com/SonarSource/SonarJS/releases/tag/9.9.0.19492

**Comment by duncanp-sonar** [comment]
@ilia-kebets-sonarsource please include a link to the release notes in the ticket (e.g. #3286, #3287). Thanks!

**Comment by ilia-kebets-sonarsource** [comment]
Hi @duncanp-sonar, I've updated my comment above. More detailed notes should be added by @gabriel-vivas-sonarsource in the coming days.
