### ISSUE TITLE
Unable to temporarily disable extension

### ISSUE THREAD

**Issue by dokmanc** [SonarSource/sonarlint-visualstudio#3388]
Using VS 2022 and SonarLint for Visual Studio 2022 version 6.10.0.57359, which is current at the time of this writing, I am unable to disable the extension.

1. I open the "Manage Extension" dialog
2 Select the SonarLint item under "Installed" and click the "Disabled" button next to it. 
3. Restart Visual Studio
4. Visual Studio shows me Sonar Lint messages in my status bar. When I return to "Manage Extensions", I see that it is still enabled.

**Comment by vnaskos-sonar** [comment]
This is no longer relevant.
