### ISSUE TITLE
Support CSS analysis

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonarlint-visualstudio#3389]
### Description

CSS analysis is now part of the JS/TS analyser (i.e. executes using Node.js). It should now be possible to support it in SLVS.

TODO
- [ ] support Standalone Mode (analysis, disabling rules, configuring rules)
- [ ] support Connected Mode (Quality Profile sync, inclusions/exclusions, server-side suppressions)

**Comment by bigfluffycookie** [comment]
The new endpoint for CSS -> 

Input:

router.post('/analyze-css', onAnalyzeCss);


filePath: string;
fileContent: string;
linterId?: string;
rules: RuleConfig[];

linterId should stay undefined

The css rules are missing in the metadata.json currently. Language Team JS Bubble is planning to have a new release including this. They will keep us posted.
