### ISSUE TITLE
Update embedded JS/TS analyzer to 9.12.1.20358

### ISSUE THREAD

**Issue by victor-diez-sonarsource** [SonarSource/sonarlint-visualstudio#3453]
Bugfix release over 9.12 improving performance within SonarLint context at startup when analyzing JS files

https://github.com/SonarSource/SonarJS/releases/tag/9.12.1.20358

**Comment by duncanp-sonar** [comment]
@victor-diez-sonarsource it looks like this bug-fix release only involved changes in the Java plugin code. Is that correct?

(if so, there is no point in us updating the analyzer embedded in Visual Studio, as we don't execute Java code).

**Comment by victor-diez-sonarsource** [comment]
Hi @duncanp-sonar ,

yes, that's correct. Indeed it should not affect VS plugin. sorry for the noise.

**Comment by duncanp-sonar** [comment]
No problem, @victor-diez-sonarsource - it helps to have an issue that records why we didn't ship this update.

Thanks for confirming!

**Comment by duncanp-sonar** [comment]
Closing as won't fix - this is a bug-fix release of the analyzer that does not contain any changes relevant to SLVS.
