### ISSUE TITLE
Team Explorer view shows stale data

### ISSUE THREAD

**Issue by michalb-sonar** [SonarSource/sonarlint-visualstudio#348]
Repro:
1. Connect when solution is closed (which results in error message as per https://github.com/SonarSource/sonarlint-visualstudio/issues/347
2. Open bound solution (the one you have credentials with).

Expected:
- User is connected.
- SQ team viewer shows project as connected

Actual:
- User is connected.
- Team viewer shows outdated message

Related Information:
    SonarLint for VS Version: Milestone 3.6
    Visual Studio Version: 2015u3

**Comment by valhristov** [comment]
This is FUBAR :) I will not be able to fix all these and I think it is worth thoroughly investigating the workflows and creating improvement tickets, because just hiding the symptoms is not doing much good in the long run.

**Comment by duncanp-sonar** [comment]
It is no longer possible to connect to SonarQube unless a solution is open so this issue will no longer arise.
