### ISSUE TITLE
Crash when invalid credentials are stored in credential manager

### ISSUE THREAD

**Issue by michalb-sonar** [SonarSource/sonarlint-visualstudio#349]
Repro:
1. Bind solution1 to project1 as user1 
2. Bind solution2 to project2 as user2 to the same SQ.
3. Close VS.
4. Open solution1.

Expected:
Solution connected to project1 as user1.

Actual:
VS crashes with message "Invalid credentials".

Related Information:
    SonarLint for VS Version: Milestone 3.6
    Visual Studio Version: 2015u3

**Comment by duncanp-sonar** [comment]
Couldn't repro the bug as described.
@michalb-sonar and I tried out various other code paths and managed to get the exception to occur:
* bind a solution
* close VS
* edit the credentials in the Windows Cred Manager so they are wrong
* restart VS
The exception is thrown, but is handled and doesn't crash VS. I'll close this issue.
