### ISSUE TITLE
Error list message when VB.NET plugin is not present on SQ

### ISSUE THREAD

**Issue by michalb-sonar** [SonarSource/sonarlint-visualstudio#351]
Repro:
1. Open solution with C# and VB.NET projects.
2. Connect to SQ with no VB.NET plugin.

Result:
The gold bar in error list appears with message "One or more rule sets are out of date or not linked to the SonarQube quality profile rule set. See output window (SonarLint) for affected projects."

I'm not sure what "update" button could do in that case. Whatever it is doing, it makes the bar disappear until VS is restarted.

The output window says:

[DEBUG SonarLintSqmFacade] RefreshCommand
Connecting to SonarQube server: http://localhost.fiddler:9000/
Connecting to SonarQube server: Validating credentials
Connecting to SonarQube server: Retrieving organizations
Checking for unbound projects.
1 unbound projects were found (VbTestApp\VbTestApp.vbproj).
[DEBUG SonarLintSqmFacade] ErrorListInfoBarShow
Connecting to SonarQube server: Detecting server plugins
   Discovered a supported plugin: Language: 'C#', Minimum version: '5.0'
   Discovered an unsupported plugin: Language: 'VB.NET', Minimum version: '3.0'
Connecting to SonarQube server: Retrieving projects
Connecting to SonarQube server: Succeeded
Connecting to SonarQube server: Downloading server settings.
DEBUGONLY: Connect workflow finished, Execution result: Succeeded

Related Information:
    SonarLint for VS Version: Milestone 3.6
    Visual Studio Version: 2015u3

**Comment by Evangelink** [comment]
Not sure whether there are some other cases but the one I can easily reproduce is linked to the connection workflow of SonarQube triggering before the solution has finished loading any project. This issue was already present before the big refactoring we did so we will postpone its fix.

**Comment by Evangelink** [comment]
Cannot reproduce the issue using master code with the following steps:
1. Create a console app
2. Bind to a SQ server (6.5) with only SonarC# (6.5) -> Issue doesn't appear
4. Close solution and reopen it while staying on Team Explorer view -> issue doesn't appear
5. Close solution and reopen it while being on Solution Explorer view -> issue doesn't appear
