### ISSUE TITLE
Credentials are only stored in credential manager during solution binding

### ISSUE THREAD

**Issue by michalb-sonar** [SonarSource/sonarlint-visualstudio#354]
This means unless users disconnect and reconnect with their credentials every time, the sessions will be anonymous, which will break at least notifications.

Related Information:
    SonarLint for VS Version: Milestone 3.6
    Visual Studio Version: 2015u3

**Comment by duncanp-sonar** [comment]
I think this is the same as #726, which has been fixed.
Closing as a duplicate.
