### ISSUE TITLE
Update embedded JS/TS analyzer to 10.0.0.20728

### ISSUE THREAD

**Issue by saberduck** [SonarSource/sonarlint-visualstudio#3543]
## What's Changed in 9.13.0
https://github.com/SonarSource/SonarJS/issues?q=is%3Aclosed+milestone%3A9.13

* Fix FNs caused by `node:` imports in several rules using `getFullyQualifiedName()` by @ilia-kebets-sonarsource in https://github.com/SonarSource/SonarJS/pull/3618
* Fix FP S2424 (`no-built-in-override`): Remove System from globals by @ilia-kebets-sonarsource in https://github.com/SonarSource/SonarJS/pull/3620
* Fix FP S6442 (`no-hook-setter-in-body`): Shouldn't raise when used conditionally by @saberduck in https://github.com/SonarSource/SonarJS/pull/3622
* Deprecate S2814 (`no-redeclare`) for TypeScript by @victor-diez-sonarsource in https://github.com/SonarSource/SonarJS/pull/3635
* Upgrade ESLint, TypeScript, and TypeScript ESLint dependencies by @yassin-kammoun-sonarsource in https://github.com/SonarSource/SonarJS/pull/3631
* Fix recursion in FQN resolution by @victor-diez-sonarsource in https://github.com/SonarSource/SonarJS/pull/3642

**Comment by yassin-kammoun-sonarsource** [comment]
## What's Changed
* Analyze JavaScript embedded in HTML by @ilia-kebets-sonarsource and @victor-diez-sonarsource  in https://github.com/SonarSource/SonarJS/pull/3674
* Fix FP S128 (`sonar-max-lines-per-function`): Improve React functional components detection by @victor-diez-sonarsource in https://github.com/SonarSource/SonarJS/pull/3679
* Fix FP S5860 (`unused-named-groups`): Consider accesses via the index syntax by @yassin-kammoun-sonarsource in https://github.com/SonarSource/SonarJS/pull/3685
* Fix FP S6329 (`aws-ec2-rds-dms-public`): Consider sensitive RDS DB instance on public subnet only by @yassin-kammoun-sonarsource in https://github.com/SonarSource/SonarJS/pull/3688
* Fix FN S6265 (`aws-s3-bucket-granted-access`): Fix BucketDeployment resolving by @yassin-kammoun-sonarsource in https://github.com/SonarSource/SonarJS/pull/3689
* Fix FN S6249 (`aws-s3-bucket-insecure-http`): Consider TypeScript `import = require()` construct by @victor-diez-sonarsource in https://github.com/SonarSource/SonarJS/pull/3665
* Update S4423 (`weak-ssl`): Change issue message when omitting `tlsSecurityPolicy` by @yassin-kammoun-sonarsource in https://github.com/SonarSource/SonarJS/pull/3687
* Add helper functions searchable documentation by @ilia-kebets-sonarsource in https://github.com/SonarSource/SonarJS/pull/3506
* Update ESLint dependencies to the latest version by @francoismora in https://github.com/SonarSource/SonarJS/pull/3682

__The support for JavaScript analysis inside HTML files required introducing the new endpoint `/analyze-html` in ESLint bridge, which behaves roughly like `/analyze-yaml` in case this is already supported.__
