### ISSUE TITLE
JavaScript Intellisense stopped working in VS2017

### ISSUE THREAD

**Issue by ArneKlein** [SonarSource/sonarlint-visualstudio#357]
### Description

I'm aware Visual Studio has a lot of issues with their JavaScript language service currently, however, it seems like SonarQube played some role in my issues with them.

We have a solution with a couple of JavaScript files in it and our editor was downgraded to a basic text editor after updating to VS 15.3. 
Intellisense, auto intending, smart brackets etc. stopped working.

I followed the workarounds detailled here and nothing helped: https://developercommunity.visualstudio.com/content/problem/8148/javascript-intellisense-not-working.html 

### Repro steps
These might work:

1. Install VS 2017.1 

2. Install the SonarLint extension

3. Update VS to the latest Version

3. Create a ASP.Net MVC 4 project, add a JavaScript file and start coding

I get the following error in the activity log after I add a this to an event handler:
`
System.ArgumentNullException: Der Wert darf nicht NULL sein. Parametername: key   bei System.Collections.Concurrent.ConcurrentDictionary`2.TryRemove(TKey key, TValue& value)   bei Microsoft.VisualStudio.JSON.Package.ErrorSources.JSONTableDataSink.RemoveFactory(ITableEntriesSnapshotFactory oldFactory)   bei Microsoft.VisualStudio.JSON.Package.ErrorSources.JSONTableDataSink.FactorySnapshotChanged(ITableEntriesSnapshotFactory factory)   bei SonarLint.VisualStudio.Integration.Vsix.TaggerProvider.UpdateAllSinks()   bei SonarLint.VisualStudio.Integration.Vsix.IssueTagger.SnapToNewSnapshot(IssuesSnapshot snapshot)   bei SonarLint.VisualStudio.Integration.Vsix.IssueTagger.OnBufferChange(Object sender, TextContentChangedEventArgs e)   bei Microsoft.VisualStudio.Text.Utilities.GuardedOperations.RaiseEvent[TArgs](Object sender, EventHandler`1 eventHandlers, TArgs args)
--

`

### Known workarounds

Remove the SonarLint Extension and reinstall it.

I'm not completely sure if the fault actually lies with the SonarLint extension, however from the activity log it seemed like it and I thought I let you guys know since I really like the extension.

**Comment by Evangelink** [comment]
Hi @ArneKlein,

Sorry for the late investigation. Do you still experience this issue? I have just followed your repro steps and I cannot get a `ArgumentNullException` exception thrown.

**Comment by ArneKlein** [comment]
Hi @Evangelink ,

thank you for your response. I can't reproduce the issue anymore either.

**Comment by Evangelink** [comment]
@ArneKlein thanks for the feedback! I'll close the ticket then :)
