### ISSUE TITLE
SonarLint Rule link compliants with SonarQube DataCenter Platform

### ISSUE THREAD

**Issue by lanneshoa** [SonarSource/sonarlint-visualstudio#3633]
Hello,

In a company with SonarQube Datacenter Edition, our workstations don't have access to internet.

We would like that the link refers to the rule, point to our on premise platform. (Internet access is denied on workstation)
eg. : https://sonarqube.mycompany.com/coding_rules?languages=cs&open=csharpsquid%AS2583
instead of 
https://rules.sonarqube.com/csharp/RSPEC-2583

https://github.com/SonarSource/sonarlint-visualstudio/blob/e5362abad51eb7655cf8b310bcc3801217b0a054/src/Core/RuleHelpLinkProvider.cs#L58

**Comment by duncanp-sonar** [comment]
@lanneshoa as requested in the "New issue" template, please use the [community forum](https://community.sonarsource.com/c/sl/visual-studio/35) for feature requests/support issues/bug reports. Thank you.

As it happens, we have just released v6.13 of SonarLint for Visual Studio, which now has rules help documentation in the IDE for almost all rules (the exception is taint rules, which will be addressed in the next release). See the [release announcement](https://community.sonarsource.com/c/sl/visual-studio/35) for more information.
