### ISSUE TITLE
Handle stream connection errors and re-connect

### ISSUE THREAD

**Issue by rita-sonarsource** [SonarSource/sonarlint-visualstudio#3648]
### Description

Code on the java side https://github.com/SonarSource/sonarlint-core/blob/4f34c7c844b12e331a61c63ad7105acac41d2efd/server-api/src/main/java/org/sonarsource/sonarlint/core/serverapi/stream/EventStream.java#L101

**Comment by duncanp-sonar** [comment]
See #3718
