### ISSUE TITLE
Typo on SonarLint for VS 2017 marketplace page

### ISSUE THREAD

**Issue by Evangelink** [SonarSource/sonarlint-visualstudio#380]
The current description is:

> conSonarLint is a Visual Studio 2017 extension that provides on-the-fly feedback [...]

![image](https://user-images.githubusercontent.com/11340282/31620843-9b352f94-b298-11e7-909e-6f3dc64ead78.png)

This shouldn't start with `con`.

**Comment by valhristov** [comment]
@Evangelink I think it is ok now.

**Comment by Evangelink** [comment]
All good!
