### ISSUE TITLE
Cannot change severity of 'major code smells' in Visual Studio

### ISSUE THREAD

**Issue by woeterman94** [SonarSource/sonarlint-visualstudio#3967]
How can I make Visual Studio show major code smells or bugs as error? It should be possible by using the .editorconfig but this doesn't seem to have any effect

```
[*.cs]

# Default severity for analyzer diagnostics with category 'Major Bug'
dotnet_analyzer_diagnostic.category-Major Bug.severity = error
# Default severity for analyzer diagnostics with category 'Major Code Smell'
dotnet_analyzer_diagnostic.category-Major Code Smell.severity = error
```

![image](https://user-images.githubusercontent.com/5755057/227262277-a5368aaa-ea5d-4d6c-9bc6-f3cb4dfb1a12.png)

**Comment by woeterman94** [comment]
Also changing the severity of one rule (without spaces) like this
`dotnet_diagnostic.S112.severity = error `

Doesn't seem to have any effect at all. It still shows as a warning in visual studio

![image](https://user-images.githubusercontent.com/5755057/227265830-bed5fe76-62ff-4826-bcfa-f3f4f759da88.png)

**Comment by woeterman94** [comment]
Would the settings.json file allow me to do this?

**Comment by duncanp-sonar** [comment]
@woeterman94 please use the [Community Forum](https://community.sonarsource.com/c/sl/visual-studio/35) for support questions, as requested in the "[New issue](https://github.com/SonarSource/sonarlint-visualstudio/issues/new)" template for this repo.

> How can I make Visual Studio show major code smells or bugs as error?

You should be able to use the .editorconfig file to configure the severity of C# and VB.NET rules as they are both Roslyn-based analyzers, although it can take VS a while before it re-analyses the code and changes the severity:

![image](https://user-images.githubusercontent.com/10757559/229489134-bbe3a53b-0f62-4702-8794-cfb54f067001.png)


> Would the settings.json file allow me to do this?
No. The `settings.json` file has no effect on Roslyn-based rules, which are configured and executed directly by Visual Studio (in any event, we currently don't map any of the Sonar severities to VS `Error` as that would break local builds, which isn't what most people want. The mapping is shown [here](https://github.com/SonarSource/sonarlint-visualstudio/wiki#rule-severities)).
