### ISSUE TITLE
How to configure rule set for C++ project

### ISSUE THREAD

**Issue by neusdan** [SonarSource/sonarlint-visualstudio#405]
Is there a way to configure the rule set for a C++ project? The described "“References” > “Analyzers”, select “Open Active Rule Set”" way does not seem to exist, at least for c++ projects.

![image](https://user-images.githubusercontent.com/5289290/31821424-5fd1d8ac-b5a5-11e7-9654-0279ec6d6dbd.png)

Additionally, moving the mouse over an issue does not show details about it. This here is not shown:

![image](https://user-images.githubusercontent.com/5289290/31822550-6e21461e-b5a9-11e7-9e6e-150c8b3384aa.png)

* SonarLint for VS Version: 3.5.0.1803
* Visual Studio Version: 2017 - 15.4.1

**Comment by Evangelink** [comment]
Hi @neusdan,

Sorry for this late answer. There is currently no way to configure rules for C/C++/Javascript in standalone mode in SonarLint for VS.

Note that we are working on providing this feature in the near future.

**Comment by Timmeey86** [comment]
> Note that we are working on providing this feature in the near future.

It's been one and a half years. Any updates on this?

**Comment by duncanp-sonar** [comment]
@Timmeey86 you might want to track #771 instead.

FYI until recently the team working on SonarLint was a virtual team - all of the team members had other responsibilities which meant progress on SonarLint was very slow. We've now created a dedicated team to focus primarily on SonarLint so we will be fixing bugs and adding new features faster. #771 is in our plans for this year.
