### ISSUE TITLE
Information section is not rendered in rule help

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonarlint-visualstudio#4094]
### Description

Rich rule descriptions can contain an `information` e.g. [javascrip:S6509](https://sonarcloud.io/organizations/duncanp-sonar-test/rules?languages=js&open=javascript%3AS6509&q=S6509)

This is not rendered in the IDE.

#### Example json - javascript:S6509
![image](https://user-images.githubusercontent.com/10757559/231774068-4031ab28-a05e-40f5-a227-93c7e97854b2.png)

### Screenshot - SonarCloud
![image](https://user-images.githubusercontent.com/10757559/231773909-65015adc-05db-4028-89de-8ddd6ed77fce.png)

### Screenshot - VS IDE
![image](https://user-images.githubusercontent.com/10757559/231773857-7bd572c2-3621-4ba4-b769-1e1dd876aa37.png)

**Comment by gabriela-trutan-sonarsource** [comment]
No longer reproducible in version 8.2 

![image](https://github.com/user-attachments/assets/fc8eaebe-e419-4cb7-bfdb-5302bf1e4877)
