### ISSUE TITLE
Display secondary locations in Visual Studio

### ISSUE THREAD

**Issue by Evangelink** [SonarSource/sonarlint-visualstudio#419]
Currently the analyzers report secondary locations for some rules. While they are used and displayed in SonarQube nothing is done within Visual Studio. Most of our users are currently using SonarLint for VS in standalone mode so I think it is worth adding a way to visualize the secondary locations directly in VS.

Ideas:
1. New window to display secondary locations.
2. Update description to include all secondary information (message, location....)
3. Extend CodeLens to display secondary locations inline
4. [Personal favorite] Update the analyzer so that if the analyzer is used within VS it doesn't report secondary locations but transform them all into issues.

**Comment by duncanp-sonar** [comment]
Superceded by #1842
