### ISSUE TITLE
Use the issues/search API to retrieve list of issues to suppress

### ISSUE THREAD

**Issue by michalb-sonar** [SonarSource/sonarlint-visualstudio#421]
Use the issues/search API to retrieve FP/won't fix issues for suppression: https://jira.sonarsource.com/browse/SONAR-9823

This allow us to filter issues before retrieving them, greatly improving performance.

**Comment by Evangelink** [comment]
Relates to #274

**Comment by duncanp-sonar** [comment]
Fixed in 4.2
