### ISSUE TITLE
[Feature Request] Extension for Visual Studio Mac

### ISSUE THREAD

**Issue by Phenek** [SonarSource/sonarlint-visualstudio#4212]
<p align="center">
  <img src="https://github.com/SonarSource/sonarlint-visualstudio/assets/4518686/c71030c1-58d4-4a0d-9fdd-3d17c50cc334" alt="Visual Studio For Mac" />
</p>

## Feature Request: SonarLint Extension for Visual Studio Mac

As a development team working across multiple platforms, it is crucial for us to ensure consistent code quality and maintain cohesion using the same analysis tools.

Currently, Visual Studio for Mac lacks the SonarLint extension that is available for Visual Studio on Windows. This missing feature creates a significant gap in our development workflow and hampers our ability to maintain the highest standards of code quality.

We kindly request your attention and consideration the development of the SonarLint extension for Visual Studio Mac. 
Its availability would greatly enhance our productivity, code quality, and alignment with the same analysis capabilities as our Windows counterparts.

The current version of Visual Studio for Mac lacks the comprehensive features and extensibility found in Visual Studio for Windows. This limitation has prompted me to open a thread on the developer community, specifically addressing the need for the SonarLint extension on Visual Studio for Mac.

You can find the thread and join the discussion here: [SonarLint-for-Visual-Studio-for-Mac](https://developercommunity.visualstudio.com/t/SonarLint-for-Visual-Studio-for-Mac/10361648)

Thank you for your time and understanding.

Best regards,

**Comment by duncanp-sonar** [comment]
Closing this feature request following Microsoft's [announcement](https://devblogs.microsoft.com/visualstudio/visual-studio-for-mac-retirement-announcement/) that Visual Studio for Mac has been deprecated.
