### ISSUE TITLE
Unable to sync custom Quality Profile from SonarCloud

### ISSUE THREAD

**Issue by benhas** [SonarSource/sonarlint-visualstudio#424]
Using SonarLint in connected mode with SonarCloud.

When using Sonar Way in C# project, the Quality Profile downloads successfully.

When changing to a custom Quality Profile in SonarCloud project, it reports the following error:

Binding solution to SonarQube project: Download quality profile(s):

SonarQube request failed: Response status code does not indicate success: 404 (). 

   Failed to download quality profile. Name: 'AnsaradaCSharp', Key: ‘EDITED', Language: 'C#'

**Comment by Evangelink** [comment]
Hi @benhas,

Please follow the issue template when creating an issue.

Could you provide the following information:
- SonarLint version
- Organization

**Comment by benhas** [comment]
Thanks @Evangelink 
SonarLint version: 3.6.0.2584
Organization: Ansarada

**Comment by Evangelink** [comment]
Hi @benhas I have confirmed the bug. Thanks for reporting it.

**Comment by valhristov** [comment]
Hi @benhas, I cannot reproduce the problem now, I suspect it was on the SonarQube side and was fixed. Could you please try again and let me know if persists? It is possible that we are missing something.

**Comment by benhas** [comment]
Thanks @valhristov, I successfully downloaded the profile after your message.

**Comment by duncanp-sonar** [comment]
Re-opened: @christophelevis and I have just encountered this with SonarCloud (v7) and SLVSv3.8.

The _organization_ parameter is not being passed in the _sonarqubeClient.GetRoslynExportProfileAsync_ call. The call succeeds for the default QP but fails for a custom QP (message _SonarQube request failed: Response status code does not indicate success: 404 ()_ in the SLVS Output window in VS).

Note: we should check that the other APIs being used by SLVS are passing the organization when required.

**Comment by RaviKlair** [comment]
can somebody confirm if this bug has been fixed ?

**Comment by baoduy** [comment]
I got the similar error from VSTS not sure if the same issue.

> 

 Failed to load the quality profiles of project 'HBD.EntityFramework': Component key 'HBD.EntityFramework' not found

**Comment by swtrse** [comment]
I still have that problem...
Solar Lint - Output:
Checking for suppressions...
Initializing the notifications package...
Initializing the telemetry package...
Loading notifications settings...
Finished initializing the telemetry package...
Connected: checking for notifications
Finished initializing the notifications package
**Failed to fetch suppressions: Response status code does not indicate success: 400 ( ).**
Initializing the daemon package...
Starting the daemon...
Running C:\Users\xxx\AppData\Local\SonarLint for Visual Studio\sonarlint-daemon-3.4.0.1536-windows\jre\bin\java.exe
Daemon started successfully.
Finished initializing the daemon package.
09:36:40.555 [main] INFO  o.s.d.Daemon - Starting server on port 8051
09:36:41.847 [main] INFO  o.s.d.Daemon - Server started, listening on 8051
Notifications are not supported on this version of SonarQube
Checking for unbound projects.
No unbound projects were found.
Checking if SonarQube Quality profile has changed.
Quality Profile is up-to-date.
