### ISSUE TITLE
Update embedded JS/TS analyzer to 10.3.2.22047

### ISSUE THREAD

**Issue by alexander-kamushkin-sonarsource** [SonarSource/sonarlint-visualstudio#4336]
10.2.0 -> [10.3.0](https://github.com/SonarSource/SonarJS/releases/tag/10.3.0.21893) -> [10.3.1](https://github.com/SonarSource/SonarJS/releases/tag/10.3.1.21905) -> [10.3.2](https://github.com/SonarSource/SonarJS/releases/tag/10.3.2.22047)

**Comment by duncanp-sonar** [comment]
Note: upgrade is currently blocked. Changes have been made to the eslintbridge API.

**Comment by saberduck** [comment]
@duncanp-sonar We did a bugfix which rollbacks the breaking changes due to performance issues we encountered. I think you should be able to upgrade now
