### ISSUE TITLE
Display severity of issues

### ISSUE THREAD

**Issue by christophelevis** [SonarSource/sonarlint-visualstudio#434]
SonarLint should show the type and severity of issues as defined by quality model:

* in the error view: in the category column, as a replacement of the current info
e.g. `Blocker Bug`, `Minor Code Smell`, instead of the type currently displayed.
** `Sonar Bug`, `Sonar Code Smell` for C#, VB.net
** `Bug`, `Code Smell` for the additional languages
* if possible, in the quick fix contextual menu, before the issue description

If icons are used, a tooltip should explain the meaning.

**Comment by valhristov** [comment]
I think we could easily display the default severity (that's in sonar-csharp), but if someone changes it for some rules on SQ we will not be able to show it.
