### ISSUE TITLE
Investigate options for cleaning XML without losing whitespace/changing formatting

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonarlint-visualstudio#4356]
### Description

See if we can make changes to the project etc XML files without losing whitespace.

Some options to investigate:
* XDocument SaveOptions
* equivalent in other .NET framework XML libraries
* regular expresssions against text
* hybrid - IXmlLineInfo to find nodes, remove from text document

**Comment by georgii-borovinskikh-sonarsource** [comment]
This works
```
var doc = new XmlDocument();
doc.PreserveWhitespace = true;
doc.Load(path);
```
