### ISSUE TITLE
Dotnet S2190 & S6422 rule descriptions contain rule cross reference inside of anchor tag

### ISSUE THREAD

**Issue by georgii-borovinskikh-sonarsource** [SonarSource/sonarlint-visualstudio#4471]
For example `<a href="https://rules.sonarsource.com/csharp/RSPEC-907">{rule:csharpsquid:S907}: "goto" statement should not be used</a>` . This is not something that we expect. We currently transform cross rule references `{rule:....}`  to links. Because of the aforementioned issue we now generate a link inside of another link, which is not valid. Here's an example `<Hyperlink NavigateUri="https://rules.sonarsource.com/csharp/RSPEC-4462"><Hyperlink NavigateUri="sonarlintrulecrossref://csharpsquid/S4462">csharpsquid:S4462</Hyperlink> - a more general version of this rule</Hyperlink>`. The inner link is generated by us and is used to open the rule description in the same IDE window instead of opening it inside of the browser.

Update: it appears to be some sort of issue with a common rule description processing tool https://discuss.sonarsource.com/t/cross-rule-references-inside-a-tags-in-html-rule-descriptions/14971

**Comment by duncanp-sonar** [comment]
Fixed by the Languages Team in a previous release.
