### ISSUE TITLE
Fix S2259 FP: Null-conditional operator + LINQ check

### ISSUE THREAD

**Issue by ivorobkalo** [SonarSource/sonarlint-visualstudio#4475]
### Description

A rule S2259 is triggered in the next code snippet however if `dataTable?.Columns.Contains("ID")` equals `true` (not `null`) the dataTable is guaranteed not to be null.

### Repro steps

`if (dataTable?.Columns.Contains("ID") == true)
{
	dataTable.Columns["ID"].ColumnName = "Id"; // Here S2259 is triggered for the dataTable variable
}`
### Expected behavior

The rule is not triggered

### Actual behavior

The rule is triggered

### Related information

* C#/VB.NET Plugins version 6.16.0.69538
* Visual Studio 2022 (17.6.4)
* MSBuild / dotnet version .Net Framework 4.7.2
* Operating System Windows 11

**Comment by gabriela-trutan-sonarsource** [comment]
I am no longer able to reproduce it with SonarLint 8.1: 
![image](https://github.com/user-attachments/assets/2c84c7c2-4329-4d18-9936-c87eb88d1c39)
