### ISSUE TITLE
S4158: False Warning

### ISSUE THREAD

**Issue by Mirzoda** [SonarSource/sonarlint-visualstudio#449]
### Description
SonarLint shows a warning that makes no sense (See screenshot below) 
![image](https://user-images.githubusercontent.com/19552723/33325961-f5d829a6-d453-11e7-8fac-32560cba893a.png)
![image](https://user-images.githubusercontent.com/19552723/33326227-abd0bf0c-d454-11e7-86d3-7ba1a06022e3.png)

### Repro steps
Create a collection (List in screenshot) and check when it's length is longer than 0 it sort the list.

### Expected behavior
Normally no warning should be given, unless it can be checked if the content would only contain one item. 

### Actual behavior
A warning that the collection is empty (which it isn't due to the if-check).

### Known workarounds
None

### Related information

* SonarLint for VS Version: 3.7.0.2645
* Visual Studio Version: Professional v15.3.5)
* SonarQube server version
* Languages in your solution: C#

**Comment by valhristov** [comment]
Hi @Mirzoda, could you please send us the whole method that raises the issue? If you are not allowed to share it with third parties, you could reduce it to the minimum that can be used to demonstrate the problem. It would be very difficult to fix it otherwise. Thanks in advance!

**Comment by Mirzoda** [comment]
Attached you'll find the method where that warning is given. I've changed almost all the names as it's company stuff, I just can't copy paste the code how it is. 
[SonarLint.txt](https://github.com/SonarSource/sonarlint-visualstudio/files/1512936/SonarLint.txt)

**Comment by valhristov** [comment]
Thanks a lot! The code was of great help identifying the problem - we are still unable to correctly detect the data flow through loops and the similar rules (expression always true/false, null dereference, dead stores) usually raise false positives when there is a loop inside the method. Since we have identical issue in SonarC# - SonarSource/sonar-csharp#767, I will close this one.
