### ISSUE TITLE
Support non-intrusive Connected Mode

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonarlint-visualstudio#4498]
### Description

See [MMF-3008](https://sonarsource.atlassian.net/browse/MMF-3008).

The existing Connected Mode settings format has three main drawbacks:
* the configuration files are stored under what is normally a source-controlled location
* C# and VB.NET rule analysis is configured using ruleset files, which have been deprecated
* the configuration of analysis for C# and VB.NET involves making changes to the project files

The new Connected Mode format addresses all three of these problems.

[MMF-3008]: https://sonarsource.atlassian.net/browse/MMF-3008?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by Bosch-Eli-Black** [comment]
Yay!!! ^_^
