### ISSUE TITLE
DotCover Results Disparity

### ISSUE THREAD

**Issue by Paulie-Waulie** [SonarSource/sonarlint-visualstudio#450]
### Description

We have been using dotCover which feeds into our Sonar Analysis for a little while without issue. To help resolve an issue we had with Sonar Lint we updated the the Sonar C# plugin last week to version 6.6. Immediatley after this update our code coverage metrics drastically changed. We did have coverage of 93% which then dropped to 73%. We utilize a dot cover configuration xml file to detail any module and class filter masks, as there is a reasonable amount of configuration classes or data access classes which are not covered by unit tests we need to filter these types out to not affect the actual coverage metric. On face value it appears that a lot of our filters are no longer always being taken into consideration in Sonar,where as in the past they always were and missing coverage for the filtered types was not reported. 

As a first step I looked at the outputted dotCover HTML report (the file fed into Sonar) and it was detailing the same coverage as we were expecting (93% overall) and was not reporting classes that had been masked in the configuration file. I then tried a different version of dotCover, we were using 2017.1.3 on the build agent which was upgraded to 2017.2.2 which does generate a sligtly different report but the result in Sonar was the same, 73% opposed to the 93% shown in the dot cover report.

The image below shows the html report outputted by dotCover:

![image](https://user-images.githubusercontent.com/12846390/33327862-68d7fc82-d450-11e7-964a-4d29be49ad8b.png)

The image below shows the coverage stat in Sonar:

![image](https://user-images.githubusercontent.com/12846390/33327856-62afa7ce-d450-11e7-9abd-11fed3ff0756.png)

The image below shows our test coverage history in Sonar, as you can see, apart from a dip caused by a bad check in, after we configured our class masks our coverage stat was quite high and stable until the final analysis which is the date that we updated the plugin. This may be unrelated as there was around two weeks where that code base had not been worked on and analysed but it seems coincidental that it occurred the day that the plugin was updated along with fact that the coverage report from dot cover seems the same as before.

![image](https://user-images.githubusercontent.com/12846390/33328386-c4727288-d451-11e7-94e9-cc0b5d8cade6.png)

### Repro steps

Run dotCover as part of the analysis and feed the output HTML report into Sonar.

### Expected behavior

The test coverage metrics match the output of the dotCover report.

### Actual behavior

The coverage metrics differ to the output of dotCover with missing coverage detailed for classes excluded by dot cover in the dot cover configuration file.

### Known workarounds

None known.

### Related information

VS 2017 - V15.2,
Sonar Lint V3.7.0.2645
Sonar Qube V6.4.0.25310.
Sonar C# Plugin V6.6

Tested with same results using dotCover:
dotCover V2017.1.3 
dotCover V2017.2.2

**Comment by Paulie-Waulie** [comment]
Apologies, I'm closing this as I just realised that this is issues for Sonar Lint, I have moved this to the Sonar Google group.

**Comment by Evangelink** [comment]
Hi @Paulie-Waulie,

No worries! SonarQube Google Group is indeed the right place. If you prefer to track through GitHub issues you could post it in the [sonar-csharp](https://github.com/SonarSource/sonar-csharp) github page.
