### ISSUE TITLE
Sonarlint not working within VS 2017

### ISSUE THREAD

**Issue by naymore** [SonarSource/sonarlint-visualstudio#457]
I installed solarlint for vs 2017 using SonarLint.VSIX-3.8.0.2728-2017.vsix.
After installation I opened up VS and opened an arbitrary  source code file - and nothing happened.
Looking at https://www.sonarlint.org/visualstudio/howto.html I figured there should be a configuration menu within the Options - but that's not the case either.
Unfortunately I cannot run the installer a second time because the installer claims it has already been installed. Unfortunately that's solely the installer's opinion. Not mine. Not VisualStudio's.

Visual Studio Enterprise v15.5.1
There is nothing fancy about my Visual Studio installation. In fact I don't have any other extensions installed.

**Comment by naymore** [comment]
Uninstalled it using vsixinstaller.
Reinstalled it with local admin rights (which I probably didn't have previously - and the installer doesn't ask for it).

Working fine now.

**Comment by duncanp-sonar** [comment]
Thanks for the update @naymore. FYI the VSIX shouldn't require admin privileges (I don't use admin privileges when installing it).

Other potential workarounds:
* run _devenv /updateConfiguration_. This tells VS to refresh the cache of MEF components that are available.
* run _devenv /setup_. This tells VS to do a more exhaustive re-registration of the installed extensions (not just the MEF components).
