### ISSUE TITLE
Unify first day ping with other SonarLint variants

### ISSUE THREAD

**Issue by christophelevis** [SonarSource/sonarlint-visualstudio#458]
Since v3.6, SonarLint for Visual Studio sends `days_since_installation=1` on the first day.
It should be consistent with the way it behaves in the other IDEs. After installation and until the day changes, the first ping should contain `days_since_installation=0`.

**Comment by Evangelink** [comment]
Hi @christophelevis,
Could we have a quick look at all the properties to make sure we have a standard definition for them all instead of doing multiple fixes?

Cheers,
Amaury

**Comment by christophelevis** [comment]
Checked with @valhristov: except for that property, all sounds good.
