### ISSUE TITLE
Handle SQ API changes for paged results

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonarlint-visualstudio#4632]
### Description

SonarQube are dropping the deprecated paging fields from all APIs that return paged results in the v10.x time frame (not clear exactly when yet).

See [SONAR-19233](https://sonarsource.atlassian.net/browse/SONAR-19233). 

We need to continue to support the current LTS, so we will have to handle both the old and new response formats.

Related: [SLCORE-528](https://sonarsource.atlassian.net/browse/SLCORE-528)

[SONAR-19233]: https://sonarsource.atlassian.net/browse/SONAR-19233?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SLCORE-528]: https://sonarsource.atlassian.net/browse/SLCORE-528?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by ugras-ergun-sonarsource** [comment]
We already support this and have tests in place 

https://github.com/SonarSource/sonarlint-visualstudio/blob/master/src/SonarQube.Client.Tests/SonarQubeService_PagedRequestTests.cs
