### ISSUE TITLE
Do not store data in the user's roaming profile

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonarlint-visualstudio#470]
### Description

SonarLint stores the SonarLintDaemon binaries and plugins in the user's roaming profile which means that they are copied to any WindowsNT domain-joined machine that the user logs on to.

The files should be stored in a per-user, non-roaming location.

### Examples of files that are currently stored in the roaming profile
_AppData\Roaming\sonarlint
AppData\Roaming\SonarLint for Visual Studio\telemetry.xml
AppData\Roaming\sonarlint-daemon-2.14.0.669-windows
sonarlint-daemon-2.17.0.899-windows_

### Notes
* _Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData)_ returns 
e.g. _C:\Users\fredbloggs\AppData\Roaming_

_Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData)_ returns 
e.g. _C:\Users\fredbloggs\AppData\Local_ (non-roaming)

* other SonarQube files are store in e.g. _C:\Users\fredbloggs\.sonar_

* ?should the _telemetry.xml_ file roam?

**Comment by Evangelink** [comment]
I tend to think that storing the telemetry data in the roaming profile is actually a good idea as it allows to reduce the number of pings from the same user (if the roaming is properly sync). WDYT?
