### ISSUE TITLE
[Infra] Update VSSDK version used for VS2019

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonarlint-visualstudio#4837]
### Description

We import different versions of the VSSDK meta-package for VS2019 and VS2022. We're still using v15 of the VSSDK for our SLVS 2019 build i.e. we're still using a version that is compatible with VS2017, which we no longer support.

We can update to a v16.x version of the VSSDK. It shouldn't make any difference at runtime since we don't include any VSSDK assemblies in our VSIX - we'll still be using whichever assembly versions VS ships with. However, there might be new APIs that we could use.

The version used is set in [SonarLint.VsPkgRefs.props](https://github.com/SonarSource/sonarlint-visualstudio/blob/master/src/SonarLint.VsPkgRefs.props).

**Comment by georgii-borovinskikh-sonarsource** [comment]
VS19 support has been dropped
