### ISSUE TITLE
Taint rule help for SonarCloud does not show in the IDE

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonarlint-visualstudio#4849]
### Description

Clicking on the rule id to show taint rule help when connected to SonarCloud shows the rule help from `rules.sonarsource.com` in a browser, rather than in the IDE.

### Repro steps
* Open a solution with taint issues that is connected to SonarCloud (e.g. the sample VS2019 bound solution)
* open a file containing taint issues
* click on the rule id of one of the issues in the Taint window i.e.

![image](https://github.com/SonarSource/sonarlint-visualstudio/assets/10757559/7ed37cf9-64a6-4826-b8a4-51f2c2205d4f)

### Expected
The rule help is shown in the IDE.

### Actual
The rule help is shown in the browser.

#### Notes
Error logged in the Output Window:
```
[ThreadId 109] [DEBUG] Looking up implementation of 'IGetRulesRequest' on thread '109'
[ThreadId 109] [DEBUG] Created request of type 'SonarQube.Client.Api.V10_2.GetRulesWithCCTRequest'.
[ThreadId 109] [DEBUG] Sending Http request:
[ThreadId 109] [DEBUG] Method: GET, RequestUri: 'api/rules/search?qprofile=AWJypR-No-4kJLXn1_rR&rule_key=roslyn.sonaranalyzer.security.cs%3AS2083&f=repo%2CinternalKey%2Cparams%2Cactives%2ChtmlDesc%2Ctags%2Cname%2ChtmlNote%2CdescriptionSections%2CeducationPrinciples%2CcleanCodeAttribute&p=1&ps=500', Version: 1.1, Content: <null>, Headers:
{
}
[ThreadId 92] [DEBUG] Response with HTTP status code 'BadRequest' received.
[ThreadId 92] [Rules] Error getting rules from SQ Server. Rule ID: roslyn.sonaranalyzer.security.cs:S2083 
Error:Response status code does not indicate success: 400 ().
```

Requesting that API directly from SonarCloud gives the following response:
```
{"errors":[{"msg":"Value of parameter \u0027f\u0027 (cleanCodeAttribute) must be one of: [actives, createdAt, debtOverloaded, debtRemFn, defaultDebtRemFn, defaultRemFn, deprecatedKeys, descriptionSections, educationPrinciples, effortToFixDescription, gapDescription, htmlDesc, htmlNote, internalKey, isExternal, isTemplate, lang, langName, mdDesc, mdNote, name, noteLogin, params, remFn, remFnOverloaded, repo, scope, severity, status, sysTags, tags, templateKey, updatedAt]"}]}
```

This is essentially the same underlying issue as #4848 - we're including a parameter in the request that is supported on SonarQube but not on SonarCloud. However, the impact is much less severe. In this case, the bug was introduced in [here](https://github.com/SonarSource/sonarlint-visualstudio/blame/a26de5e6764be2606a62407e9a4272960633973d/src/SonarQube.Client/Api/DefaultConfiguration.cs#L91). 

This issue only affects taint help when connected to SonarCloud, because taint help is currently fetched from the server.
It does not affect help for non-taint issues since that data is embedded in SLVS.

Rolling back the change mean help for taint issues would show in the IDE. However, there is a caveat: the help would display the old non-CCT severities, whereas the taint issues list will show the new severity calculated from the CCT values
i.e. inconsistent data being shown in the IDE.

**Comment by georgii-borovinskikh-sonarsource** [comment]
This has been fixed as of 7.4
