### ISSUE TITLE
Inconsistent ContentType attributes in view taggers

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonarlint-visualstudio#4891]
### Description

Most of our tagger providers work with `[ContentType("text)]`.

However, `IViewTaggerProvider` and `IssueHighlightViewTaggerProvider` both work with the more restrictive `[ContentType("code")]`.

TODO - investigate whether this is an issue and if so fix it
The difference in content types probably means that we could analysing and tagging document types but not then visualising secondary locations issues for those files.

In practice, this probably only applies to Secrets currently, which don't have secondary locations at the moment. Logically, it is still incorrect, though.

**Comment by ugras-ergun-sonarsource** [comment]
I did some investigation and tried to find out some documentation about the issue but there weren't really useful. It needs more investigation but it seems it's OK as long as Secrets don't have secondary locations.
