### ISSUE TITLE
[Editor perf] Investigate whether we can avoid creating taggers by specifying TextViewRoles for tagger providers

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonarlint-visualstudio#4892]
### Description

Our `IssueLocationAdornmenTaggerProvider` tagger provider has the attribute `[TextViewRole(PredefinedTextViewRoles.PrimaryDocument)]` to limit when it is created by VS.

None of our other taggers providers do.

TODO - investigate whether we could apply `TextViewRole` to limit when other tagger providers are created.
Are some of our tagger providers currently being created for e.g. diff windows, peek windows etc, and would setting the attribute prevent it?

**Comment by georgii-borovinskikh-sonarsource** [comment]
Doesn't affect buffer taggers. View taggers in our solution already have that.
