### ISSUE TITLE
Status Bar Icon is missing

### ISSUE THREAD

**Issue by ugras-ergun-sonarsource** [SonarSource/sonarlint-visualstudio#5004]
SonarQube icon in the Status Bar of visual studio is not loaded correctly in newer versions of Visual Studio (at least greater than 17.4). And we got an assertion fail if we run it in Debug mode.

![image](https://github.com/SonarSource/sonarlint-visualstudio/assets/96827714/970b268e-b04c-40d1-94fa-c63b976f8155)

**Comment by georgii-borovinskikh-sonarsource** [comment]
https://github.com/snoopwpf/snoopwpf could be useful here
