### ISSUE TITLE
Can not find Java 17

### ISSUE THREAD

**Issue by Spenhouet** [SonarSource/sonarlint-visualstudio#5051]
As there isn't a single issue on this here and I really can not get this solved... I'm opening one for future readers.

I'm using VS Code in WSL. The extension always shows:

![image](https://github.com/SonarSource/sonarlint-visualstudio/assets/7819068/fe67f8ba-9740-459f-9f09-57d904fddc05)

It does not come with the JRE (as stated in the extension description).
There is now auto-install.

I installed it manually. My WSL now has Java 17. 

I did also set:

```
"sonarlint.ls.javaHome": "/usr/lib/jvm/java-17-openjdk-amd64/bin/java"
```

as the extension description suggest, but VS Code marks it as unused setting.

I can not get this resolved.

**Comment by FREDDY-QUEZADA** [comment]
Tuve el mismo problema en mi caso se tuve que agregar manualmente las variables de entorno JDK17   y volvi a crear la carpeta de PATH con el directorio dicreccionando al bin de JDK 
<img width="436" alt="image" src="https://github.com/SonarSource/sonarlint-visualstudio/assets/134630066/f734a3f5-904e-4242-b5cf-d04341cf5282">

**Comment by pavel-mikula-sonarsource** [comment]
Hi, 

this repository is for SonarLint for Visual Studio, not for VS Code. 

Our Community forum is the correct place to send posts, as you did.

Thank you
