### ISSUE TITLE
Tool column for C#/VB.NET issues should display SonarLint

### ISSUE THREAD

**Issue by christophelevis** [SonarSource/sonarlint-visualstudio#509]
For C# issues reported by SonarLint, the Tool column in the Error List shows `SonarAnalyzer.CSharp[SonarLint for Visual Studio 201x]`.
In order to make it simple and clear for the developer, we should simply display `SonarLint` like it's already the case for JS/C/C++ issues.

**Comment by duncanp-sonar** [comment]
@christophelevis I'm not sure we can change what appears in the Tool column. Even if we can, it might be something we need to change in the analyzer repo.

I've had a quick look and I can't see any place where we can set the Tool/Source description through the Roslyn public API. It looks like the Tool description is constructed from {assembly name}[{VSIX product name}]. I might have missed something, though.
