### ISSUE TITLE
Make branch matching algorithm aligned with other SonarLint flavours. 

### ISSUE THREAD

**Issue by ugras-ergun-sonarsource** [SonarSource/sonarlint-visualstudio#5092]
There are two differences between SLVS and other flavours. 

- [x] We do not ignore short-lived branches. (only applicable to SC; in SQ there's no distinction of short-lived vs long-lived branches) 
- [x] We need to prioritise main branch when there's a tie between branches. 

Based on slack discussion: https://sonarsource.slack.com/archives/C03PE8P8TK6/p1701336633925369

**Comment by kevin-hinz** [comment]
🙏 Please notify the Documentation Squad when this issue is started. 
DOC-1043 is waiting to implement the changes to the docs.

**Comment by ugras-ergun-sonarsource** [comment]
We haven't done a proper hardening sprint since this was created it'll be the top ticket when we do a hardening.
