### ISSUE TITLE
Embed SonarC# 9.18.0.83559 and SonarVB 9.18.0.83559

### ISSUE THREAD

**Issue by antonioaversa** [SonarSource/sonarlint-visualstudio#5196]
Release note: https://github.com/SonarSource/sonar-dotnet/releases/tag/9.18.0.83559
Summary: Hardening: 5 FPs for C#, 1 FPs for VB.NET, 2 message improvements for C#, 1 rule deprecation

**Comment by georgii-borovinskikh-sonarsource** [comment]
Superseded by #5201 & #5238
