### ISSUE TITLE
Embed SonarC# 9.21.0.86780

### ISSUE THREAD

**Issue by zsolt-kolbay-sonarsource** [SonarSource/sonarlint-visualstudio#5272]
**Release Notes:** https://github.com/SonarSource/sonar-dotnet/releases/tag/9.21.0.86780
**Summary:** 6 new logging rules were added, fixed AD0001 in the Symbolic Execution engine, and several rules were promoted from non-SonarWay to SonarWay.

**Comment by georgii-borovinskikh-sonarsource** [comment]
Superseded by #5321
