### ISSUE TITLE
Sonarlint doesn't seem to work in VSCode if path contains spaces (%20)

### ISSUE THREAD

**Issue by messeant** [SonarSource/sonarlint-visualstudio#5315]
Hello

Sonarlint doesn't seem to work in VSCode if path contains spaces (%20)

![image](https://github.com/SonarSource/sonarlint-visualstudio/assets/6958444/9563f57d-4d71-4ad7-bcba-95109b441250)

THANKS

**Comment by pavel-mikula-sonarsource** [comment]
Hi @messeant, 

this repo is for Visual Studio, not for VS Code.

Please create a new thread on https://community.sonarsource.com/c/sl/vs-code/36

Thank you
