### ISSUE TITLE
Suggestion: Support for Java

### ISSUE THREAD

**Issue by ChrisTrenkamp** [SonarSource/sonarlint-visualstudio#533]
### Description

As a user of Visual Studio Code and Java, I would like to have SonarLint integration for the Java language for quick feedback.

I've been keeping an eye on the [Java plugin](https://code.visualstudio.com/docs/languages/java) for VSC, and it's shaping up quite nicely.  Eclipse is long in the tooth and has a lot of annoyances that add up.  VSC is looking more and more like a great replacement.  The one last critical piece that's missing is SonarLint, which really helps with our development process.

If support for Java can be added to the SonarLint plugin, VSC can be our full-time dev environments.

**Comment by Evangelink** [comment]
Hi @ChrisTrenkamp,

Thanks for raising an issue but this repository is about SonarLint for Visual Studio (not VSCode). Could you please open a thread in this [Google Group](https://groups.google.com/forum/#!forum/sonarlint)? FYI here is the [issue tracker for VSCode](https://jira.sonarsource.com/browse/SLVSCODE).

Thanks for the suggestion!
