### ISSUE TITLE
Update embedded JS/TS analyzer to 10.13.0.25911

### ISSUE THREAD

**Issue by zglicz** [SonarSource/sonarlint-visualstudio#5333]
10.13.0 https://github.com/SonarSource/SonarJS/releases/tag/10.13.0.25911

- Drop support for NodeJS v16
- Disable type-checking for Vue.js
- Hardening

**Comment by ugras-ergun-sonarsource** [comment]
@zglicz so now minimum supported node version is 17 is that correct?
