### ISSUE TITLE
Embed SonarC# 9.24.0.89429 and SonarVB 9.24.0.89429

### ISSUE THREAD

**Issue by Tim-Pohlmann** [SonarSource/sonarlint-visualstudio#5386]
This release contains one new ASP.NET Rule ([S6961](https://sonarsource.github.io/rspec/#/rspec/S6961/csharp)) and several general improvements and fixes.
[Release Notes](https://github.com/SonarSource/sonar-dotnet/releases/tag/9.24.0.89429)

**Comment by georgii-borovinskikh-sonarsource** [comment]
Superseded by #5406
