### ISSUE TITLE
Use AsyncPackage class instead of Package to load in the background

### ISSUE THREAD

**Issue by madskristensen** [SonarSource/sonarlint-visualstudio#539]
Hey there. 

We (the VS extensibility team) are trying to help extension authors follow best practices to ensure the best possible performance and reliability. We've discovered an opportunity in SonarLint to make it more performant with very small code changes.

In the VSIX projects, you are currently using the `[ProvideAutoload]` attribute at least on one of the classes deriving from the `Package` class. That causes the package to be synchronously loaded on Visual Studio startup which has very bad performance impact for the users. 

Please see https://msdn.microsoft.com/en-us/library/mt750288.aspx on how to use the `AsyncPackage` class instead to load in the background with very few code changes.

For more info, please reach out to me at madsk@microsoft.com

**Comment by madskristensen** [comment]
Let me know if there is anything I can do to help with this

**Comment by madskristensen** [comment]
Specifically, the slow package is the [SonarLintDaemonPackage](https://github.com/SonarSource/sonarlint-visualstudio/blob/5114ca9f61080dceb8605321c02a0becf58bd468/src/Integration.Vsix/SonarLintDaemonPackage.cs)

**Comment by Evangelink** [comment]
Hi @madskristensen,

Thanks for the feedback and the offer to help. We already identified the problem with this package when it was created. Back then the team who worked on it ended up with deadlocks when using `AsyncPackage` so we decided to go like this and to plan a rewrite of the daemon package later on. Sadly we haven't been able to tackle it yet.

We will try to plan a sprint on this soon (note it's pretty likely it won't be next sprint).

Cheers,
Amaury

**Comment by madskristensen** [comment]
Do you remember if the deadlock was on this line? https://github.com/SonarSource/sonarlint-visualstudio/blob/5114ca9f61080dceb8605321c02a0becf58bd468/src/Integration.Vsix/SonarLintDaemonPackage.cs#L80

If so, I can take a look at creating a PR that avoids that deadlock

**Comment by Evangelink** [comment]
I am afraid I don't remember. I haven't worked on this package but I had a quick look at fixing the issue and back then the choice was between rewrite and not using the `AsyncPackage`. I'll try to have a look tomorrow (I am UTC+1).

**Comment by madskristensen** [comment]
@Evangelink I found out what the deadlock was and fixed the issue in PR #572
