### ISSUE TITLE
Embed SonarC# 9.27.0.93347 and SonarVB 9.27.0.93347

### ISSUE THREAD

**Issue by martin-strecker-sonarsource** [SonarSource/sonarlint-visualstudio#5486]
Release Notes: https://github.com/SonarSource/sonar-dotnet/releases/tag/9.27.0.93347
Summary: Hardening FP/FN fixes

**Comment by georgii-borovinskikh-sonarsource** [comment]
Moved to https://sonarsource.atlassian.net/browse/SLVS-1222?atlOrigin=eyJpIjoiOTU5YzRmYWRiODU0NGFiNWI0YmMwNzkyNjE3NWVkYmQiLCJwIjoiaiJ9
