### ISSUE TITLE
Please Support ARM64

### ISSUE THREAD

**Issue by EmrecanKaracayir** [SonarSource/sonarlint-visualstudio#5511]
It can be easily done by following these [steps](https://devblogs.microsoft.com/visualstudio/now-introducing-arm64-support-for-vs-extensions/).

**Comment by costin-zaharia-sonarsource** [comment]
Hi @oising, I do not work in the SonarLint team. I'm not sure how I can help.

**Comment by oising** [comment]
> Hi @oising, I do not work in the SonarLint team. I'm not sure how I can help.

Okay, it didn't seem _crazy_ to tag you when you have sonarsource in your name. Is the lint plugin not supported by your company?

**Comment by emanuelezambrano** [comment]
Download the vsix extension from the marketplace.
Open with 7zip and double-click the file "extension.vsixmanifest" to open with Notepad or Visual Studio (depending on your settings).
Search and replace "amd64" with "arm64" (in the "InstallationTarget" section).
Save the file and jump back to 7zip; a popup appears that tell you if you want to update the archive; click yes.
Install the extension and enjoy Sonarlint on VS2022/Windows ARM

**Comment by oising** [comment]
> Download the vsix extension from the marketplace. Open with 7zip and double-click the file "extension.vsixmanifest" to open with Notepad or Visual Studio (depending on your settings). Search and replace "amd64" with "arm64" (in the "InstallationTarget" section). Save the file and jump back to 7zip; a popup appears that tell you if you want to update the archive; click yes. Install the extension and enjoy Sonarlint on VS2022/Windows ARM

This works. @sylvain-combe-sonarsource -- all your team needs to do is adjust the manifest to declare support for arm64. No code changes neccessary. I can confirm the above works on a WOA 11 ARM64 with VS 2022 ARM64. Works perfectly.

**Comment by pavel-mikula-sonarsource** [comment]
Hi everyone,

As this is a request for a new feature, please add your voice to this card:
https://portal.productboard.com/sonarsource/4-sonarlint/c/514-support-sonarlint-for-visual-studio-on-arm-64-devices?&utm_medium=social&utm_source=starter_share

It will help PMs prioritize it.
