### ISSUE TITLE
S1144 FP: Embedded private classes don't recognize use of indexer properly

### ISSUE THREAD

**Issue by cdanek** [SonarSource/sonarlint-visualstudio#5715]
When using embedded private classes, S1144 alerts on unused private property 'this[]'.

C# Repro Below.

```cs
using System.Collections.Generic;

namespace MyTest
{
    public class MyClass
    {
        public void MyMethod()
        {
            MyTree tree = new();
            tree[1].Value = 0;
        }

        private class MyNode
        {
            public int Value;
        }

        private class MyTree
        {
            private readonly List<MyNode> _nodes = new();
            public MyNode this[int index] => _nodes[index];

            public MyTree()
            {
                _nodes.Add(new MyNode() { Value = 1 });
                _nodes.Add(new MyNode() { Value = 2 });
            }
        }
    }
}

**Comment by pavel-mikula-sonarsource** [comment]
Hi @cdanek,

https://community.sonarsource.com/c/clean-code/fp/7 is the best place to report issues with our analyzers, as this repo does not contain the analyzers, only the extension.

Out of curiosity, how did you create this issue? By default, the [Create Issue](https://github.com/SonarSource/sonarlint-visualstudio/issues/new/choose) page should guide you toward the link I've mentioned above.
