### ISSUE TITLE
[Connected Mode] VS freezes when retrieving the list of projects from the server

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonarlint-visualstudio#580]
When SLVS establishes a connection to the server it retrieves the list of projects. This can happen either when establishing a connection for the first time or when re-opening a bound solution.
Some customers have thousands of projects, and VS freezes while the list of projects is retrieved.

This applies to both legacy mode and connected mode.

### Related
DONE: #274 - _Update usage of deprecated API_. The API being used to fetch the list of projects has been deprecated and the replacement API is paginated. However, switching the API being used may not be enough on its own if most of the work is being triggered from the UI thread.

### Workaround
Use SQ permissions to restrict the number of projects the user can see

### Notes
This bug is a particular problem in the "re-opening bound solution" case as the user will hit it every time they open a solution.

**Comment by Evangelink** [comment]
The problem is actually mainly linked to the MS style we are using and that is breaking the virtualization of the tree hence forcing the rendering of all elements. This comment doesn't cancel the fact that using another API and fetching asynchronously would help improving performances.

**Comment by duncanp-sonar** [comment]
As noted above, there was a problem with the treeview styles that had been copied from the MS TeamExplorer resources to maintain the same look and feel. 
Comparison of our customised styles with the default TreeView styles showed that our treeview style was missing a ScrollViewer element and VirtualizingStackPanel triggers, and the TreeViewItem was missing the triggers.

I've amended our styles to include the missing elements and manually tested on all three versions of VS. The treeview is now virtualized so the UI no longer freezes when the project list is rendered. However, some operations are still slow if the list contains a very large number of projects - scrolling is ok, but collapsing the entire list/switching to another Team Explorer page can be slow.
