### ISSUE TITLE
Confusing recognition of "Duplicate Values" as Arguments

### ISSUE THREAD

**Issue by JaedenRuiner** [SonarSource/sonarlint-visualstudio#581]
### Description

[](https://rules.sonarsource.com/csharp/RSPEC-4142)

This seems to be in error over all, because there is no way to truly determine a _mistake_.  The `Compare(point.X, point.X)`
example is a valid recognition of a mistake but not if you are drawing a horizontal line on a canvas:
```
       using (Pen pen = new Pen(this.Owner.BackColor))
       {
           Rectangle clientRect = ClientRectangle;
           e.Graphics.DrawLine(pen, clientRect.Left, clientRect.Bottom - 1, clientRect.Right - 1, clientRect.Bottom - 1); //  clientRect.Bottom - 1 is the Y for a straight horizontal line
       }
```
or Adding an Excel® Worksheet via Interop:
```
        public XL.Worksheet NewSheet(string name)
        {
            if (this.IsOpen && !this.SheetNames.Contains(name, StringComparer.OrdinalIgnoreCase))
            {
                this.CurrentSheet = this.Sheets.Add(Type.Missing, Type.Missing, Type.Missing, XL.XlSheetType.xlWorksheet) as XL.Worksheet; //<------
                this.CurrentSheet.Name = name;
                this.SheetNames.Add(name);
                return this.CurrentSheet;
            }
            return null;
        }

```
or adding DataTable column mapping for Data Adapters
```
        protected override DataTableMapping CreateTableMappings()
        {
            DataTableMapping tableMapping = new DataTableMapping();
            tableMapping.SourceTable = this.SafeTableName;
            tableMapping.DataSetTable = this.TableName;
            foreach (DataColumn column in this.TypedTable.Columns)
            {
                tableMapping.ColumnMappings.Add(column.ColumnName, column.ColumnName); //this is a default behavior.  overrides can make for updated mappings, but defaultly the column name is the datasource name
            }
            return tableMapping;
        }

```

### Repro steps

1. Easily replicated by way of the examples above.  Drawing a line on a canvas is a great example of a scenario where the same value is expected. That or utilizing the Type.Missing with a call to a Microsoft Office® Interop call, where Type.Missing is a valid COM place holder.
2. Build.

### Expected behavior
That it would not assume that the value was incorrect.  
### Actual behavior
This is listed as a MAJOR code smell, but in all honesty the only times it has ever detected this issue in my code is when it was completely logical to use the same value twice.
Please provide a description of the actual behavior you observe.
### Known workarounds
Ignore it or use a #Pragma.

### Related information
* SonarLint for VS Version: 7.0.0.4784
* Visual Studio Version: Enterprise 14.0 Update 3
* SonarQube server version: 5.6.7
* Languages in your solution C#

**Comment by Evangelink** [comment]
Hi @JaedenRuiner,

We have been discussing a lot about this rule internally because it generates far more False Positives than real issues. The outcome of the discussion was to deprecate the rule for the time being (waiting to find a better algorithm).

You can see it's marked as `deprecated` here: https://jira.sonarsource.com/browse/RSPEC-4142

**Comment by Evangelink** [comment]
See deprecation ticket https://github.com/SonarSource/sonar-csharp/issues/1222
