### ISSUE TITLE
RSPEC-S2228 - Not appropriate in ConsoleApplication

### ISSUE THREAD

**Issue by JaedenRuiner** [SonarSource/sonarlint-visualstudio#582]
### Description

[](https://rules.sonarsource.com/csharp/RSPEC-2228)

Indicates that Console.WriteLine() is a "Logging Statement".  However, in a ConsoleApplication that is the primary avenue for communication with the user, if the application so desires.

### Repro steps

1. Create ConsoleApplication
2. Add a Console.WriteLine("Hello World"); to the Main method.

### Expected behavior

No warning.

### Actual behavior

Warning to "Remove this logging statement."

### Known workarounds
Pragma or Ignore

### Related information

* SonarLint for VS Version: 7.0.0.4784
* Visual Studio Version : 14.0 Update 3
* SonarQube server version :5.6.7
* Languages in your solution C#

**Comment by Evangelink** [comment]
Hi @JaedenRuiner,

You are right! I have noticed this behavior while working on a simple console app. I am moving this issue to the analyzer https://github.com/SonarSource/sonar-csharp/issues/1223
