### ISSUE TITLE
Conflicting RSPECs 3168 and 3241

### ISSUE THREAD

**Issue by JaedenRuiner** [SonarSource/sonarlint-visualstudio#591]
### Description

Given that the challenge of multi-threaded applications is a complicated enough affair for humans to wrap their minds around, I find it amusing that we attempted to give the AI of the analyzer a shot at it.  That being said the expected occurred.  
The analyzer cannot detect the appropriate entry point for an asynchronous process, and it gets confused.  If there is a method that is "async" it cannot be void, but if it returns Task it must be used in an "await" statement.  It's really pick your poison, and you don't win either way.  
This is primarily a problem for UI interaction, where thread lines cannot be crossed.  So, if you have an time consuming operation, but still want the UI to function without freezing - perhaps giving it a progress meter, it is beneficial to use the Task system.  (I'm still a little old school with BackgroundWorker, or direct Thread creation, but the Task system is becoming a more elegant method for this scenario)

### Repro steps

1. WebDownload Test: (may need to be creative to flush out my example, but I'll give what I can to start the process)
```
//WindowsFormsApplication
//Add MenuStrip to form.  with Download Menu Item
//Add Button to Form
//Add System.Timers.Timer to the Form (not Forms.Timer)
//Add Status Strip with label, progressbar, and label on it

        private bool Downloading { get; set; }
        private DateTime? DownloadComplete { get; set; }

        private async void DownloadSecureData() //<-- this is the offending method.  Toggle void to Task and back to Void and there will always be a warning
        {
            using (LoginForm login = new LoginForm())
            {
                using (CustomWebClient wc = CustomWebClient.InitiateSecureConnection(login, this))
                {
                    await Task.Run(() =>
                    {
                        if ((wc?.IsLoggedIn).GetValueOrDefault())
                        {
                            this.Downloading = true;                            
                            //Do asynchronous downloading of data, or whatever process that would naturally interrupt
                            //the UI
                        }
                    });
                }
            }
        }

        private void UpdateEnableds()
        {
            if (this.InvokeRequired) this.Invoke(new CrossThread(this.UpdateEnableds));
            else
            {
                if (_progBar.Visible && this.DownloadComplete.HasValue)
                {
                    this.Downloading = false;
                    if ((DateTime.Now - this.DownloadComplete.Value).Seconds >= 10)
                    {
                        _progBar.Visible = false;
                        _infoStatusLabel.Text = String.Empty;
                        this.DownloadComplete = null;
                    }
                }
                _timeStatusLabel.Text = DateTime.Now.ToString("ddd, dd MMM yyyy - HH:mm:ss");
                this.Enabled = !this.Downloading;
            }
        }

        public void Report(ProgressEventArgs value)
        {
            if (this.InvokeRequired) this.Invoke(new ReportProgress(this.Report), value);
            else
            {
                if (!_progBar.Visible)
                {
                    _progBar.Value = 0;
                    _progBar.Visible = true;
                }
                if (value.StatusMessage == null) _infoStatusLabel.Text = String.Empty;
                _progBar.Value = value.Percentage;
                _statusBar.Refresh();
                Application.DoEvents();
                Application.DoEvents();
                if (value.Percentage == 100) this.DownloadComplete = DateTime.Now;
            }
        }

        private void _downloadMenuButton_Click(object sender, EventArgs e)
        {
            this.DownloadSecureData();
        }

        private void _downloadFormButton_Click(object sender, EventArgs e)
        {
            this.DownloadSecureData();
        }

        private void _timer_Elapsed(object sender, System.Timers.ElapsedEventArgs e)
        {
            this.UpdateEnableds();
        }

        delegate void CrossThread();
        delegate void ReportProgress(ProgressEventArgs value);
```

2. Granted that you can make this work with the other classes not fully defined, I believe they can be inferred from the context.  if that is not the case let me know and I'll get a more flushed out example. 

3. The key element here is the    DownloadSecureData()  method.  

### Expected behavior
To choose one of the two errors, not flip flop back and forth.  (I personally say remove 3168, because the what the rule says is wrong is exactly what I want to achieve).

### Actual behavior
3168: don't use 'async void' because that suggests Fire and Forget
3241: use 'void' because nothing uses return value (which = Fire and Forget)

Looking at the DownloadSecureData() method, the nature of the method is to be a "Fire And Forget" method within the UI.  However, the method is more complicated than a simple Event Handler.
When the method is async, which is necessary for the "await" instruction, the conflict arises on whether I use the "void" or "Task" return values.  As you can see the method accesses a Form(), which as we all know needs to exist within the singular GUI Thread, or Application Thread.  the DownloadSecureData cannot be entirely in a separate thread, it has to exist in the main thread.  But the download process inside the Task.Run(() => { }) call is too lengthy to keep in synchronous execution, and it hinders progress reporting and other form interaction.  I believe that a application should never "freeze" because of a back ground process.

Being that it is "Fire and Forget" because the timer (another thread) reads the "Downloading Flag" and updates the enabled controls based upon the Downloading flag.  if the processing thread is active, the parts of the form are disabled.  
But since this method is NOT a control event handler, RSPEC-3168 is raised, saying to return Task.  Now, i don't need or want to return anything, because the method is a fire and forget, loading other objects that will be referenced by the form when the operation is completed.

If i change that "void" to "Task" i get RSPEC-3241 complaining along with CS4014.  4014 complains that the two event handlers are not "awaiting" the method that returns a "Task", but i can't "await" the method there because it will multi-thread the login form and thus cause thread invocation exceptions.  
3241 complains at the same place as 3168 by saying "Since nothing uses the returning task, use 'void' instead." Now, there may be a hundred different ways to refactor this, and sure that is something for a larger discussion.  

It's a never-ending circle.  

### Known workarounds
Ignore, or Pragma

Hack:  make the "async" method follow the pattern of an event handler:
`private async void DownloadSecureData(object sender, EventArgs e)
`
It is NEVER used as an event, so that signature should not be necessary and screams code smell to me.

### Related information

* SonarLint for VS Version: 3.10.0.3095
* Visual Studio Version : 14.0 Update 3
* SonarQube server version: Version 6.7.1 (build 35068)
* Languages in your solution: C#

**Comment by valhristov** [comment]
Thank you for the extensive analysis. I agree with your points and I see the same solutions for the problem as you:
- refactor the method so that it returns `Task` and `await` it in the two wrappers `_downloadFormButton_Click` and `_downloadMenuButton_Click`. This way both rules should be satisfied.
- change the async method signature to match an event handler and use it instead of the two wrappers.
- ignore or pragma - that's the easiest, especially if you know this method is "fire and forget" and the potential errors are handled (e.g. exceptions are lost if async method is not awaited)
