### ISSUE TITLE
InvalidOperationException thrown

### ISSUE THREAD

**Issue by madskristensen** [SonarSource/sonarlint-visualstudio#594]
### Description

We're seeing VS crashes being reported by Watson coming from SonarLint. An InvalidOperationException is being thrown by a call to `System.Linq.Enumerable.SingleOrDefault` somewhere in the **SonarLint.VisualStudio.Integration** dll with the error message *Sequence contains more than one matching element*.

Unfortunately, we cannot tell exactly where in the source code the issue occurs, only that it is in the SonarLint.VisualStudio.Integration module.

### Repro steps

N/A

### Known workarounds

A possible fix is to change the call from `SingleOrDefault` to `FirstOrDefault` which doesn't throw when there are duplicate values in the collection.

### Related information

* SonarLint for VS Version **unknown**
* Visual Studio Version **2015 and 2017**

If you have any questions, feel free to send an email to madsk@microsoft.com

Thanks,
Mads Kristensen
Visual Studio Extensibility

> PS. If you care to ship your .pdb files inside the VSIX container then we have a better chance at debugging the exact location of these types of issues. It will add to the overall weight of your .vsix file, so I understand if you are hesitant to do so.

**Comment by duncanp-sonar** [comment]
Thanks for the info @madskristensen. We'll take a look.
