### ISSUE TITLE
Visual Studio asking to disable SonarLint due to 5 second startup time...

### ISSUE THREAD

**Issue by usmrtester** [SonarSource/sonarlint-visualstudio#604]
### Description

See Image

### Repro steps

Start Visual Studio

* SonarLint for VS Version - 3.10.0.3095
* Visual Studio Version (e.g. Professional v15.4.1) - v15.6.5
* SonarQube server version - NA
* Languages in your solution (C#, VB.Net, Javascript, C, C++) C#

![sonarpic](https://user-images.githubusercontent.com/32103332/38388010-86006134-38df-11e8-9f46-0bd5f6c588d7.PNG)

**Comment by michalb-sonar** [comment]
Thanks for reporting @usmrtester.
This will be fixed in upcoming version: https://github.com/SonarSource/sonarlint-visualstudio/issues/539
There is already an RC you're welcome to try out: https://github.com/SonarSource/sonarlint-visualstudio/releases/tag/4.0-RC1
