### ISSUE TITLE
[Support request] Binaries for VS2017 community on mac

### ISSUE THREAD

**Issue by lrk** [SonarSource/sonarlint-visualstudio#607]
Hello,

is it possible to add support for VS2017 community on mac ?

thank you

**Comment by Evangelink** [comment]
Hi @lrk,

We will have a look but I am afraid it won't be an easy task as Visual Studio for Mac is not offering the same features and extensibility as Visual Studio.

**Comment by basdecort** [comment]
We would also like to have an extension for Visual Studio for Mac to support our Xamarin development.

**Comment by OleksiiStr** [comment]
Hi @Evangelink , any news about plugin for Mac version?

**Comment by onurhazar** [comment]
It would be great if I have this extension on VS for Mac

**Comment by alexshikov** [comment]
+1

**Comment by duncanp-sonar** [comment]
Update: currently VS for Mac does not support installing Roslyn analyzers as VSIX extensions.
We've added some notes in the [wiki](https://github.com/SonarSource/sonarlint-visualstudio/wiki/SonarLint-in-other-IDEs#visual-studio-for-mac) on how to manually configure the SonarC# and SonarVB.NET analyzers.

**Comment by Phenek** [comment]
Could it be possible to pack this in to an extension for Visual Studio for Mac?
We definitely need this

**Comment by rajadev2019** [comment]
+1 for Sonar lint on VS for Mac
