### ISSUE TITLE
[New connected mode] Quality profile is not used for test projects

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonarlint-visualstudio#632]
In legacy connected mode, we would not report any issues against test projects. This is because we did not install the NuGet analyzer in the project, and the analyzer embedded in the VSIX would turn itself off for the test project.

Currently, new connected mode runs the VSIX analyzer rules against test projects i.e. we don't install a Nuget, but the rules in the VSIX analyzer are run. We also don't add a ruleset to test projects, so the default SonarWay set of rules is run.

For new connected mode, we should add the ruleset to test projects as well as to non-test projects.

Note: postponed pending the upcoming "Tests as first class citizens" initiative.

### TODO
* decide what the behaviour should be for test projects in legacy mode.
   - in legacy mode, the projects will have explicit references to the Sonar analyzer NuGet packages. However, the analyzer package might be an old version that does not handle test detection correctly.

* decide what the behaviour should be for test projects in new connected mode that reference the SonarC#/VB  NuGet package.
  - this is a corner-case. Projects in new connected mode will not reference the NuGet packages unless the user has explicitly added them. This should be uncommon, and even more so for test projects. In either case, add a reference to the generated ruleset should not cause a problem; it will just mean the QP configuration will be applied to the set of rules that will be run.

**Comment by jaybanaticla** [comment]
Hi duncanp-sonar,

We are facing the same issue where we cannot add a ruleset on our test projects. Just wanted to reach out to you how I can exactly do the option #2 you have provided? 

Thanks much in advance!

**Comment by duncanp-sonar** [comment]
Hi Jay,
You should just be able to manually add a ruleset to a test project (although probably what you want to do is add a _link_ to generated SonarLint ruleset instead, so the test projects will pick up any changes from the server). Are you saying you are not able to manually add a ruleset? If so, what error are you getting?
