### ISSUE TITLE
SonarLint for VS 2017 4.0.0.3479 likely caused 6 seconds of unresponsiveness

### ISSUE THREAD

**Issue by Evangelink** [SonarSource/sonarlint-visualstudio#647]
### Description

On every start of VS 2017 I have a message saying the extension caused unresponsiveness of VS.
![image](https://user-images.githubusercontent.com/11340282/40365023-f432293a-5dd3-11e8-9ec3-23204d0c62e0.png)

### Related information

* SonarLint for VS Version: 4.0.0.3479
* Visual Studio Version: 15.7.2

**Comment by duncanp-sonar** [comment]
See MSDN article: [Measuring extension impact in startup](https://docs.microsoft.com/en-us/visualstudio/extensibility/how-to-diagnose-extension-performance)

When opening Visual Studio without a solution, the only SonarLint package that has a _Manage Visual Studio Performance_ entry in the activity log is the _SonarLintNotificationsPackage_ (c26b6802-dd9c-4a49-b8a5-0ad8ef04c579)

**Comment by duncanp-sonar** [comment]
Two of the remaining three packages have been converted to be asynchronous so the gold bar should appear less frequently.
There is one package still to be converted (_SonarLintIntegrationPackage_). There isn't time in the Milestone 4.2 to convert it.

**Comment by duncanp-sonar** [comment]
Update: the _Telemetry_ package (_4E057B4B-E2B8-490D-95D8-2A1A4E7ACAED_) is now loaded asynchronously, but still appears in the _activity.log_ in the _Manage Visual Studio Performance_ security. However, the gold bar does not appear saying SLVS is causing a delay, so I will close this ticket.
We may still need to do some more performance work in the future.
