### ISSUE TITLE
Support connect mode for c/c++ analyse

### ISSUE THREAD

**Issue by louislau86** [SonarSource/sonarlint-visualstudio#650]
what's the plan for sonarlint to support connect mode with c++ check?  Expecting for your response, thank you

**Comment by Evangelink** [comment]
ping @christophelevis

**Comment by fmallet** [comment]
Hi @louislau86, thanks for you interest for this feature. Unhappily, we're not yet able to provide any deadline for this support for the connected mode with C++ checks. This is definitely something which will be done but it's not yet in our short term roadmap. Thanks for your understanding.
Freddy
