### ISSUE TITLE
Regexes are not synced from connected project

### ISSUE THREAD

**Issue by sobjornstad** [SonarSource/sonarlint-visualstudio#693]
### Description

I can switch rules on and off on the SonarQube server and those changes are reflected in the connected SonarLint project once I sync it. However, if I change a naming convention regex and try to sync that change, SonarLint never notices and is always stuck on the default expression.

### Repro steps

1. Create a custom quality profile in SonarQube.
2. Turn on a naming convention rule and modify a regex.
3. Create a project in SonarQube (we use the VSTS extension, so I did this by building some new code and having the extension automatically create the nonexistent project).
4. Install the SonarLint extension, connect to the SonarQube server, and connect to the project.
5. Open a code file and create a variable that matches the new regex but not the default one.

### Expected behavior

SonarLint retrieves the regex that was set on the server that works correctly during SonarQube analysis and the variable is identified as named correctly.

### Actual behavior

SonarLint continues to use the default regex even after resyncing, and the variable is incorrectly flagged as not matching project naming conventions.

### Known workarounds

Have not found any except to turn off the naming rules.

### Related information

We don't store configuration information or rules in the project itself; the rules are all being grabbed from the default quality profile. This may have something to do with the issue.

* SonarLint for VS Version - **4.1.0.3539**
* Visual Studio Version (e.g. Professional v15.4.1) - **Enterprise 2017 15.5.1**
* SonarQube server version - **6.7.3 (build 38370)**
* Languages in your solution (C#, VB.Net, Javascript, C, C++) - **VB.NET**

**Comment by duncanp-sonar** [comment]
@sobjornstad this is covered by #176. That ticket contains a manual workaround.

**Comment by sobjornstad** [comment]
Thanks!
