### ISSUE TITLE
Really confused how to use connected mode

### ISSUE THREAD

**Issue by gregpakes** [SonarSource/sonarlint-visualstudio#722]
### Description

We use SonarCloud and I want to start using SonarLint.  My issue is that I can't get it to work for my team members.

I set it up against one of our projects and commited the **.sonarlint** folder into git (I can't find documentation as to whether this is correct).  Anyway - it all worked for me.

The issue now is that when another team member opens the solution with SonarLint installed, they get the following:

![image](https://user-images.githubusercontent.com/102243/45090842-dfcdab80-b153-11e8-9b94-01e698564278.png)

They have not been asked to enter any credentials and I can't see how to get it to ask for credentials.

### Expected behavior

I would expect SonarLint to ask the user for credentials.

### Actual behavior

It tries to connect to the project and fails.

### Related information

* SonarLint for VS Version 4.4.0.3745
* Visual Studio Version (e.g. Professional v15.71)
* SonarQube server version - SonarCloud
* Languages in your solution (C#)

**Comment by duncanp-sonar** [comment]
@gregpakes this looks like a bug.

Committing the _.sonarlint_ folder is the correct thing to do if you want to share the connection with team members. However, the files in the folder only contain the pointer to the server and the project.
The credentials are stored using the Windows Credential Manager (so they are per-user and per-machine). SonarQube/Cloud projects can allow anonymous access to view projects, so if SonarLint finds a _.sonarlint_ folder but no credentials it will attempt to connect to the server anonymously, which is probably what is happening here. Anonymous connections to SonarCloud are allowed but can only see public projects, leading to the error you describe above.

### Workaround
Create a new dummy project in a new solution and bind it to that project in SonarCloud. The user should be prompted for credentials, which will be stored by the Credential Manager. The dummy project and solution can then be discarded. SonarLint should then use those credentials when opening the "real" bound solution.

**Comment by gregpakes** [comment]
Thanks so much.

**Comment by StephenLarkin** [comment]
Sorry, just noticed that this has been closed. I've been tracking this as it's a blocker to rolling out this extension to all of our developers, asking them all to do this workaround is not really an option for us.

Is this going to be fixed, or is this intended functionality?

**Comment by duncanp-sonar** [comment]
@StephenLarkin I created a separate bug to track the issue (#726) - please track that
(perhaps I should just have edited the title and description of this issue).

**Comment by StephenLarkin** [comment]
Ah, okay, thanks, I shall keep an eye on that one then.
