### ISSUE TITLE
Bind a project in VS code with SonarQube using SonarLint

### ISSUE THREAD

**Issue by AmudhaD** [SonarSource/sonarlint-visualstudio#725]
### Description

Hi,

I am trying to Bind a project in Visual Studio code with SonarQube using SonarLint
Could you please help with the steps to do it?
All I find information with respect to Visual Studio not Visual Studio Code

In other terms I want to Sync the rules from SonarQube in Visual studio code using SonarLint,
I have updated the required user settings and workspace settings.

Thanks,
Amudha

**Comment by AmudhaD** [comment]
Hi,
I am able to bind the project using workspace settings
Please help me understand on displaying the SonarQube errors in VS code connected through SonarLint.

**Comment by duncanp-sonar** [comment]
Hi @AmudhaD,

This repo is for issues specific to SonarLint for Visual Studio (and the folk monitoring it don't have detailed knowledge about SonarLint for VS Code).

Please start a thread in the community forum: https://community.sonarsource.com/c/help. Thank you.

**Comment by AmudhaD** [comment]
Sure..thanks !
