### ISSUE TITLE
Object reference not set to an instance of an object when trying to sync project.

### ISSUE THREAD

**Issue by PawelKm** [SonarSource/sonarlint-visualstudio#729]
### Description

Exception during execution.

### Repro steps

1. Analyse project.
2. Mark one of issues as won't fix.
3. Connect to SQ server via SonarLint in Visual Studio.
4. Bind project.
5. Try to update.

### Expected behavior

Suppressions are correctly synced and excluded from warnings after successful build.

### Actual behavior

Updating binding...
Binding solution to SonarQube project: Started
Binding solution to SonarQube project: Discovering solution projects
   Included projects:
   * **********************.csproj
   * **********************.Unit.Tests.csproj
   * **********************.Integ.Tests.csproj
   * ...
   You can change the exclusion options via the SonarLint project-level context menu i.e. Solution Explorer -> Select project(s)
Binding solution to SonarQube project: Download quality profile(s):
   Successfully downloaded quality profile. Name: '**********************', Key: '\*\*********************', Language: 'C#'
INFO: SonarLint connected mode no longer installs the analyzers NuGet packages. The analyzers embedded in the VSIX are used instead.
Binding solution to SonarQube project: Generating project rule sets
Binding solution to SonarQube project: Completed successfully
Checking for suppressions...
**Failed to fetch suppressions: Object reference not set to an instance of an object.**

### Known workarounds

None.

### Related information

* SonarLint for VS Version       4.4.0.3745 (tested also with 4.5.0.3786 same result)
* Visual Studio Version            Enterprise 2017 15.8.5 (tested also with 15.8.6 same result)
* SonarQube server version    7.3 (build 15553) with C# plugin 7.5 (build 6605)
* Languages in your solution (C#, JavaScript, TypeScript, xml)

**Comment by Evangelink** [comment]
Hi @PawelKm,

I will keep this issue closed for the moment (as the NRE is fixed) and I will create a new ticket for your new problem. It's easier for us to track.
