### ISSUE TITLE
SonarLint dont use the rules that i have in sonarqube for Javascript

### ISSUE THREAD

**Issue by josedecima** [SonarSource/sonarlint-visualstudio#730]
### Description
In sonarqube i have the set of rules sonarqube recommended for javascript and in the page show 16 code smells in one file , but the in visual studio i made the analysis in the same file and show only 3 warning.

Then if i make one update of sonarqube always only change the .slconfig file but dont add the profile for js only add the profile for csharp

"Profiles": {
    "CSharp": {

### Expected behavior
I expect the same qty of warning in sonarqube and visual studio 2017 for csharp and javascript

### Actual behavior

Only show csharp warning in visual studio 2017 , 

slconfig only show 

"Profiles": {
    "CSharp": {

and the rulset for csharp and not for js

### Related information

* SonarLint for VS Version
* Visual Studio Version (e.g. Professional v15.4.1)
* SonarQube server version
* Languages in your solution (C#, Javascript)

**Comment by duncanp-sonar** [comment]
Connected Mode is not currently supported for JavaScript (or C++) so the default set of rules will always be used. This issue is tracked by #770.
