### ISSUE TITLE
Dim unused code rather than highlighting the whole method

### ISSUE THREAD

**Issue by christophelevis** [SonarSource/sonarlint-visualstudio#755]
### Description

For rules about unused code such as `csharpsquid:S1144: Unused private types or members should be removed`, the whole body of the method is highlighted. Other issues are not visible, and it's not comfortable to write code in this situation. 

### Expected behavior

We should rather dim the unused code the same way Visual Studio does and, ideally, highlight only the name of the unused method.

**Comment by valhristov** [comment]
Related issue is closed.
