### ISSUE TITLE
Add support for connected mode for JavaScript/TypeScript

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonarlint-visualstudio#770]
Currently connected mode is only supported for C# and VB projects, even though SLVS supports analysis C++ and JavaScript code. This means that C++ and JavaScript are always analysed using the SonarWay ruleset, rather than using the rules configured in the Sonar Quality Profile for the Sonar project.

UPDATE: support for C++ connected mode was added in [v4.15](https://github.com/SonarSource/sonarlint-visualstudio/releases/tag/v4.15.0.14069).

Users using these other supported languages should be able to connect their solutions to SonarQube/Cloud so that the set of rules run in the IDE is the same as the set of rules configured on the server.

### Current behaviour

Users attempting to connect to SonarQube with a solution that does not contain a C# or VB project will see the following dialogue:
![image](https://user-images.githubusercontent.com/10757559/49277496-b03fee00-f479-11e8-9b48-8adccf84751e.png)
If the solution does contain a C#/VB project then the user will be able to connect, but only the C#/VB projects will be configured to use the rules specified on the server. It isn't immediately obvious to the user that only some of the projects in the solution have been configured (although this information does appear in the SonarLint output window).

### Related information

* SonarLint for VS Version: all (currently version is 4.7)

Related ticket about configuring rules in standalone mode: #771 
Related ticket for C/C++ projects: #1096 

Additional features that will need to be adjusted once Connected Mode is added: 
- [ ] Help links for Hotspots and Taint Vulnerabilities (see #2411)

**Comment by ThatShawGuy** [comment]
Can the slconfig file be manually updated to include a JavaScript profile section with the appropriate ProfileKey and ProfileTimestamp properties? Or will it still not be able to hook into the JavaScript profile in SonarQube?

**Comment by duncanp-sonar** [comment]
@ThatShawGuy no, manually updating the `.slconfig` won't work, unfortunately. JavaScript isn't in the list of supported languages handled by by the SLVS code, so it won't try to pull down the JavaScript profile.

**Comment by vasu04** [comment]
@duncanp-sonar  is this issue still underdevelopment. I am also facing a similar issue.
![image](https://user-images.githubusercontent.com/8501117/96220608-a6103580-0fa6-11eb-8839-6b4265b3922c.png)

**Comment by duncanp-sonar** [comment]
@vasu04 it's still in the backlog but we don't have a timescale for implementation. It's unlikely to be this calendar year, I'm afraid.

**Comment by mirdaDev** [comment]
Hi, it would be great to have this feature. Any feeling about integration ?

**Comment by Swatibovi** [comment]
Hi @duncanp-sonar  any update on this issue? Can we expect this anytime soon?

**Comment by duncanp-sonar** [comment]
@Swatibovi It's on the roadmap for this year. I can't be more specific than that.

**Comment by duncanp-sonar** [comment]
Status: the feature is complete, but the release is blocked by #3138.
