### ISSUE TITLE
Lexical error in S4069?

### ISSUE THREAD

**Issue by mprochaska** [SonarSource/sonarlint-visualstudio#773]
I am new to SonarLint so please bear with me.

I am analyzing old source code that is running afoul of S4069: Operator overloads should have named alternatives for my operator overloads of <, <=, >, >= in a struct.

The rule cries I must implement 'Compare', but I am already implementing the intrfaces IComparable, IComparable<T> which necessitate 'CompareTo' method, this method is implemented.

String has a static Compare method.  Int32 does not.

Is there a lexical error in the implementation of the rule 'Compare' instead of 'CompareTo' or am I being daft?

Thank you,

~Michael

### Related information

* SonarLint for VS Version: 4.7.0.3891
* Visual Studio Version: Microsoft Visual Studio Community Edition 15.8.7
* SonarQube server version: (n/a)
* Languages in your solution (C# 7.2)

**Comment by valhristov** [comment]
This rule is equivalent of FxCop's [CA2225](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2225-operator-overloads-have-named-alternates?view=vs-2017). And you are right that FxCop considers `Compare` and `CompareTo` semantically equivalent. This is an omission on our side and we'll fix it in the next release of SonarC#.

**Comment by mprochaska** [comment]
Thank you :)
