### ISSUE TITLE
Enable install on VS2019 Preview for dogfooding

### ISSUE THREAD

**Issue by Larswa** [SonarSource/sonarlint-visualstudio#774]
### Description

Visual Studio 2019 Preview not supported

### Repro steps

Sonarlint is not shown as an option when searching for sonarlint from VS 2019 extensions.

Suggestion:
Would it be possible to update the .vsixmanifest to support VS2019, as described in Mads Kristensens blogpost here?  :
https://blogs.msdn.microsoft.com/visualstudio/2018/09/26/how-to-upgrade-extensions-to-support-visual-studio-2019/

For many extensions the changes seems minimal, and this could be the only thing keeping us from enjoying Sonarlint in VS 2019.

**Comment by duncanp-sonar** [comment]
@Larswa thanks for the feedback. We're planning on adding support for VS2019 early next year (if possible, in January).

**Comment by duncanp-sonar** [comment]
We'll trying updating the manifest for the VS2017 extension to make it installable in the VS2019 preview to get feedback about any issues.

I've created a separate ticket for full support of VS2019 RTM once it's released: #780

**Comment by duncanp-sonar** [comment]
Pre-release build available [here](https://github.com/SonarSource/sonarlint-visualstudio/releases/tag/v4.7.28408.50-alpha).
