### ISSUE TITLE
SonarLint does not suppress issues over 10k SonarQube API limit

### ISSUE THREAD

**Issue by roger-cazangi** [SonarSource/sonarlint-visualstudio#776]
### Description

We have a legacy application with lot of technical debt. There are more then 10k resolved issues today, but SonarLint does not suppress a lot of resolved issues on server. Debbuging the source code we found that it hapends because of de 10k limit of Issues API, used to suppress issues. Are there some improvement planned to handle this limitation? Please, do you have any suggestion of workaround to resolve this scenario?

### Repro steps

Please provide the steps required to reproduce the problem

1. Create a project with more then 10k issues and run SonarQube analysis for it;

2. Resolve more then 10k issues, by configuring "Source File Exclusions" on project, for example;

3. Run a new SonarQube analysis for project;

4. Open the project on Visual Studio 2017 using SonarLint on Connected Mode;

### Expected behavior

All issues resolved at server should by suppressed by SonarLint.

### Actual behavior

Only 10k resolved issues are suppressed by SonarLint, not all of them.

### Known workarounds

No workarounds found.

### Related information

* SonarLint for VS Version - 4.7
* Visual Studio Version - Professional 2017
* SonarQube server version - 7.2.0.13530
* Languages in your solution - C#

**Comment by valhristov** [comment]
I chose to create a new Request, which wraps the existing one and executes it multiple times with different arguments (e.g. `types`). This way the existing request does not change (much) and the service is kept clean from knowledge of the connected SQ version. In addition, the wrapper could be removed when the Web API removes the response limitation.
