### ISSUE TITLE
Add support for VS2019 RTM

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonarlint-visualstudio#780]
Add support for the RTM version of VS2019

### TODO
* finalise decision on whether to release a separate extension for VS2019, or to support both VS2017 and VS2019 in a single extension
* testing
* update the marketplace
* product announcements/marketing

**Comment by PeteBoyRocket** [comment]
This is closed but I cannot find SonarLint in the VS2019 extensions?

**Comment by duncanp-sonar** [comment]
@PeteBoyRocket [the page for the VS2019 extension](https://marketplace.visualstudio.com/items?itemName=SonarSource.SonarLintforVisualStudio2019) has just been made public on the marketplace.
