### ISSUE TITLE
[C++] Huge JVM resource consumption leading to VS freezing

### ISSUE THREAD

**Issue by loic-joly-sonarsource** [SonarSource/sonarlint-visualstudio#781]
### Description
Disclaimer: I was running an experimental version of SonarLint, so the problem itself might manifest differently on the official version, but I believe the root cause would still be there, and still be a big issue.

In a C++ project, create a class with a function declaration. Add a definition following the steps described here: https://docs.microsoft.com/en-us/cpp/ide/refactoring/create-declaration-definition?view=vs-2017

The .cpp file will appear inside of the .h file, as an embedded popup. Click next to the file name to open it in a normal window.

Then, mayhem happens...
Apparently, SonarLint instantly tries to analyze many files at the same time (really, MANY, but it's hard to say), and this leads to huge resource consumption (100% processor, 100% memory, disk was swapping continuously, mouse almost frozen). I barely managed to close the impacted files in visual studio, and after some time, the situation calmed down a little, but by that time visual studio was no longer responsive (I had to kill it), and the Java process of SonarLint took up to 7Gb of memory.

I tried to reproduce this situation, but failed.

### Expected behaviour
- There should be a hard maximum to the number of analyses that SonarLint triggers in parallel
- Why did this operation start so many analyses?

**Comment by duncanp-sonar** [comment]
Update: neither Loïc nor I were able to repro this. Loïc has increased the SLVS logging verbosity to try to get more info it happens again.

**Comment by duncanp-sonar** [comment]
Closing as no longer applicable.
Since [v4.12](https://github.com/SonarSource/sonarlint-visualstudio/releases/tag/v4.12.0.10939) C++ analysis no longer involves the JVM.
