### ISSUE TITLE
[TFS] Updating an existing binding fails

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonarlint-visualstudio#801]
### Description

Updating an existing binding fails when the source control system is TfVC.
It works correctly for Git.

### Repro steps

1. Create a solution, commit it to TfVC, and bind the solution to SonarQube.

2. Go to the SonarQube pane in the _Team Explorer_ and select _Update_

### Expected behavior

The binding update succeeds.

### Actual behavior

The update fails. The following gold bar is displayed.

![image](https://user-images.githubusercontent.com/10757559/51193237-4cb23880-18e0-11e9-93d1-ea435aa56464.png)

There is no useful information in the output window.

![image](https://user-images.githubusercontent.com/10757559/51193292-6e132480-18e0-11e9-85b4-270c8727f28c.png)

### Known workarounds

Manually check out the files under the _.sonarlint_ folder before updating the binding:

![image](https://user-images.githubusercontent.com/10757559/51193695-643df100-18e1-11e9-94d4-4438df62414f.png)

### Related information

* SonarLint for VS Version: 4.7
* Visual Studio Version: VS2015 and VS2017, all SKUs
* Languages affected: C\, VB

### Notes
On debugging, the failure is happening when attempting to check the files for edit in [this line](https://github.com/SonarSource/sonarlint-visualstudio/blob/aadf9950c7d2eb3a6978738e071de752a4fcd1f5/src/Integration/LocalServices/SourceControlledFileSystem.cs#L159).
The error code that is returned is ok so the code does not throw.
However, the _verdict_ is not _QER_EditOK_ so the method returns 
The [_moreInfo_](https://docs.microsoft.com/cs-cz/dotnet/api/microsoft.visualstudio.shell.interop.tagvsqueryeditresultflags?view=visualstudiosdk-2017) value is 272 i.e. QER_ReadOnlyUnderScc | QER_NoisyCheckoutRequired

**Comment by Pradeep1409Bora** [comment]
Is it working without the workaround?

Because we are still facing this issue with SonarLint 4.8.0.4040

Output Window :-
Binding solution to SonarQube project: Generating project rule sets
Failed to check out files for editing. Error flags: QER_InMemoryEditNotAllowed, QER_CheckoutCanceledOrFailed, QER_ReadOnlyUnderScc
Saving notifications settings...
