### ISSUE TITLE
[C++] Analysis fails if the toolset is not specified

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonarlint-visualstudio#804]
### Description

If the _PlatformToolset_ is not specified in the project file then VS will use a default toolset.
However, SonarLint will not 

### Repro steps

1. Create a new C++ project

2. Clear the _Platform Toolset_ field as shown in the screenshot below and click OK

![image](https://user-images.githubusercontent.com/10757559/51339423-4d83cf80-1a84-11e9-84b9-d0c507a82047.png)

3. Open the save a _.cpp_ file

### Expected behavior

The daemon analyzes the file successfully.

### Actual behavior

The daemon fails to analyze the file. The text in the SonarLint output window is:
```
Unable to collect C/C++ configuration for C:\Code\VS2017\Bugs\Cpp\SLVS767\test\mydemo\ConsoleApplication1\ConsoleApplication1\ConsoleApplication1.cpp: System.ArgumentException: Unsupported PlatformToolset: 
Parameter name: platformToolset
   at SonarLint.VisualStudio.Integration.Vsix.CFamily.FileConfig.ConvertPlatformToolset(String platformToolset)
   at SonarLint.VisualStudio.Integration.Vsix.CFamily.FileConfig.ToCaptures(String path, String& sqLanguage)
   at SonarLint.VisualStudio.Integration.Vsix.CFamily.FileConfig.ToJson(String path, String& sqLanguage)
   at SonarLint.VisualStudio.Integration.Vsix.CFamily.TryGetConfig(ILogger logger, ProjectItem projectItem, String absoluteFilePath, String& sqLanguage)
```

~~However, the project will still build. More accurately, VS will decide what default toolset is, and the build will succeed if that toolset is installed on the machine. To check which toolset is actually being used, build the project with diagnostic output turned on and search for the text _PlatformToolset =_~~

Update: re-tested, and the build fails on VS2015, VS217 and VS2019 if the `PlatformToolset` is not specified. The failure message is unhelpful

```
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(379,5): error MSB4018: The "VCMessage" task failed unexpectedly.
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(379,5): error MSB4018: System.FormatException: Index (zero based) must be greater than or equal to zero and less than the size of the argument list.
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(379,5): error MSB4018:    at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
...
```

We could fall back on using the `DefaultPlatformRuleset` e.g. `config.Rules.Item("ConfigurationGeneral").GetEvaluatedPropertyValue("DefaultPlatformToolset")`

However, since the project won't build then arguably guessing at the platform toolset and trying to analyse the source code is not the right thing to do. It also suggests that this scenario isn't very common since a project that doesn't build because a key setting is missing is not very useful.

**Decision:** for now, we'll simply output a more useful message in the output window.

### Known workarounds

Explicitly specify a platform toolset.

### Related information

* SonarLint for VS Version: 4.7
* Languages affected: C/C++

**Comment by valhristov** [comment]
Related to #738
