### ISSUE TITLE
[Support] Can't install dogfood VS2019 build on VS2019 Preview 2

### ISSUE THREAD

**Issue by AceHack** [SonarSource/sonarlint-visualstudio#814]
![image](https://user-images.githubusercontent.com/578953/52657665-2bd10900-2ec7-11e9-97e2-be6f42326067.png)

**Comment by duncanp-sonar** [comment]
Are you trying to install the dogfood build on VS2019 Preview 2?
The dogfood build will on install in Preview 1. We'll release another dogfood build shortly.

**Comment by AceHack** [comment]
Latest preview build

**Comment by AceHack** [comment]
By the way Update, 3 just came out so I would be looking for support for update 3.  Thanks.

**Comment by ThatShawGuy** [comment]
I'm also looking for a version that supports Preview 3.0. Let us know when that is available.

**Comment by duncanp-sonar** [comment]
@AceHack, @ThatShawGuy 
FYI there's a [new pre-release of SonarLint for VS2019](https://github.com/SonarSource/sonarlint-visualstudio/releases/tag/v4.7.28608.199-alpha) that is installable on VS2019 Preview 3.0.

**Comment by ThatShawGuy** [comment]
@duncanp-sonar It's working well for me so far, thank you!

**Comment by SquaLLpt** [comment]
Can't install on VS2019 Preview 4.0, the following occurs:

![image](https://user-images.githubusercontent.com/45943973/54820772-2ae68080-4c98-11e9-93fc-3d5989e4c1ac.png)
