### ISSUE TITLE
[Connected Mode] Stop generating project-level ruleset when project has no rulesets

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonarlint-visualstudio#817]
### Description

Currently connected mode creates a per-project ruleset file that in turn references the generated solution-level ruleset. This was to provide developers with an easy way to customise the ruleset for each project (i.e. they could just customise the per-project ruleset).

However, this has led to complaints about the number of files being added by connected mode, and the ability to customise project-level rulesets does not seem to be widely used.

### Proposal

* when creating new bindings, stop creating project-level rulesets when the project has no defined rulesets.
* instead, directly reference the generated-solution level ruleset from the project

### Related information

* SonarLint for VS Version: all (current is 4.8)

**Comment by TeunKooijman** [comment]
Hi Duncan! I was wondering if there are any updates on this, as we are currently experiencing some strange behavior that might be attributable to this. We are running `SonarQube 7.6` in association with `SonarLint for Visual Studio 2019 4.14.0.12332`, and the project-level ruleset files automatically enable `S2479 - Whitespace and control characters in string literals should be explicit`. This rule does not seem to exist until `SonarQube 8.0` (if I am not mistaken), and is also not present in the response of `/api/qualityprofiles/export?exporterKey=sonarlint-vs-cs&key=someQualityProfileKey`, or the solution-wide ruleset in the `.sonarlint` directory. When deleting the project-level rule sets, all is well and good, but upon updating the connected Quality Profile, they are generated again, and the rule is once again enabled. 

I would love to hear your thoughts on this, as there's a good chance I'm overlooking something or not grasping some of the concepts correctly. Thanks in advance for any help!

**Comment by duncanp-sonar** [comment]
Hi @TeunKooijman. This ticket won't have an impact in the situation you describe - the level of indirection via the per-project ruleset won't exist, but the generated ruleset will be the same so the same rules will be enabled/disabled.

In your case, if you are using a version of SonarLint that has a newer version of the `sonar-dotnet` analysers than the one in the Java plugin then the generated ruleset won't contain an entry for any new rules.

I've had a quick look and S2479 is enabled by default, so in the situation you described I'd expect it to raise issues in both standalone and connected mode. If you want to disable S2479 then you would have to do it explicitly in a custom ruleset, and configure your projects to use this ruleset (your custom ruleset would also have to "Include" the generated SQ ruleset, otherwise SonarLint will complain).

If you'd like to discuss this further or need more info please start a thread in the [community forum](https://community.sonarsource.com/c/help/sl/11), since I don't think the situation you are describing is related to this ticket.
