### ISSUE TITLE
[VS2019] Prompt to install support for new languages does not appear for VS2019

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonarlint-visualstudio#826]
### Description

SLVS in 2015/2017 displays a message box after startup to prompt the user to install support for additional languages.

However, VS2019 has a new startup screen that appears before the main UI loads. The SLVS message box no longer appears.

### TODO

* [min-bar] check that there are no adverse side-effects with the current behaviour (e.g. intermittent crashes, freezes, perf gold bars etc).

* [optional] replace the current message box pop with an alternative that works better with the new startup flow e.g. a gold bar

### Related information

* SonarLint for VS Version: 4.8
* Visual Studio Version: VS2019 RC/Preview
* SonarQube server version: N/A

**Comment by Evangelink** [comment]
Cannot reproduce
