### ISSUE TITLE
[Task] Refactor SLVS projects to support building VS2019 artifacts

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonarlint-visualstudio#827]
### Description

We currently have duplicated product and test MSBuild projects for VS2015 and VS2019 (i.e. 2 x 9 projects). We do not want to add another set of nine projects just to add support for VS2019.

Instead, we want to reduce the number of projects to the minimum necessary.

### Steps:
* identify the VS/TFS artifacts that cannot be handled in a version-agnostic way (note: seems just to be the two TeamFoundation assemblies)
* refactor the SLVS assemblies to isolate the version-dependent code
* remove the redundant duplicated projects
* modify the build scripts as necessary to handle the new project structure
* add new VS2019-specific MSBuild project(s)

**Comment by Evangelink** [comment]
Closed by #834
