### ISSUE TITLE
Can't install dogfood VS2019 build on VS2019 Preview 4

### ISSUE THREAD

**Issue by SquaLLpt** [SonarSource/sonarlint-visualstudio#847]
### Description

Can't install on VS2019 Preview 4.0.

### Related information

* SonarLint for VS 2019 Beta for Preview 3
* Visual Studio 2019 Preview 4

![image](https://user-images.githubusercontent.com/45943973/54837448-55e3cb00-4cbe-11e9-9952-03393bf48230.png)

Related issue: #814

**Comment by SquaLLpt** [comment]
Related issue closed: https://github.com/SonarSource/sonarlint-visualstudio/issues/814

**Comment by duncanp-sonar** [comment]
We're currently working on a RC version of SLVS that will install on the latest VS RC. We're aiming to release it on Monday.

**Comment by duncanp-sonar** [comment]
FYI the SLVS RC is now available [here](https://github.com/SonarSource/sonarlint-visualstudio/releases/tag/v.4.9-rc1).

Note however that the SLVS RC is for the latest VS RC release, not the latest VS Preview release.

**Comment by duncanp-sonar** [comment]
[SLVS RC2](https://github.com/SonarSource/sonarlint-visualstudio/releases/tag/v4.9-rc2) is now available. It can be installed on VS2019 RC4 and Preview 4.4.
