### ISSUE TITLE
 ?? operator as S2589

### ISSUE THREAD

**Issue by ilkerkaran** [SonarSource/sonarlint-visualstudio#880]
### Description

sonarlint warnings ?? operator as S2589

### Repro steps

class A
{
public bool booleanVal { get; set; }
}

A aObj = null;
if(aObj?booleanVal ?? false)

You can observe the problem via the code above

**Comment by duncanp-sonar** [comment]
Thanks for reporting this issue @ilkerkaran. I've created issue [2407](
https://github.com/SonarSource/sonar-dotnet/issues/2407) in the "rules" repo, and I'll close this issue.
