### ISSUE TITLE
Support analysis of CMake projects in VS2017 and VS2019

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonarlint-visualstudio#903]
### Description
VS2017 and VS2019 now [provides](https://docs.microsoft.com/en-us/cpp/build/cmake-projects-in-visual-studio?view=vs-2019) better integration with CMake.

However, our C++ analyzers don't current run because we can't detect the configuration settings. The output window contains the following message:
```
Unable to retrieve the configuration for file 'D:\repos\sq\other\sonar-clang\src\core\MetricsComputer.cpp'. Check the file is part of a project in the current solution.
```

### MMF

See https://jira.sonarsource.com/browse/MMF-2286
### Notes

The initial release will have some limitations :
* we use the generated compilation database to fetch the settings, so we'll only support the default Ninja generator that produces a compilation database
* support will be more limited in VS2017; specifically, we won't support the `workspaceHash` and `projectHash` macros (the hash algorithm is different in VS2019, and most of our users are on VS2017 so we'll target VS2019 first). Hash macros in VS2017 are tracked by #2632 ).
* VS2015 does not support CMake projects, so we can't support it either

**Comment by waj334** [comment]
https://developercommunity.visualstudio.com/comments/1283066/view.html

I took the opportunity to ask Microsoft support about a way to support this. Perhaps there should be an option for the user to pick the language while in folder mode.

**Comment by notox** [comment]
Waiting for this feature

**Comment by Livius90** [comment]
Is there any news about when SonarLint will be available for VS2019 CMake projects?

**Comment by duncanp-sonar** [comment]
@Livius90 we're working on this feature at the moment and expect to release the first version at the end of the current sprint.
You can follow the progress [here](https://github.com/SonarSource/sonarlint-visualstudio/projects/31).

**Comment by Livius90** [comment]
Thanks the quick answer. Do i see right that the [standalone mode](https://github.com/SonarSource/sonarlint-visualstudio/projects/24) is almost done in 99%?

**Comment by duncanp-sonar** [comment]
It's being internally dogfood-ed currently. It's not ready for a public dogfood release yet.

**Comment by duncanp-sonar** [comment]
FYI public release is planned for the week commencing 20th September.

**Comment by Livius90** [comment]
Is there any plan to support not just the MSVC compiler in CMake projects?
https://github.com/SonarSource/sonarlint-visualstudio/issues/2684

**Comment by duncanp-sonar** [comment]
@Livius90 compiler support is handle by another team; I don't know if that is in their plans.

I suggest you open a thread in the ["suggest a feature"](https://community.sonarsource.com/c/suggestions/features/14) section of the forum and tag it with `cfamily`. That way the appropriate team/PMs will see it, and other users will be able to vote   on it.
