### ISSUE TITLE
Illegal reflective access by net.sf.cglib.core.ReflectUtils$1

### ISSUE THREAD

**Issue by creage** [SonarSource/sonarlint-visualstudio#921]
### Description

Running SonarLint on ES6 project, Output window states:

``
Using default daemon download URL
Daemon version: 4.3.0.2475
Daemon download url: https://binaries.sonarsource.com/Distribution/sonarlint-daemon/sonarlint-daemon-4.3.0.2475-windows.zip
Initializing the telemetry package...
Finished initializing the telemetry package...
Initializing the daemon package...
Starting the daemon...
Daemon started successfully.
Finished initializing the daemon package.
Initializing the SonarLint package...
Standalone mode detected.
Finishing initializing the SonarLint package
Analyzing C:\Git\WorkZone\WZC\Source\client\sources\App\components\List\plugins\Reorderable\Reorderable.js
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by net.sf.cglib.core.ReflectUtils$1 (file:/C:/Users/z8ziz/AppData/Local/sonarlint/plugins/cc8ad346e85db9d3735898b533d37d34/sonar-javascript-plugin-4.0.0.5862.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of net.sf.cglib.core.ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Initializing the notifications package...
Not connected: not checking for notifications
Finished initializing the notifications package
Found 1 issue(s)
``

### Repro steps

Just open a C# project having some ES6 code

### Expected behavior

No errors?

### Actual behavior

As described above

### Related information

* SonarLint for VS Version : 4.11.0.0
* Visual Studio Version (e.g. Professional v15.4.1): Enterprise 2019 16.1.6
* Languages in your solution: C#, Javascript

**Comment by creage** [comment]
Looks like 4.11.1.0 has fixed the issue

**Comment by creage** [comment]
Sorry for bringing it back, but issue is still there.

**Comment by giggio** [comment]
This seems related: https://github.com/SonarSource/SonarJS/issues/1110

Also, according to this comment, this is not going to be easily fixed: https://github.com/SonarSource/SonarJS/issues/1110#issuecomment-428559109

> as you note, this is just a warning and it can be safely ignored. We cannot fix this warning easily, because it's a dependency of our parser which would need fixing. However we started migration to another parser in 5.0 and gradually we will migrate all rules to the new parser. This will eventually allow to drop dependency on sslr and fix the warning

**Comment by duncanp-sonar** [comment]
Fixing this involves moving to a version of SonarJS in which the parser is re-written to use Node.js (at which point this warning will disappear).

Issue #1188 relates to work we need to do to support Node.js. There isn't anything else we can do in the meantime, so I'll close this ticket as being superceded by #1188.

**Comment by BlackFrog1** [comment]
Just a side note that the issue still exists in version 4.5.0.2216; Knowing it should be resolved in 5.0
