### ISSUE TITLE
Unable to connect to sonarcloud

### ISSUE THREAD

**Issue by alkampfergit** [SonarSource/sonarlint-visualstudio#971]
I've a problem, I've a sonarcloud account where I login with my github credentials.

I'm unable to login into the account from inside visual studio, I've generated a token I've tried with my github password but there is no way to connect.

I've used alkampfergit@github and alkampfergit (with and without @gihub) I've generated a fresh security token but I always got invalid credentials.

Connecting to SonarQube server: https://sonarcloud.io/
Connecting to SonarQube server: Validating credentials
Connecting to 'https://sonarcloud.io/'.
Connected to SonarQube '8.0.0.102'.
SonarQube request failed: Invalid credentials 
Connecting to SonarQube server: Failed

**Comment by alkampfergit** [comment]
Closed. It seems that closing and reopening VS changed something ... now I can connect just fine :P

**Comment by ccabezudo** [comment]
I have the same issue, resolution not working.
